--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(3)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(568.0000, 320.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1136.0000, height = 640.0000})
layout:setStretchWidthEnabled(true)
layout:setStretchHeightEnabled(true)
Scene:addChild(Panel_1)

--Create Panel_2
local Panel_2 = ccui.Layout:create()
Panel_2:ignoreContentAdaptWithSize(false)
Panel_2:setClippingEnabled(false)
Panel_2:setBackGroundColorOpacity(102)
Panel_2:setTouchEnabled(true);
Panel_2:setLayoutComponentEnabled(true)
Panel_2:setName("Panel_2")
Panel_2:setTag(19)
Panel_2:setCascadeColorEnabled(true)
Panel_2:setCascadeOpacityEnabled(true)
Panel_2:setAnchorPoint(0.5000, 0.5000)
Panel_2:setPosition(568.0000, 320.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.0440)
layout:setPercentHeight(0.0781)
layout:setSize({width = 50.0000, height = 50.0000})
layout:setLeftMargin(543.0000)
layout:setRightMargin(543.0000)
layout:setTopMargin(295.0000)
layout:setBottomMargin(295.0000)
Scene:addChild(Panel_2)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("res/public/1900000665.png",0)
Image_1:setScale9Enabled(true)
Image_1:setCapInsets({x = 78, y = 44, width = 82, height = 48})
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(20)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(25.0000, 25.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(4.7600)
layout:setPercentHeight(2.7200)
layout:setSize({width = 238.0000, height = 136.0000})
layout:setLeftMargin(-94.0000)
layout:setRightMargin(-94.0000)
layout:setTopMargin(-43.0000)
layout:setBottomMargin(-43.0000)
Panel_2:addChild(Image_1)

--Create Panel_dice
local Panel_dice = ccui.Layout:create()
Panel_dice:ignoreContentAdaptWithSize(false)
Panel_dice:setClippingEnabled(false)
Panel_dice:setBackGroundColorOpacity(102)
Panel_dice:setTouchEnabled(true);
Panel_dice:setLayoutComponentEnabled(true)
Panel_dice:setName("Panel_dice")
Panel_dice:setTag(22)
Panel_dice:setCascadeColorEnabled(true)
Panel_dice:setCascadeOpacityEnabled(true)
Panel_dice:setAnchorPoint(0.5000, 0.5000)
Panel_dice:setPosition(25.0000, 10.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_dice)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.2000)
layout:setPercentWidth(4.0000)
layout:setPercentHeight(0.6000)
layout:setSize({width = 200.0000, height = 30.0000})
layout:setLeftMargin(-75.0000)
layout:setRightMargin(-75.0000)
layout:setTopMargin(25.0000)
layout:setBottomMargin(-5.0000)
Panel_2:addChild(Panel_dice)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

