--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(190)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPercentHeightEnabled(true)
layout:setSize({width = 640.0000, height = 0.0000})
layout:setRightMargin(-640.0000)
Node:addChild(Panel_1)

--Create Node_monster1
local Node_monster1=cc.Node:create()
Node_monster1:setName("Node_monster1")
Node_monster1:setTag(191)
Node_monster1:setCascadeColorEnabled(true)
Node_monster1:setCascadeOpacityEnabled(true)
Node_monster1:setPosition(465.0000, 250.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_monster1)
layout:setPositionPercentX(0.7266)
layout:setLeftMargin(465.0000)
layout:setRightMargin(175.0000)
layout:setTopMargin(-250.0000)
layout:setBottomMargin(250.0000)
Panel_1:addChild(Node_monster1)

--Create Node_monster2
local Node_monster2=cc.Node:create()
Node_monster2:setName("Node_monster2")
Node_monster2:setTag(192)
Node_monster2:setCascadeColorEnabled(true)
Node_monster2:setCascadeOpacityEnabled(true)
Node_monster2:setPosition(62.0000, 250.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_monster2)
layout:setPositionPercentX(0.0969)
layout:setLeftMargin(62.0000)
layout:setRightMargin(578.0000)
layout:setTopMargin(-250.0000)
layout:setBottomMargin(250.0000)
Panel_1:addChild(Node_monster2)

--Create Node_player
local Node_player=cc.Node:create()
Node_player:setName("Node_player")
Node_player:setTag(193)
Node_player:setCascadeColorEnabled(true)
Node_player:setCascadeOpacityEnabled(true)
Node_player:setPosition(540.0000, 250.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_player)
layout:setPositionPercentX(0.8438)
layout:setLeftMargin(540.0000)
layout:setRightMargin(100.0000)
layout:setTopMargin(-250.0000)
layout:setBottomMargin(250.0000)
Panel_1:addChild(Node_player)

--Create Node_Play
local Node_Play=cc.Node:create()
Node_Play:setName("Node_Play")
Node_Play:setTag(194)
Node_Play:setCascadeColorEnabled(true)
Node_Play:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_Play)
layout:setRightMargin(640.0000)
Panel_1:addChild(Node_Play)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

