--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create ListView_rewards
local ListView_rewards = ccui.ListView:create()
ListView_rewards:setDirection(2)
ListView_rewards:setGravity(3)
ListView_rewards:ignoreContentAdaptWithSize(false)
ListView_rewards:setClippingEnabled(true)
ListView_rewards:setBackGroundColorOpacity(109)
ListView_rewards:setLayoutComponentEnabled(true)
ListView_rewards:setName("ListView_rewards")
ListView_rewards:setTag(57)
ListView_rewards:setCascadeColorEnabled(true)
ListView_rewards:setCascadeOpacityEnabled(true)
ListView_rewards:setAnchorPoint(0.5000, 0.0000)
ListView_rewards:setPosition(129.0000, 162.7659)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_rewards)
layout:setSize({width = 245.0000, height = 68.0000})
layout:setLeftMargin(6.5000)
layout:setRightMargin(-251.5000)
layout:setTopMargin(-230.7659)
layout:setBottomMargin(162.7659)
Node:addChild(ListView_rewards)

--Create Node_title
local Node_title=cc.Node:create()
Node_title:setName("Node_title")
Node_title:setTag(58)
Node_title:setCascadeColorEnabled(true)
Node_title:setCascadeOpacityEnabled(true)
Node_title:setPosition(129.0000, 130.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_title)
layout:setLeftMargin(129.0000)
layout:setRightMargin(-129.0000)
layout:setTopMargin(-130.0000)
layout:setBottomMargin(130.0000)
Node:addChild(Node_title)

--Create Image_get
local Image_get = ccui.ImageView:create()
Image_get:ignoreContentAdaptWithSize(false)
Image_get:loadTexture("res/private/box_996_ui/hz_anniu.png",0)
Image_get:setLayoutComponentEnabled(true)
Image_get:setName("Image_get")
Image_get:setTag(59)
Image_get:setCascadeColorEnabled(true)
Image_get:setCascadeOpacityEnabled(true)
Image_get:setPosition(129.0000, 61.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_get)
layout:setSize({width = 174.0000, height = 54.0000})
layout:setLeftMargin(42.0000)
layout:setRightMargin(-216.0000)
layout:setTopMargin(-88.0000)
layout:setBottomMargin(34.0000)
Node:addChild(Image_get)

--Create Button_get
local Button_get = ccui.Button:create()
Button_get:ignoreContentAdaptWithSize(false)
Button_get:loadTextureNormal("res/private/box_996_ui/hz_ylq0.png",0)
Button_get:loadTexturePressed("res/private/box_996_ui/hz_ylq1.png",0)
Button_get:setTitleFontSize(14)
Button_get:setTitleColor({r = 65, g = 65, b = 70})
Button_get:setScale9Enabled(true)
Button_get:setCapInsets({x = 15, y = 4, width = 68, height = 24})
Button_get:setLayoutComponentEnabled(true)
Button_get:setName("Button_get")
Button_get:setTag(60)
Button_get:setCascadeColorEnabled(true)
Button_get:setCascadeOpacityEnabled(true)
Button_get:setPosition(87.0000, 27.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_get)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5632)
layout:setPercentHeight(0.5926)
layout:setSize({width = 98.0000, height = 32.0000})
layout:setLeftMargin(38.0000)
layout:setRightMargin(38.0000)
layout:setTopMargin(11.0000)
layout:setBottomMargin(11.0000)
Image_get:addChild(Button_get)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

