--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
Image_bg:loadTexture("res/private/box_996_ui/hz_chd.png",0)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(29)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(131.0000, 261.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setSize({width = 223.0000, height = 40.0000})
layout:setLeftMargin(19.5000)
layout:setRightMargin(-242.5000)
layout:setTopMargin(-281.0000)
layout:setBottomMargin(241.0000)
Node:addChild(Image_bg)

--Create Text_state_1
local Text_state_1 = ccui.Text:create()
Text_state_1:ignoreContentAdaptWithSize(true)
Text_state_1:setTextAreaSize({width = 0, height = 0})
Text_state_1:setFontName("fonts/font2.ttf")
Text_state_1:setFontSize(16)
Text_state_1:setString([[当前状态：]])
Text_state_1:setLayoutComponentEnabled(true)
Text_state_1:setName("Text_state_1")
Text_state_1:setTag(30)
Text_state_1:setCascadeColorEnabled(true)
Text_state_1:setCascadeOpacityEnabled(true)
Text_state_1:setPosition(90.0000, 220.0000)
Text_state_1.UserData = {}
Text_state_1.UserData[1] = [==========[1006]==========]
layout = ccui.LayoutComponent:bindLayoutComponent(Text_state_1)
layout:setSize({width = 76.0000, height = 21.0000})
layout:setLeftMargin(52.0000)
layout:setRightMargin(-128.0000)
layout:setTopMargin(-230.5000)
layout:setBottomMargin(209.5000)
Node:addChild(Text_state_1)

--Create Text_state
local Text_state = ccui.Text:create()
Text_state:ignoreContentAdaptWithSize(true)
Text_state:setTextAreaSize({width = 0, height = 0})
Text_state:setFontName("fonts/font2.ttf")
Text_state:setFontSize(16)
Text_state:setString([[称号未激活]])
Text_state:setLayoutComponentEnabled(true)
Text_state:setName("Text_state")
Text_state:setTag(31)
Text_state:setCascadeColorEnabled(true)
Text_state:setCascadeOpacityEnabled(true)
Text_state:setPosition(174.0000, 220.0000)
Text_state:setTextColor({r = 255, g = 5, b = 0})
Text_state.UserData = {}
Text_state.UserData[1] = [==========[1006]==========]
layout = ccui.LayoutComponent:bindLayoutComponent(Text_state)
layout:setSize({width = 83.0000, height = 21.0000})
layout:setLeftMargin(132.5000)
layout:setRightMargin(-215.5000)
layout:setTopMargin(-230.5000)
layout:setBottomMargin(209.5000)
Node:addChild(Text_state)

--Create Image_attr_bg
local Image_attr_bg = ccui.ImageView:create()
Image_attr_bg:ignoreContentAdaptWithSize(false)
Image_attr_bg:loadTexture("res/private/box_996_ui/hz_wzd.png",0)
Image_attr_bg:setLayoutComponentEnabled(true)
Image_attr_bg:setName("Image_attr_bg")
Image_attr_bg:setTag(32)
Image_attr_bg:setCascadeColorEnabled(true)
Image_attr_bg:setCascadeOpacityEnabled(true)
Image_attr_bg:setPosition(131.0000, 144.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_attr_bg)
layout:setSize({width = 294.0000, height = 123.0000})
layout:setLeftMargin(-16.0000)
layout:setRightMargin(-278.0000)
layout:setTopMargin(-205.5000)
layout:setBottomMargin(82.5000)
Node:addChild(Image_attr_bg)

--Create ListView_attr
local ListView_attr = ccui.ListView:create()
ListView_attr:setDirection(1)
ListView_attr:setGravity(0)
ListView_attr:ignoreContentAdaptWithSize(false)
ListView_attr:setClippingEnabled(true)
ListView_attr:setBackGroundColorOpacity(102)
ListView_attr:setLayoutComponentEnabled(true)
ListView_attr:setName("ListView_attr")
ListView_attr:setTag(33)
ListView_attr:setCascadeColorEnabled(true)
ListView_attr:setCascadeOpacityEnabled(true)
ListView_attr:setPosition(-10.0000, 88.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_attr)
layout:setSize({width = 282.0000, height = 111.0000})
layout:setLeftMargin(-10.0000)
layout:setRightMargin(-272.0000)
layout:setTopMargin(-199.5000)
layout:setBottomMargin(88.5000)
Node:addChild(ListView_attr)

--Create Node_title
local Node_title=cc.Node:create()
Node_title:setName("Node_title")
Node_title:setTag(34)
Node_title:setCascadeColorEnabled(true)
Node_title:setCascadeOpacityEnabled(true)
Node_title:setPosition(131.0000, 73.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_title)
layout:setLeftMargin(131.0000)
layout:setRightMargin(-131.0000)
layout:setTopMargin(-73.0000)
layout:setBottomMargin(73.0000)
Node:addChild(Node_title)

--Create Button_yc_s
local Button_yc_s = ccui.Button:create()
Button_yc_s:ignoreContentAdaptWithSize(false)
Button_yc_s:loadTextureNormal("res/private/box_996_ui/hz_yczjch.png",0)
Button_yc_s:loadTexturePressed("res/private/box_996_ui/hz_yczjch.png",0)
Button_yc_s:setTitleFontSize(14)
Button_yc_s:setTitleColor({r = 65, g = 65, b = 70})
Button_yc_s:setScale9Enabled(true)
Button_yc_s:setCapInsets({x = 15, y = 4, width = 143, height = 46})
Button_yc_s:setLayoutComponentEnabled(true)
Button_yc_s:setName("Button_yc_s")
Button_yc_s:setTag(36)
Button_yc_s:setCascadeColorEnabled(true)
Button_yc_s:setCascadeOpacityEnabled(true)
Button_yc_s:setVisible(false)
Button_yc_s:setPosition(27.9000, 36.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_yc_s)
layout:setSize({width = 173.0000, height = 54.0000})
layout:setLeftMargin(-58.6000)
layout:setRightMargin(-114.4000)
layout:setTopMargin(-63.0000)
layout:setBottomMargin(9.0000)
Node:addChild(Button_yc_s)

--Create Button_yc_o
local Button_yc_o = ccui.Button:create()
Button_yc_o:ignoreContentAdaptWithSize(false)
Button_yc_o:loadTextureNormal("res/private/box_996_ui/hz_yctrch.png",0)
Button_yc_o:loadTexturePressed("res/private/box_996_ui/hz_yctrch.png",0)
Button_yc_o:setTitleFontSize(14)
Button_yc_o:setTitleColor({r = 65, g = 65, b = 70})
Button_yc_o:setScale9Enabled(true)
Button_yc_o:setCapInsets({x = 15, y = 4, width = 143, height = 46})
Button_yc_o:setLayoutComponentEnabled(true)
Button_yc_o:setName("Button_yc_o")
Button_yc_o:setTag(38)
Button_yc_o:setCascadeColorEnabled(true)
Button_yc_o:setCascadeOpacityEnabled(true)
Button_yc_o:setVisible(false)
Button_yc_o:setPosition(237.0000, 36.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_yc_o)
layout:setSize({width = 173.0000, height = 54.0000})
layout:setLeftMargin(150.5000)
layout:setRightMargin(-323.5000)
layout:setTopMargin(-63.0000)
layout:setBottomMargin(9.0000)
Node:addChild(Button_yc_o)

--Create Image_download
local Image_download = ccui.ImageView:create()
Image_download:ignoreContentAdaptWithSize(false)
Image_download:loadTexture("res/private/box_996_ui/hz_anniu.png",0)
Image_download:setLayoutComponentEnabled(true)
Image_download:setName("Image_download")
Image_download:setTag(82)
Image_download:setCascadeColorEnabled(true)
Image_download:setCascadeOpacityEnabled(true)
Image_download:setVisible(false)
Image_download:setPosition(132.9000, 36.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_download)
layout:setSize({width = 174.0000, height = 54.0000})
layout:setLeftMargin(45.9000)
layout:setRightMargin(-219.9000)
layout:setTopMargin(-63.0000)
layout:setBottomMargin(9.0000)
Node:addChild(Image_download)

--Create Button_download
local Button_download = ccui.Button:create()
Button_download:ignoreContentAdaptWithSize(false)
Button_download:loadTextureNormal("res/private/box_996_ui/hz_xzhz0.png",0)
Button_download:loadTexturePressed("res/private/box_996_ui/hz_xzhz1.png",0)
Button_download:setTitleFontSize(14)
Button_download:setTitleColor({r = 65, g = 65, b = 70})
Button_download:setScale9Enabled(true)
Button_download:setCapInsets({x = 15, y = 4, width = 68, height = 25})
Button_download:setLayoutComponentEnabled(true)
Button_download:setName("Button_download")
Button_download:setTag(83)
Button_download:setCascadeColorEnabled(true)
Button_download:setCascadeOpacityEnabled(true)
Button_download:setPosition(87.0000, 27.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_download)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5632)
layout:setPercentHeight(0.6111)
layout:setSize({width = 98.0000, height = 33.0000})
layout:setLeftMargin(38.0000)
layout:setRightMargin(38.0000)
layout:setTopMargin(10.5000)
layout:setBottomMargin(10.5000)
Image_download:addChild(Button_download)

--Create Node_tx
local Node_tx=cc.Node:create()
Node_tx:setName("Node_tx")
Node_tx:setTag(28)
Node_tx:setCascadeColorEnabled(true)
Node_tx:setCascadeOpacityEnabled(true)
Node_tx:setPosition(131.0000, 249.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_tx)
layout:setLeftMargin(131.0000)
layout:setRightMargin(-131.0000)
layout:setTopMargin(-249.0000)
layout:setBottomMargin(249.0000)
Node:addChild(Node_tx)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

