--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create ListView_rewards
local ListView_rewards = ccui.ListView:create()
ListView_rewards:setDirection(2)
ListView_rewards:setGravity(3)
ListView_rewards:ignoreContentAdaptWithSize(false)
ListView_rewards:setClippingEnabled(true)
ListView_rewards:setBackGroundColorOpacity(109)
ListView_rewards:setLayoutComponentEnabled(true)
ListView_rewards:setName("ListView_rewards")
ListView_rewards:setTag(76)
ListView_rewards:setCascadeColorEnabled(true)
ListView_rewards:setCascadeOpacityEnabled(true)
ListView_rewards:setAnchorPoint(0.5000, 0.0000)
ListView_rewards:setPosition(129.0000, 162.7659)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_rewards)
layout:setSize({width = 245.0000, height = 68.0000})
layout:setLeftMargin(6.5000)
layout:setRightMargin(-251.5000)
layout:setTopMargin(-230.7659)
layout:setBottomMargin(162.7659)
Node:addChild(ListView_rewards)

--Create Node_title
local Node_title=cc.Node:create()
Node_title:setName("Node_title")
Node_title:setTag(77)
Node_title:setCascadeColorEnabled(true)
Node_title:setCascadeOpacityEnabled(true)
Node_title:setPosition(129.0000, 130.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_title)
layout:setLeftMargin(129.0000)
layout:setRightMargin(-129.0000)
layout:setTopMargin(-130.0000)
layout:setBottomMargin(130.0000)
Node:addChild(Node_title)

--Create Image_bg_lbm
local Image_bg_lbm = ccui.ImageView:create()
Image_bg_lbm:ignoreContentAdaptWithSize(false)
Image_bg_lbm:loadTexture("res/private/box_996_ui/hz_srk.png",0)
Image_bg_lbm:setLayoutComponentEnabled(true)
Image_bg_lbm:setName("Image_bg_lbm")
Image_bg_lbm:setTag(78)
Image_bg_lbm:setCascadeColorEnabled(true)
Image_bg_lbm:setCascadeOpacityEnabled(true)
Image_bg_lbm:setPosition(108.0000, 61.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg_lbm)
layout:setSize({width = 232.0000, height = 46.0000})
layout:setLeftMargin(-8.0000)
layout:setRightMargin(-224.0000)
layout:setTopMargin(-84.0000)
layout:setBottomMargin(38.0000)
Node:addChild(Image_bg_lbm)

--Create TextField_lbm
local TextField_lbm = ccui.TextField:create()
TextField_lbm:ignoreContentAdaptWithSize(false)
tolua.cast(TextField_lbm:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
TextField_lbm:setFontName("fonts/font2.ttf")
TextField_lbm:setFontSize(16)
TextField_lbm:setPlaceHolder("请输入礼包码")
TextField_lbm:setString([[]])
TextField_lbm:setMaxLength(10)
TextField_lbm:setLayoutComponentEnabled(true)
TextField_lbm:setName("TextField_lbm")
TextField_lbm:setTag(79)
TextField_lbm:setCascadeColorEnabled(true)
TextField_lbm:setCascadeOpacityEnabled(true)
TextField_lbm:setPosition(108.0000, 61.0000)
TextField_lbm.UserData = {}
TextField_lbm.UserData[1] = [==========[1006]==========]
layout = ccui.LayoutComponent:bindLayoutComponent(TextField_lbm)
layout:setSize({width = 221.0000, height = 35.0000})
layout:setLeftMargin(-2.5000)
layout:setRightMargin(-218.5000)
layout:setTopMargin(-78.5000)
layout:setBottomMargin(43.5000)
Node:addChild(TextField_lbm)

--Create Image_lbm_get
local Image_lbm_get = ccui.ImageView:create()
Image_lbm_get:ignoreContentAdaptWithSize(false)
Image_lbm_get:loadTexture("res/private/box_996_ui/hz_anniu.png",0)
Image_lbm_get:setLayoutComponentEnabled(true)
Image_lbm_get:setName("Image_lbm_get")
Image_lbm_get:setTag(80)
Image_lbm_get:setCascadeColorEnabled(true)
Image_lbm_get:setCascadeOpacityEnabled(true)
Image_lbm_get:setPosition(326.0000, 61.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_lbm_get)
layout:setSize({width = 174.0000, height = 54.0000})
layout:setLeftMargin(239.0000)
layout:setRightMargin(-413.0000)
layout:setTopMargin(-88.0000)
layout:setBottomMargin(34.0000)
Node:addChild(Image_lbm_get)

--Create Button_lbm_get
local Button_lbm_get = ccui.Button:create()
Button_lbm_get:ignoreContentAdaptWithSize(false)
Button_lbm_get:loadTextureNormal("res/private/box_996_ui/hz_lqhz0.png",0)
Button_lbm_get:loadTexturePressed("res/private/box_996_ui/hz_lqhz1.png",0)
Button_lbm_get:setTitleFontSize(14)
Button_lbm_get:setTitleColor({r = 65, g = 65, b = 70})
Button_lbm_get:setScale9Enabled(true)
Button_lbm_get:setCapInsets({x = 15, y = 4, width = 69, height = 24})
Button_lbm_get:setLayoutComponentEnabled(true)
Button_lbm_get:setName("Button_lbm_get")
Button_lbm_get:setTag(81)
Button_lbm_get:setCascadeColorEnabled(true)
Button_lbm_get:setCascadeOpacityEnabled(true)
Button_lbm_get:setPosition(87.0000, 27.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_lbm_get)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5690)
layout:setPercentHeight(0.5926)
layout:setSize({width = 99.0000, height = 32.0000})
layout:setLeftMargin(37.5000)
layout:setRightMargin(37.5000)
layout:setTopMargin(11.0000)
layout:setBottomMargin(11.0000)
Image_lbm_get:addChild(Button_lbm_get)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

