--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Layer
local Layer=cc.Node:create()
Layer:setName("Layer")
layout = ccui.LayoutComponent:bindLayoutComponent(Layer)
layout:setSize({width = 1136.0000, height = 640.0000})

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(101)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1136.0000, height = 640.0000})
Layer:addChild(Panel_1)

--Create Panel_touch
local Panel_touch = ccui.Layout:create()
Panel_touch:ignoreContentAdaptWithSize(false)
Panel_touch:setClippingEnabled(false)
Panel_touch:setBackGroundColorOpacity(102)
Panel_touch:setTouchEnabled(true);
Panel_touch:setLayoutComponentEnabled(true)
Panel_touch:setName("Panel_touch")
Panel_touch:setTag(22)
Panel_touch:setCascadeColorEnabled(true)
Panel_touch:setCascadeOpacityEnabled(true)
Panel_touch:setAnchorPoint(0.5000, 0.5000)
Panel_touch:setPosition(568.0000, 320.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_touch)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1136.0000, height = 640.0000})
Panel_1:addChild(Panel_touch)

--Create Panel_guide
local Panel_guide = ccui.Layout:create()
Panel_guide:ignoreContentAdaptWithSize(false)
Panel_guide:setClippingEnabled(false)
Panel_guide:setBackGroundColorOpacity(102)
Panel_guide:setTouchEnabled(true);
Panel_guide:setLayoutComponentEnabled(true)
Panel_guide:setName("Panel_guide")
Panel_guide:setTag(102)
Panel_guide:setCascadeColorEnabled(true)
Panel_guide:setCascadeOpacityEnabled(true)
Panel_guide:setAnchorPoint(0.5000, 0.5000)
Panel_guide:setPosition(568.0000, 320.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_guide)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5986)
layout:setPercentHeight(0.6250)
layout:setSize({width = 680.0000, height = 400.0000})
layout:setLeftMargin(228.0000)
layout:setRightMargin(228.0000)
layout:setTopMargin(120.0000)
layout:setBottomMargin(120.0000)
Panel_1:addChild(Panel_guide)

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
Image_bg:loadTexture("res/public/1900000675.jpg",0)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(103)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(340.0000, 200.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 680.0000, height = 400.0000})
Panel_guide:addChild(Image_bg)

--Create ListView_list
local ListView_list = ccui.ListView:create()
ListView_list:setItemsMargin(8)
ListView_list:setDirection(2)
ListView_list:setGravity(3)
ListView_list:ignoreContentAdaptWithSize(false)
ListView_list:setClippingEnabled(true)
ListView_list:setBackGroundColorOpacity(102)
ListView_list:setLayoutComponentEnabled(true)
ListView_list:setName("ListView_list")
ListView_list:setTag(35)
ListView_list:setCascadeColorEnabled(true)
ListView_list:setCascadeOpacityEnabled(true)
ListView_list:setAnchorPoint(0.5000, 0.5000)
ListView_list:setPosition(340.0000, 230.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_list)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5750)
layout:setPercentWidth(0.9103)
layout:setPercentHeight(0.8125)
layout:setSize({width = 619.0000, height = 325.0000})
layout:setLeftMargin(30.5000)
layout:setRightMargin(30.5000)
layout:setTopMargin(7.5000)
layout:setBottomMargin(67.5000)
Panel_guide:addChild(ListView_list)

--Create Image_download
local Image_download = ccui.ImageView:create()
Image_download:ignoreContentAdaptWithSize(false)
Image_download:loadTexture("res/private/box_996_ui/hz_anniu.png",0)
Image_download:setLayoutComponentEnabled(true)
Image_download:setName("Image_download")
Image_download:setTag(33)
Image_download:setCascadeColorEnabled(true)
Image_download:setCascadeOpacityEnabled(true)
Image_download:setVisible(false)
Image_download:setPosition(340.0000, 38.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_download)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.0950)
layout:setPercentWidth(0.2559)
layout:setPercentHeight(0.1400)
layout:setSize({width = 174.0000, height = 56.0000})
layout:setLeftMargin(253.0000)
layout:setRightMargin(253.0000)
layout:setTopMargin(334.0000)
layout:setBottomMargin(10.0000)
Panel_guide:addChild(Image_download)

--Create Button_download
local Button_download = ccui.Button:create()
Button_download:ignoreContentAdaptWithSize(false)
Button_download:loadTextureNormal("res/private/box_996_ui/hz_xzhz0.png",0)
Button_download:loadTexturePressed("res/private/box_996_ui/hz_xzhz1.png",0)
Button_download:setTitleFontSize(14)
Button_download:setTitleColor({r = 65, g = 65, b = 70})
Button_download:setScale9Enabled(true)
Button_download:setCapInsets({x = 15, y = 4, width = 68, height = 25})
Button_download:setLayoutComponentEnabled(true)
Button_download:setName("Button_download")
Button_download:setTag(34)
Button_download:setCascadeColorEnabled(true)
Button_download:setCascadeOpacityEnabled(true)
Button_download:setPosition(87.0000, 28.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_download)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5632)
layout:setPercentHeight(0.5893)
layout:setSize({width = 98.0000, height = 33.0000})
layout:setLeftMargin(38.0000)
layout:setRightMargin(38.0000)
layout:setTopMargin(11.5000)
layout:setBottomMargin(11.5000)
Image_download:addChild(Button_download)

--Create Button_close
local Button_close = ccui.Button:create()
Button_close:ignoreContentAdaptWithSize(false)
Button_close:loadTextureNormal("res/private/box_996_ui/hz_gb.png",0)
Button_close:setTitleFontSize(14)
Button_close:setTitleColor({r = 65, g = 65, b = 70})
Button_close:setScale9Enabled(true)
Button_close:setCapInsets({x = 8, y = 11, width = 10, height = 20})
Button_close:setLayoutComponentEnabled(true)
Button_close:setName("Button_close")
Button_close:setTag(23)
Button_close:setCascadeColorEnabled(true)
Button_close:setCascadeOpacityEnabled(true)
Button_close:setPosition(920.9998, 501.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_close)
layout:setPositionPercentX(0.8107)
layout:setPositionPercentY(0.7828)
layout:setPercentWidth(0.0229)
layout:setPercentHeight(0.0656)
layout:setSize({width = 26.0000, height = 42.0000})
layout:setLeftMargin(907.9998)
layout:setRightMargin(202.0002)
layout:setTopMargin(118.0000)
layout:setBottomMargin(480.0000)
Panel_1:addChild(Button_close)

--Create Panel_custom
local Panel_custom = ccui.Layout:create()
Panel_custom:ignoreContentAdaptWithSize(false)
Panel_custom:setClippingEnabled(false)
Panel_custom:setBackGroundColorOpacity(102)
Panel_custom:setLayoutComponentEnabled(true)
Panel_custom:setName("Panel_custom")
Panel_custom:setTag(36)
Panel_custom:setCascadeColorEnabled(true)
Panel_custom:setCascadeOpacityEnabled(true)
Panel_custom:setVisible(false)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_custom)
layout:setPercentWidth(0.1761)
layout:setPercentHeight(0.3125)
layout:setSize({width = 200.0000, height = 200.0000})
layout:setRightMargin(936.0000)
layout:setTopMargin(440.0000)
Panel_1:addChild(Panel_custom)

--Create Panel_item
local Panel_item = ccui.Layout:create()
Panel_item:ignoreContentAdaptWithSize(false)
Panel_item:setClippingEnabled(false)
Panel_item:setBackGroundColorOpacity(102)
Panel_item:setTouchEnabled(true);
Panel_item:setLayoutComponentEnabled(true)
Panel_item:setName("Panel_item")
Panel_item:setTag(37)
Panel_item:setCascadeColorEnabled(true)
Panel_item:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_item)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.6250)
layout:setSize({width = 200.0000, height = 325.0000})
layout:setTopMargin(-125.0000)
Panel_custom:addChild(Panel_item)

--Create Image_item_bg
local Image_item_bg = ccui.ImageView:create()
Image_item_bg:ignoreContentAdaptWithSize(false)
Image_item_bg:loadTexture("Default/ImageFile.png",0)
Image_item_bg:setLayoutComponentEnabled(true)
Image_item_bg:setName("Image_item_bg")
Image_item_bg:setTag(38)
Image_item_bg:setCascadeColorEnabled(true)
Image_item_bg:setCascadeOpacityEnabled(true)
Image_item_bg:setPosition(100.0000, 162.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_item_bg)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.2300)
layout:setPercentHeight(0.1415)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setLeftMargin(77.0000)
layout:setRightMargin(77.0000)
layout:setTopMargin(139.5000)
layout:setBottomMargin(139.5000)
Panel_item:addChild(Image_item_bg)

--Create Text_title
local Text_title = ccui.Text:create()
Text_title:ignoreContentAdaptWithSize(true)
Text_title:setTextAreaSize({width = 0, height = 0})
Text_title:setFontName("fonts/font2.ttf")
Text_title:setFontSize(20)
Text_title:setString([[]])
Text_title:setTextHorizontalAlignment(1)
Text_title:setLayoutComponentEnabled(true)
Text_title:setName("Text_title")
Text_title:setTag(23)
Text_title:setCascadeColorEnabled(true)
Text_title:setCascadeOpacityEnabled(true)
Text_title:setAnchorPoint(0.5000, 0.0000)
Text_title:setPosition(100.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_title)
layout:setPositionPercentX(0.5000)
layout:setLeftMargin(100.0000)
layout:setRightMargin(100.0000)
layout:setTopMargin(325.0000)
Panel_item:addChild(Text_title)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Layer
return result;
end

return Result

