--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create ui_BmpText
local ui_BmpText = ccui.Layout:create()
ui_BmpText:ignoreContentAdaptWithSize(false)
ui_BmpText:setClippingEnabled(false)
ui_BmpText:setBackGroundColorOpacity(102)
ui_BmpText:setTouchEnabled(true);
ui_BmpText:setLayoutComponentEnabled(true)
ui_BmpText:setName("ui_BmpText")
ui_BmpText:setTag(2708)
ui_BmpText:setCascadeColorEnabled(true)
ui_BmpText:setCascadeOpacityEnabled(true)
ui_BmpText:setAnchorPoint(0.0000, 1.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ui_BmpText)
layout:setSize({width = 300.0000, height = 128.0000})
layout:setRightMargin(-300.0000)
layout:setBottomMargin(-128.0000)
Node:addChild(ui_BmpText)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontSize(12)
Text_name:setString([[文本]])
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(2709)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setAnchorPoint(1.0000, 0.5000)
Text_name:setPosition(65.0005, 111.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentX(0.2167)
layout:setPositionPercentY(0.8750)
layout:setPercentWidth(0.0800)
layout:setPercentHeight(0.0938)
layout:setSize({width = 24.0000, height = 12.0000})
layout:setLeftMargin(41.0005)
layout:setRightMargin(234.9995)
layout:setTopMargin(10.0001)
layout:setBottomMargin(105.9999)
ui_BmpText:addChild(Text_name)

--Create bg1
local bg1 = ccui.Layout:create()
bg1:ignoreContentAdaptWithSize(false)
bg1:setClippingEnabled(false)
bg1:setBackGroundColorType(1)
bg1:setBackGroundColor({r = 0, g = 0, b = 0})
bg1:setTouchEnabled(true);
bg1:setLayoutComponentEnabled(true)
bg1:setName("bg1")
bg1:setTag(2710)
bg1:setCascadeColorEnabled(true)
bg1:setCascadeOpacityEnabled(true)
bg1:setAnchorPoint(0.0000, 1.0000)
bg1:setPosition(69.9999, 122.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(bg1)
layout:setPositionPercentX(0.2333)
layout:setPositionPercentY(0.9609)
layout:setPercentWidth(0.7500)
layout:setPercentHeight(0.7422)
layout:setSize({width = 225.0000, height = 95.0000})
layout:setLeftMargin(69.9999)
layout:setRightMargin(5.0001)
layout:setTopMargin(5.0001)
layout:setBottomMargin(27.9999)
ui_BmpText:addChild(bg1)

--Create TextField_More_Text
local TextField_More_Text = ccui.TextField:create()
TextField_More_Text:ignoreContentAdaptWithSize(false)
tolua.cast(TextField_More_Text:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
TextField_More_Text:setFontName("fonts/font.ttf")
TextField_More_Text:setFontSize(14)
TextField_More_Text:setPlaceHolder("")
TextField_More_Text:setString([[文本]])
TextField_More_Text:setMaxLength(10)
TextField_More_Text:setLayoutComponentEnabled(true)
TextField_More_Text:setName("TextField_More_Text")
TextField_More_Text:setTag(2711)
TextField_More_Text:setCascadeColorEnabled(true)
TextField_More_Text:setCascadeOpacityEnabled(true)
TextField_More_Text:setAnchorPoint(0.0000, 1.0000)
TextField_More_Text:setPosition(71.0000, 121.9999)
layout = ccui.LayoutComponent:bindLayoutComponent(TextField_More_Text)
layout:setPositionPercentX(0.2367)
layout:setPositionPercentY(0.9531)
layout:setPercentWidth(0.7433)
layout:setPercentHeight(0.7266)
layout:setSize({width = 223.0000, height = 93.0000})
layout:setLeftMargin(71.0000)
layout:setRightMargin(6.0000)
layout:setTopMargin(6.0001)
layout:setBottomMargin(28.9999)
ui_BmpText:addChild(TextField_More_Text)

--Create a1
local a1 = ccui.Layout:create()
a1:ignoreContentAdaptWithSize(false)
a1:setClippingEnabled(false)
a1:setBackGroundColorOpacity(102)
a1:setLayoutComponentEnabled(true)
a1:setName("a1")
a1:setTag(2712)
a1:setCascadeColorEnabled(true)
a1:setCascadeOpacityEnabled(true)
a1:setAnchorPoint(0.0000, 1.0000)
a1:setPosition(0.0000, 24.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(a1)
layout:setPositionPercentY(0.1875)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.1563)
layout:setSize({width = 300.0000, height = 20.0000})
layout:setTopMargin(104.0000)
layout:setBottomMargin(4.0000)
ui_BmpText:addChild(a1)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontSize(12)
Text_name:setString([[文本颜色]])
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(2713)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setAnchorPoint(1.0000, 0.5000)
Text_name:setPosition(65.0000, 10.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2167)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1600)
layout:setPercentHeight(0.6000)
layout:setSize({width = 48.0000, height = 12.0000})
layout:setLeftMargin(17.0000)
layout:setRightMargin(235.0000)
layout:setTopMargin(4.0000)
layout:setBottomMargin(4.0000)
a1:addChild(Text_name)

--Create bg1
local bg1 = ccui.Layout:create()
bg1:ignoreContentAdaptWithSize(false)
bg1:setClippingEnabled(false)
bg1:setBackGroundColorType(1)
bg1:setBackGroundColor({r = 0, g = 0, b = 0})
bg1:setTouchEnabled(true);
bg1:setLayoutComponentEnabled(true)
bg1:setName("bg1")
bg1:setTag(2714)
bg1:setCascadeColorEnabled(true)
bg1:setCascadeOpacityEnabled(true)
bg1:setAnchorPoint(0.0000, 0.5000)
bg1:setPosition(70.0000, 10.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg1)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2333)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6733)
layout:setPercentHeight(1.0000)
layout:setSize({width = 202.0000, height = 20.0000})
layout:setLeftMargin(70.0000)
layout:setRightMargin(28.0000)
a1:addChild(bg1)

--Create Button_Color
local Button_Color = ccui.Button:create()
Button_Color:ignoreContentAdaptWithSize(false)
Button_Color:loadTextureNormal("Default/Button_Normal.png",0)
Button_Color:loadTextureDisabled("Default/Button_Disable.png",0)
Button_Color:setTitleFontSize(14)
Button_Color:setTitleColor({r = 65, g = 65, b = 70})
Button_Color:setScale9Enabled(true)
Button_Color:setCapInsets({x = 15, y = 11, width = 16, height = 14})
Button_Color:setLayoutComponentEnabled(true)
Button_Color:setName("Button_Color")
Button_Color:setTag(393)
Button_Color:setCascadeColorEnabled(true)
Button_Color:setCascadeOpacityEnabled(true)
Button_Color:setAnchorPoint(0.0000, 0.0000)
Button_Color:setPosition(275.5000, 2.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_Color)
layout:setPositionPercentX(0.9183)
layout:setPositionPercentY(0.1000)
layout:setPercentWidth(0.0600)
layout:setPercentHeight(0.8000)
layout:setSize({width = 18.0000, height = 16.0000})
layout:setLeftMargin(275.5000)
layout:setRightMargin(6.5000)
layout:setTopMargin(2.0000)
layout:setBottomMargin(2.0000)
a1:addChild(Button_Color)

--Create Panel_Preview
local Panel_Preview = ccui.Layout:create()
Panel_Preview:ignoreContentAdaptWithSize(false)
Panel_Preview:setClippingEnabled(false)
Panel_Preview:setBackGroundColorType(1)
Panel_Preview:setBackGroundColor({r = 255, g = 0, b = 0})
Panel_Preview:setLayoutComponentEnabled(true)
Panel_Preview:setName("Panel_Preview")
Panel_Preview:setTag(391)
Panel_Preview:setCascadeColorEnabled(true)
Panel_Preview:setCascadeOpacityEnabled(true)
Panel_Preview:setPosition(277.5000, 4.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_Preview)
layout:setPositionPercentX(0.9250)
layout:setPositionPercentY(0.2000)
layout:setPercentWidth(0.0467)
layout:setPercentHeight(0.6000)
layout:setSize({width = 14.0000, height = 12.0000})
layout:setLeftMargin(277.5000)
layout:setRightMargin(8.5000)
layout:setTopMargin(4.0000)
layout:setBottomMargin(4.0000)
a1:addChild(Panel_Preview)

--Create Image_9_0
local Image_9_0 = ccui.ImageView:create()
Image_9_0:ignoreContentAdaptWithSize(false)
Image_9_0:loadTexture("res/public/1900000654.png",0)
Image_9_0:setScale9Enabled(true)
Image_9_0:setCapInsets({x = 5, y = 6, width = 7, height = 7})
Image_9_0:setLayoutComponentEnabled(true)
Image_9_0:setName("Image_9_0")
Image_9_0:setTag(390)
Image_9_0:setCascadeColorEnabled(true)
Image_9_0:setCascadeOpacityEnabled(true)
Image_9_0:setAnchorPoint(0.0000, 0.0000)
Image_9_0:setPosition(273.5000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_9_0)
layout:setPositionPercentX(0.9117)
layout:setPercentWidth(0.0733)
layout:setPercentHeight(1.1000)
layout:setSize({width = 22.0000, height = 22.0000})
layout:setLeftMargin(273.5000)
layout:setRightMargin(4.5000)
layout:setTopMargin(-2.0000)
a1:addChild(Image_9_0)

--Create TextField_C
local TextField_C = ccui.TextField:create()
TextField_C:ignoreContentAdaptWithSize(false)
tolua.cast(TextField_C:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
TextField_C:setFontName("fonts/font.ttf")
TextField_C:setFontSize(14)
TextField_C:setPlaceHolder("")
TextField_C:setString([[0]])
TextField_C:setMaxLengthEnabled(true)
TextField_C:setMaxLength(7)
TextField_C:setLayoutComponentEnabled(true)
TextField_C:setName("TextField_C")
TextField_C:setTag(2717)
TextField_C:setCascadeColorEnabled(true)
TextField_C:setCascadeOpacityEnabled(true)
TextField_C:setAnchorPoint(0.0000, 0.5000)
TextField_C:setPosition(71.0000, 10.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TextField_C)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2367)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6667)
layout:setPercentHeight(0.9000)
layout:setSize({width = 200.0000, height = 18.0000})
layout:setLeftMargin(71.0000)
layout:setRightMargin(29.0000)
layout:setTopMargin(1.0000)
layout:setBottomMargin(1.0000)
a1:addChild(TextField_C)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

