--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Text_version
local Text_version = ccui.Text:create()
Text_version:ignoreContentAdaptWithSize(true)
Text_version:setTextAreaSize({width = 0, height = 0})
Text_version:setFontName("fonts/font2.ttf")
Text_version:setFontSize(18)
Text_version:setString([[Text Label]])
Text_version:setLayoutComponentEnabled(true)
Text_version:setName("Text_version")
Text_version:setTag(29)
Text_version:setCascadeColorEnabled(true)
Text_version:setCascadeOpacityEnabled(true)
Text_version:setAnchorPoint(0.0000, 1.0000)
Text_version:setPosition(25.0000, 635.0000)
Text_version:setTextColor({r = 255, g = 228, b = 199})
layout = ccui.LayoutComponent:bindLayoutComponent(Text_version)
layout:setPositionPercentX(0.0220)
layout:setPositionPercentY(0.9922)
layout:setPercentWidth(0.0757)
layout:setPercentHeight(0.0375)
layout:setSize({width = 86.0000, height = 24.0000})
layout:setHorizontalEdge(1)
layout:setVerticalEdge(2)
layout:setLeftMargin(25.0000)
layout:setRightMargin(1025.0000)
layout:setTopMargin(5.0000)
layout:setBottomMargin(611.0000)
Scene:addChild(Text_version)

--Create Node_permission
local Node_permission=cc.Node:create()
Node_permission:setName("Node_permission")
Node_permission:setTag(16)
Node_permission:setCascadeColorEnabled(true)
Node_permission:setCascadeOpacityEnabled(true)
Node_permission:setPosition(568.0000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_permission)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setLeftMargin(568.0000)
layout:setRightMargin(568.0000)
layout:setTopMargin(640.0000)
Scene:addChild(Node_permission)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

