--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Panel_touch
local Panel_touch = ccui.Layout:create()
Panel_touch:ignoreContentAdaptWithSize(false)
Panel_touch:setClippingEnabled(false)
Panel_touch:setBackGroundColorOpacity(102)
Panel_touch:setTouchEnabled(true);
Panel_touch:setLayoutComponentEnabled(true)
Panel_touch:setName("Panel_touch")
Panel_touch:setTag(28)
Panel_touch:setCascadeColorEnabled(true)
Panel_touch:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_touch)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1136.0000, height = 640.0000})
Scene:addChild(Panel_touch)

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(2)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
Panel_1:setAnchorPoint(0.5000, 0.5000)
Panel_1:setPosition(568.0000, 320.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1136.0000, height = 640.0000})
Scene:addChild(Panel_1)

--Create Image_bg
local Image_bg = ccui.ImageView:create()
Image_bg:ignoreContentAdaptWithSize(false)
Image_bg:loadTexture("Default/ImageFile.png",0)
Image_bg:setLayoutComponentEnabled(true)
Image_bg:setName("Image_bg")
Image_bg:setTag(42)
Image_bg:setCascadeColorEnabled(true)
Image_bg:setCascadeOpacityEnabled(true)
Image_bg:setPosition(568.0000, 320.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_bg)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.0405)
layout:setPercentHeight(0.0719)
layout:setSize({width = 46.0000, height = 46.0000})
layout:setLeftMargin(545.0000)
layout:setRightMargin(545.0000)
layout:setTopMargin(297.0000)
layout:setBottomMargin(297.0000)
Panel_1:addChild(Image_bg)

--Create Image_1
local Image_1 = ccui.ImageView:create()
Image_1:ignoreContentAdaptWithSize(false)
Image_1:loadTexture("res/public/1900000600.png",0)
Image_1:setLayoutComponentEnabled(true)
Image_1:setName("Image_1")
Image_1:setTag(41)
Image_1:setCascadeColorEnabled(true)
Image_1:setCascadeOpacityEnabled(true)
Image_1:setPosition(568.0000, 320.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_1)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.3979)
layout:setPercentHeight(0.2797)
layout:setSize({width = 452.0000, height = 179.0000})
layout:setLeftMargin(342.0000)
layout:setRightMargin(342.0000)
layout:setTopMargin(230.5000)
layout:setBottomMargin(230.5000)
Panel_1:addChild(Image_1)

--Create Image_edit
local Image_edit = ccui.ImageView:create()
Image_edit:ignoreContentAdaptWithSize(false)
Image_edit:loadTexture("res/public/1900000668.png",0)
Image_edit:setScale9Enabled(true)
Image_edit:setCapInsets({x = 46, y = 10, width = 64, height = 11})
Image_edit:setLayoutComponentEnabled(true)
Image_edit:setName("Image_edit")
Image_edit:setTag(29)
Image_edit:setCascadeColorEnabled(true)
Image_edit:setCascadeOpacityEnabled(true)
Image_edit:setPosition(226.0000, 90.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_edit)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5028)
layout:setPercentWidth(0.8407)
layout:setPercentHeight(0.1732)
layout:setSize({width = 380.0000, height = 31.0000})
layout:setLeftMargin(36.0000)
layout:setRightMargin(36.0000)
layout:setTopMargin(73.5000)
layout:setBottomMargin(74.5000)
Image_1:addChild(Image_edit)

--Create TextField
local TextField = ccui.TextField:create()
TextField:ignoreContentAdaptWithSize(false)
tolua.cast(TextField:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
TextField:setFontName("fonts/font.ttf")
TextField:setFontSize(18)
TextField:setPlaceHolder("")
TextField:setString([[]])
TextField:setMaxLength(10)
TextField:setLayoutComponentEnabled(true)
TextField:setName("TextField")
TextField:setTag(27)
TextField:setCascadeColorEnabled(true)
TextField:setCascadeOpacityEnabled(true)
TextField:setPosition(190.0000, 15.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(TextField)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.8065)
layout:setSize({width = 380.0000, height = 25.0000})
layout:setTopMargin(3.0000)
layout:setBottomMargin(3.0000)
Image_edit:addChild(TextField)

--Create Button_ok
local Button_ok = ccui.Button:create()
Button_ok:ignoreContentAdaptWithSize(false)
Button_ok:loadTextureNormal("res/public/1900001022.png",0)
Button_ok:loadTexturePressed("res/public/1900001023.png",0)
Button_ok:setTitleFontName("fonts/font.ttf")
Button_ok:setTitleFontSize(16)
Button_ok:setTitleText("确定")
Button_ok:setScale9Enabled(true)
Button_ok:setCapInsets({x = 15, y = 11, width = 46, height = 11})
Button_ok:setLayoutComponentEnabled(true)
Button_ok:setName("Button_ok")
Button_ok:setTag(47)
Button_ok:setCascadeColorEnabled(true)
Button_ok:setCascadeOpacityEnabled(true)
Button_ok:setPosition(390.0000, 40.0000)
Button_ok.UserData = {}
Button_ok.UserData[1] = [==========[1020]==========]
layout = ccui.LayoutComponent:bindLayoutComponent(Button_ok)
layout:setPositionPercentX(0.8628)
layout:setPositionPercentY(0.2235)
layout:setPercentWidth(0.1681)
layout:setPercentHeight(0.1844)
layout:setSize({width = 76.0000, height = 33.0000})
layout:setLeftMargin(352.0000)
layout:setRightMargin(24.0000)
layout:setTopMargin(122.5000)
layout:setBottomMargin(23.5000)
Image_1:addChild(Button_ok)

--Create TouchSize
local TouchSize = ccui.Layout:create()
TouchSize:ignoreContentAdaptWithSize(false)
TouchSize:setClippingEnabled(false)
TouchSize:setBackGroundColorType(1)
TouchSize:setBackGroundColor({r = 150, g = 200, b = 255})
TouchSize:setBackGroundColorOpacity(102)
TouchSize:setTouchEnabled(true);
TouchSize:setLayoutComponentEnabled(true)
TouchSize:setName("TouchSize")
TouchSize:setTag(48)
TouchSize:setCascadeColorEnabled(true)
TouchSize:setCascadeOpacityEnabled(true)
TouchSize:setAnchorPoint(0.5000, 0.5000)
TouchSize:setPosition(38.0000, 16.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(TouchSize)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.3000)
layout:setPercentHeight(1.6000)
layout:setSize({width = 98.8000, height = 52.8000})
layout:setLeftMargin(-11.4000)
layout:setRightMargin(-11.4000)
layout:setTopMargin(-9.9000)
layout:setBottomMargin(-9.9000)
Button_ok:addChild(TouchSize)

--Create Text_app
local Text_app = ccui.Text:create()
Text_app:ignoreContentAdaptWithSize(true)
Text_app:setTextAreaSize({width = 0, height = 0})
Text_app:setFontName("fonts/font.ttf")
Text_app:setFontSize(16)
Text_app:setString([[安全中心]])
Text_app:setTextHorizontalAlignment(2)
Text_app:setLayoutComponentEnabled(true)
Text_app:setName("Text_app")
Text_app:setTag(10)
Text_app:setCascadeColorEnabled(true)
Text_app:setCascadeOpacityEnabled(true)
Text_app:setAnchorPoint(1.0000, 0.5000)
Text_app:setPosition(328.0000, 40.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_app)
layout:setPositionPercentX(0.7257)
layout:setPositionPercentY(0.2235)
layout:setPercentWidth(0.1482)
layout:setPercentHeight(0.1173)
layout:setSize({width = 67.0000, height = 21.0000})
layout:setLeftMargin(261.0000)
layout:setRightMargin(124.0000)
layout:setTopMargin(128.5000)
layout:setBottomMargin(29.5000)
Image_1:addChild(Text_app)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

