--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(40)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setSize({width = 125.0000, height = 43.0000})
layout:setRightMargin(-125.0000)
layout:setTopMargin(-43.0000)
Node:addChild(Panel_1)

--Create Button_group
local Button_group = ccui.Button:create()
Button_group:ignoreContentAdaptWithSize(false)
Button_group:loadTextureNormal("res/private/server/announce/1900000662.png",0)
Button_group:loadTexturePressed("res/private/server/announce/1900000663.png",0)
Button_group:setTitleFontName("fonts/font.ttf")
Button_group:setTitleFontSize(18)
Button_group:setTitleText("游戏公告")
Button_group:setScale9Enabled(true)
Button_group:setCapInsets({x = 15, y = 11, width = 85, height = 15})
Button_group:setLayoutComponentEnabled(true)
Button_group:setName("Button_group")
Button_group:setTag(41)
Button_group:setCascadeColorEnabled(true)
Button_group:setCascadeOpacityEnabled(true)
Button_group:setAnchorPoint(0.5000, 0.0000)
Button_group:setPosition(62.5000, 0.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_group)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPercentWidth(0.9200)
layout:setPercentHeight(0.8605)
layout:setSize({width = 115.0000, height = 37.0000})
layout:setLeftMargin(5.0000)
layout:setRightMargin(5.0000)
layout:setTopMargin(6.0000)
Panel_1:addChild(Button_group)

--Create Image_trait
local Image_trait = ccui.ImageView:create()
Image_trait:ignoreContentAdaptWithSize(false)
Image_trait:loadTexture("res/private/server/announce/word_hefubq_01.png",0)
Image_trait:setLayoutComponentEnabled(true)
Image_trait:setName("Image_trait")
Image_trait:setTag(42)
Image_trait:setCascadeColorEnabled(true)
Image_trait:setCascadeOpacityEnabled(true)
Image_trait:setPosition(22.0001, 18.0001)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_trait)
layout:setPositionPercentX(0.1760)
layout:setPositionPercentY(0.4186)
layout:setPercentWidth(0.3200)
layout:setPercentHeight(0.9767)
layout:setSize({width = 40.0000, height = 42.0000})
layout:setLeftMargin(2.0001)
layout:setRightMargin(82.9999)
layout:setTopMargin(3.9999)
layout:setBottomMargin(-2.9999)
Panel_1:addChild(Image_trait)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

