--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_bg
local Panel_bg = ccui.Layout:create()
Panel_bg:ignoreContentAdaptWithSize(false)
Panel_bg:setClippingEnabled(false)
Panel_bg:setBackGroundColorOpacity(102)
Panel_bg:setTouchEnabled(true);
Panel_bg:setLayoutComponentEnabled(true)
Panel_bg:setName("Panel_bg")
Panel_bg:setTag(7)
Panel_bg:setCascadeColorEnabled(true)
Panel_bg:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_bg)
layout:setSize({width = 264.0000, height = 49.0000})
layout:setRightMargin(-264.0000)
layout:setTopMargin(-49.0000)
Node:addChild(Panel_bg)

--Create Button_server
local Button_server = ccui.Button:create()
Button_server:ignoreContentAdaptWithSize(false)
Button_server:loadTextureNormal("res/private/server/fuguchuanqi.apk_000853.png",0)
Button_server:setTitleFontName("fonts/font.ttf")
Button_server:setTitleFontSize(18)
Button_server:setTitleText("服务器名")
Button_server:setScale9Enabled(true)
Button_server:setCapInsets({x = 15, y = 11, width = 232, height = 31})
Button_server:setLayoutComponentEnabled(true)
Button_server:setName("Button_server")
Button_server:setTag(178)
Button_server:setCascadeColorEnabled(true)
Button_server:setCascadeOpacityEnabled(true)
Button_server:setPosition(132.0000, 24.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_server)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9924)
layout:setPercentHeight(1.0816)
layout:setSize({width = 262.0000, height = 53.0000})
layout:setLeftMargin(1.0000)
layout:setRightMargin(1.0000)
layout:setTopMargin(-2.0000)
layout:setBottomMargin(-2.0000)
Panel_bg:addChild(Button_server)

--Create Image_state
local Image_state = ccui.ImageView:create()
Image_state:ignoreContentAdaptWithSize(false)
Image_state:loadTexture("res/private/server/fuguchuanqi.apk_000873.png",0)
Image_state:setLayoutComponentEnabled(true)
Image_state:setName("Image_state")
Image_state:setTag(216)
Image_state:setCascadeColorEnabled(true)
Image_state:setCascadeOpacityEnabled(true)
Image_state:setPosition(26.1170, 25.2858)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_state)
layout:setPositionPercentX(0.0997)
layout:setPositionPercentY(0.4771)
layout:setPercentWidth(0.0763)
layout:setPercentHeight(0.3774)
layout:setSize({width = 20.0000, height = 20.0000})
layout:setLeftMargin(16.1170)
layout:setRightMargin(225.8830)
layout:setTopMargin(17.7142)
layout:setBottomMargin(15.2858)
Button_server:addChild(Image_state)

--Create Image_new
local Image_new = ccui.ImageView:create()
Image_new:ignoreContentAdaptWithSize(false)
Image_new:loadTexture("res/private/server/1900008055.png",0)
Image_new:setLayoutComponentEnabled(true)
Image_new:setName("Image_new")
Image_new:setTag(32)
Image_new:setCascadeColorEnabled(true)
Image_new:setCascadeOpacityEnabled(true)
Image_new:setPosition(239.8345, 31.4900)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_new)
layout:setPositionPercentX(0.9154)
layout:setPositionPercentY(0.5942)
layout:setPercentWidth(0.1145)
layout:setPercentHeight(0.5472)
layout:setSize({width = 30.0000, height = 29.0000})
layout:setLeftMargin(224.8345)
layout:setRightMargin(7.1655)
layout:setTopMargin(7.0100)
layout:setBottomMargin(16.9900)
Button_server:addChild(Image_new)

--Create Image_role
local Image_role = ccui.ImageView:create()
Image_role:ignoreContentAdaptWithSize(false)
Image_role:loadTexture("res/private/server/icon_fwqxz_02.png",0)
Image_role:setLayoutComponentEnabled(true)
Image_role:setName("Image_role")
Image_role:setTag(56)
Image_role:setCascadeColorEnabled(true)
Image_role:setCascadeOpacityEnabled(true)
Image_role:setPosition(235.0000, 26.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_role)
layout:setPositionPercentX(0.8969)
layout:setPositionPercentY(0.4906)
layout:setPercentWidth(0.0687)
layout:setPercentHeight(0.4151)
layout:setSize({width = 18.0000, height = 22.0000})
layout:setLeftMargin(226.0000)
layout:setRightMargin(18.0000)
layout:setTopMargin(16.0000)
layout:setBottomMargin(15.0000)
Button_server:addChild(Image_role)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

