local config = { 
	[1] = { 
		xls_id = 1,
		EnevtName = "混沌·蛮荒树妖统领",
		BGimg = "jm_26",
		Types = "召唤",
		Image = "hd01",
		Mob_MonName = "混沌·蛮荒树妖统领",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = 1,
	},
	[2] = { 
		xls_id = 2,
		EnevtName = "混沌·天元冰霜巨兽",
		BGimg = "jm_27",
		Types = "召唤",
		Image = "hd02",
		Mob_MonName = "混沌·天元冰霜巨兽",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = 1,
	},
	[3] = { 
		xls_id = 3,
		EnevtName = "混沌·神龙雷霆暴君",
		BGimg = "jm_28",
		Types = "召唤",
		Image = "hd03",
		Mob_MonName = "混沌·神龙雷霆暴君",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = 1,
	},
	[4] = { 
		xls_id = 4,
		EnevtName = "混沌·冥司酆都大帝",
		BGimg = "jm_29",
		Types = "召唤",
		Image = "hd04",
		Mob_MonName = "混沌·冥司酆都大帝",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = 1,
	},
	[5] = { 
		xls_id = 5,
		EnevtName = "混沌·极恶大地魔王",
		BGimg = "jm_30",
		Types = "召唤",
		Image = "hd05",
		Mob_MonName = "混沌·极恶大地魔王",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = 1,
	},
	[6] = { 
		xls_id = 6,
		EnevtName = "混沌·太阳神炎沙巨蝎",
		BGimg = "jm_31",
		Types = "召唤",
		Image = "hd06",
		Mob_MonName = "混沌·太阳神炎沙巨蝎",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = 1,
	},
	[7] = { 
		xls_id = 7,
		EnevtName = "混沌·破晓金刚·天妖傀",
		BGimg = "jm_32",
		Types = "召唤",
		Image = "hd07",
		Mob_MonName = "混沌·破晓金刚·天妖傀",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = 1,
	},
	[8] = { 
		xls_id = 8,
		EnevtName = "混沌·新月金焱圣龙",
		BGimg = "jm_33",
		Types = "召唤",
		Image = "hd08",
		Mob_MonName = "混沌·新月金焱圣龙",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = 1,
	},
	[9] = { 
		xls_id = 9,
		EnevtName = "时之裂隙-古冥",
		BGimg = "jm_19",
		Types = "副本",
		Image = "fu01",
		Mob_MonName = {
			[1] = "仙之灵犀鸟",
			[2] = "万年神木守护",
			[3] = "暗黑终结者",
			[4] = "银爪收割者",
			[5] = "狂暴蝴蝶仙子",
			[6] = "谷中噩梦人",
			[7] = "深渊的魔兽",
			[8] = "镰骨妖",
			[9] = "被注入魔力的黑野猪",
		},
		MapID = "ShiZhiLieXi-GuMing",
		BuffId = "nil",
		Mob_MonNum = 3,
	},
	[10] = { 
		xls_id = 10,
		EnevtName = "时之裂隙-幻境",
		BGimg = "jm_20",
		Types = "副本",
		Image = "fu02",
		Mob_MonName = {
			[1] = "三魂四魄者[赤血]",
			[2] = "小妖魔安菲翁[乱世]",
			[3] = "背负棺材的男人[死神之子]",
			[4] = "生命终结者[异界]",
		},
		MapID = "ShiZhiLieXi-HuanJing",
		BuffId = "nil",
		Mob_MonNum = 2,
	},
	[11] = { 
		xls_id = 11,
		EnevtName = "时之裂隙-烈焰",
		BGimg = "jm_21",
		Types = "副本",
		Image = "fu03",
		Mob_MonName = {
			[1] = "怪异五通兽「通天」",
			[2] = "死亡歌颂者「灵主」",
			[3] = "神圣气息的九头龙[远古遗族]",
			[4] = "雷之法界·长风[道法合一]",
			[5] = "妖々天煞",
			[6] = "★★★夜魂★★★",
			[7] = "金符鬼奴·赤虚[掌控]",
			[8] = "山神修普诺斯[至高神灵]",
			[9] = "暗之神·麦尔柯[咆哮]",
		},
		MapID = "ShiZhiLieXi-LieYan",
		BuffId = "nil",
		Mob_MonNum = 2,
	},
	[12] = { 
		xls_id = 12,
		EnevtName = "时之裂隙-幽冥",
		BGimg = "jm_22",
		Types = "副本",
		Image = "fu04",
		Mob_MonName = {
			[1] = "阴朝地府的鬼[索命]",
			[2] = "远古四臂魔王[鬼神]",
			[3] = "蔓延恐惧的怪物「九头蛇」",
			[4] = "天魔之子佐玛[魔狱]",
			[5] = "阴尸鬼王·尸山血海",
			[6] = "鬼界至尊·五方鬼帝",
		},
		MapID = "ShiZhiLieXi-YouMing",
		BuffId = "nil",
		Mob_MonNum = 2,
	},
	[13] = { 
		xls_id = 13,
		EnevtName = "时之裂隙-恶狱",
		BGimg = "jm_23",
		Types = "副本",
		Image = "fu05",
		Mob_MonName = {
			[1] = "道罗斯·黑龙神[MAX]",
			[2] = "寒冬之凛·瑟斯[神话]",
			[3] = "暗裔·天魔使者[殺]",
			[4] = "哥布林之王·高格(Boss)",
			[5] = "炎魔·拉格纳罗斯",
			[6] = "（古神）克苏恩",
			[7] = "月光领主·拉卡诺斯(Boss)",
		},
		MapID = "ShiZhiLieXi-EYu",
		BuffId = "nil",
		Mob_MonNum = 2,
	},
	[14] = { 
		xls_id = 14,
		EnevtName = "时之裂隙-天穹",
		BGimg = "jm_24",
		Types = "副本",
		Image = "fu06",
		Mob_MonName = {
			[1] = "水晶巨兽",
			[2] = "真·深海霸主SSSSSS",
			[3] = "血神·哈卡の化身",
			[4] = "暗⊙灾祸领主·斯卡文",
			[5] = "雪域巨魔之王[暴怒]",
			[6] = "基尔罗格死眼[统治威严]",
			[7] = "断头者勇士[无畏]",
			[8] = "虚空冰晶蝎[异界]",
			[9] = "圣者米歇尔[神圣]",
		},
		MapID = "ShiZhiLieXi-TianQiong",
		BuffId = "nil",
		Mob_MonNum = 2,
	},
	[15] = { 
		xls_id = 15,
		EnevtName = "时之裂隙-破晓",
		BGimg = "jm_25",
		Types = "副本",
		Image = "fu07",
		Mob_MonName = {
			[1] = "地狱烈焰·亡灵骑士(Boss)",
			[2] = "究极巨龙纳特拉(Boss)",
			[3] = "时间预言者·佉罗(Boss)",
			[4] = "暗夜君王·影之鬼面(Boss)",
			[5] = "禁忌·秩序的起源(Boss)",
			[6] = "地狱烈焰·亡灵骑士(Boss)",
			[7] = "封印的熾天使(Boss)",
		},
		MapID = "ShiZhiLieXi-PoXiao",
		BuffId = "nil",
		Mob_MonNum = 2,
	},
	[16] = { 
		xls_id = 16,
		EnevtName = "时之裂隙-新月",
		BGimg = "jm_34",
		Types = "副本",
		Image = "fu08",
		Mob_MonName = {
			[1] = "",
			[2] = "血刃‖破天异魔皇(BOSS)",
			[3] = "夜风‖血空邪君◆◆◆(BOSS)",
			[4] = "星界‖御天帝⊙⊙⊙(BOSS)",
			[5] = "魂主※千星之辉★★★★★(BOSS)",
			[6] = "无间裂隙¤¤混沌天魔¤¤(BOSS)",
			[7] = "●●●●无序主教·擎天●●●●(BOSS)",
			[8] = "新月域主￠￠￠￠￠￠￠",
			[9] = "無上生霊″魂灭生￠￠￠￠￠￠￠",
		},
		MapID = "shenmi",
		BuffId = "nil",
		Mob_MonNum = 1,
	},
	[17] = { 
		xls_id = 17,
		EnevtName = "巨龙幼崽",
		BGimg = "nil",
		Types = "事件",
		Image = "sj01",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = {
			[1] = 31001,
		},
		Mob_MonNum = "nil",
	},
	[18] = { 
		xls_id = 18,
		EnevtName = "老铁匠",
		BGimg = "nil",
		Types = "事件",
		Image = "sj02",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = "nil",
	},
	[19] = { 
		xls_id = 19,
		EnevtName = "邪恶秘籍",
		BGimg = "nil",
		Types = "事件",
		Image = "sj03",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = {
			[1] = 31002,
		},
		Mob_MonNum = "nil",
	},
	[20] = { 
		xls_id = 20,
		EnevtName = "荒野迷宫",
		BGimg = "nil",
		Types = "事件",
		Image = "sj04",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = "nil",
	},
	[21] = { 
		xls_id = 21,
		EnevtName = "狗策划的手机",
		BGimg = "nil",
		Types = "事件",
		Image = "sj05",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = {
			[1] = 31003,
			[2] = 31004,
			[3] = 31005,
		},
		Mob_MonNum = "nil",
	},
	[22] = { 
		xls_id = 22,
		EnevtName = "技术大神的电脑",
		BGimg = "nil",
		Types = "事件",
		Image = "sj06",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = {
			[1] = 31006,
			[2] = 31007,
			[3] = 31008,
		},
		Mob_MonNum = "nil",
	},
	[23] = { 
		xls_id = 23,
		EnevtName = "老G的老舅",
		BGimg = "nil",
		Types = "事件",
		Image = "sj07",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = {
			[1] = 31009,
			[2] = 31010,
		},
		Mob_MonNum = "nil",
	},
	[24] = { 
		xls_id = 24,
		EnevtName = "无主的宝箱",
		BGimg = "nil",
		Types = "事件",
		Image = "sj08",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = "nil",
	},
	[25] = { 
		xls_id = 25,
		EnevtName = "美女出浴",
		BGimg = "nil",
		Types = "事件",
		Image = "sj09",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = {
			[1] = 31011,
			[2] = 31012,
		},
		Mob_MonNum = "nil",
	},
	[26] = { 
		xls_id = 26,
		EnevtName = "老乞丐",
		BGimg = "nil",
		Types = "事件",
		Image = "sj10",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = "nil",
	},
	[27] = { 
		xls_id = 27,
		EnevtName = "腐化符文",
		BGimg = "nil",
		Types = "事件",
		Image = "sj11",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = {
			[1] = 31014,
		},
		Mob_MonNum = "nil",
	},
	[28] = { 
		xls_id = 28,
		EnevtName = "契约",
		BGimg = "nil",
		Types = "事件",
		Image = "sj12",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = {
			[1] = 31015,
			[2] = 31016,
		},
		Mob_MonNum = "nil",
	},
	[29] = { 
		xls_id = 29,
		EnevtName = "诅咒的宝箱",
		BGimg = "nil",
		Types = "事件",
		Image = "sj13",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = {
			[1] = 31017,
		},
		Mob_MonNum = "nil",
	},
	[30] = { 
		xls_id = 30,
		EnevtName = "遗落的祭坛",
		BGimg = "nil",
		Types = "事件",
		Image = "sj14",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = {
			[1] = 31018,
			[2] = 31019,
		},
		Mob_MonNum = "nil",
	},
	[31] = { 
		xls_id = 31,
		EnevtName = "云游商人",
		BGimg = "nil",
		Types = "事件",
		Image = "sj16",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = "nil",
	},
	[32] = { 
		xls_id = 32,
		EnevtName = "黑市商人",
		BGimg = "nil",
		Types = "事件",
		Image = "sj17",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = "nil",
	},
	[33] = { 
		xls_id = 33,
		EnevtName = "钱庄老板",
		BGimg = "nil",
		Types = "事件",
		Image = "sj18",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = "nil",
	},
	[34] = { 
		xls_id = 34,
		EnevtName = "未知的洞窟",
		BGimg = "nil",
		Types = "事件",
		Image = "sj15",
		Mob_MonName = "nil",
		MapID = "nil",
		BuffId = "nil",
		Mob_MonNum = "nil",
	},
}
return config
