local config = { 
	[1] = { 
		xls_id = 1,
		attDesc = "每10秒恢复5%的生命值",
		TMtype = 4,
		buffId = 30055,
		name = "复苏之风",
		fontDesc = "如春风拂面，带来生命的复苏与活力，持续恢复生机。",
	},
	[2] = { 
		xls_id = 2,
		attDesc = "每8刀会额外斩杀目标1%的最大生命值！（仅对怪有效）",
		TMtype = 1,
		buffId = 3001,
		name = "以下克上",
		attackType = 3,
		fontDesc = "挑战强敌，逆袭而上，展现出绝对的斩杀之力。",
	},
	[3] = { 
		xls_id = 3,
		attr = {
			[1] = {
				[1] = 219,
				[2] = 3,
			},
		},
		attDesc = "增加命中率+3%",
		TMtype = 2,
		name = "精准打击",
		fontDesc = "精准无比的攻击，目标无所遁形，百发百中。",
	},
	[4] = { 
		xls_id = 4,
		attr = {
			[1] = {
				[1] = 220,
				[2] = 3,
			},
		},
		attDesc = "增加闪避率+3%",
		TMtype = 2,
		name = "灵狐之巧",
		fontDesc = "灵动如狐，身形灵活敏捷，闪避敌人的攻击。",
	},
	[5] = { 
		xls_id = 5,
		attr = {
			[1] = {
				[1] = 30,
				[2] = 5,
			},
		},
		attDesc = "体力上限+5%",
		TMtype = 2,
		name = "泰坦之躯",
		fontDesc = "拥有泰坦般的强悍体魄，生命力强大，稳如磐石。",
	},
	[6] = { 
		xls_id = 6,
		attr = {
			[1] = {
				[1] = 9,
				[2] = 100,
			},
			[2] = {
				[1] = 10,
				[2] = 100,
			},
			[3] = {
				[1] = 11,
				[2] = 100,
			},
			[4] = {
				[1] = 12,
				[2] = 100,
			},
		},
		attDesc = "双防增加100-100",
		TMtype = 2,
		name = "铜墙铁壁",
		fontDesc = "坚如铜墙铁壁，防御力无懈可击。",
	},
	[7] = { 
		xls_id = 7,
		attr = {
			[1] = {
				[1] = 14,
				[2] = 8,
			},
		},
		attDesc = "每拥有15格背包，增加1点敏捷",
		TMtype = 2,
		name = "灵动之力",
		fontDesc = "敏捷如风，身形灵动，背包空间越大，灵活度越高。",
	},
	[8] = { 
		xls_id = 8,
		attDesc = "每日首次登录时，自动获得1-100W金币",
		TMtype = 3,
		value = 18,
		name = "有福之人",
		fontDesc = "天赐鸿福，福运加身，每日初临便获丰厚金币。",
	},
	[9] = { 
		xls_id = 9,
		attr = {
			[1] = {
				[1] = 213,
				[2] = 5,
			},
			[2] = {
				[1] = 214,
				[2] = 5,
			},
		},
		attDesc = "双防上限增加5%",
		TMtype = 2,
		name = "金刚体魄",
		fontDesc = "如金刚般坚固的体魄，防御力达到极致，无坚不摧。",
	},
	[10] = { 
		xls_id = 10,
		attDesc = "攻击时2%的概率触发蛛网，减速目标3S",
		TMtype = 1,
		buffId = 1000,
		name = "蜘蛛侠",
		attackType = 1,
		fontDesc = "灵活如蛛，攻击时有几率触发蛛网，缠绕并减速敌人。",
	},
	[11] = { 
		xls_id = 11,
		attDesc = "受到攻击时有1%概率释放神圣战甲术",
		TMtype = 1,
		buffId = 10000,
		name = "奇门遁甲",
		attackType = 10,
		fontDesc = "神秘莫测，受到攻击时有概率触发神圣战甲术，护身保命。",
	},
	[12] = { 
		xls_id = 12,
		attDesc = "服务器每天开放1天，增加5-5的防御（最高增加200点）",
		TMtype = 3,
		value = 19,
		name = "以逸待劳",
		fontDesc = "休养生息，以备战斗，每天服务器开放时防御力逐步提升。",
	},
	[13] = { 
		xls_id = 13,
		attDesc = "黑夜的时候，攻魔道双防增加160-160",
		TMtype = 3,
		value = 28,
		name = "黑夜传说",
		fontDesc = "在黑夜中如传说般强大，攻魔道防全面提升。",
	},
	[14] = { 
		xls_id = 14,
		attDesc = "每杀死一只怪物获得怪物血量1%的金币（每天上限1千万）",
		TMtype = 1,
		buffId = 14000,
		name = "招财之灵",
		attackType = 14,
		fontDesc = "拥有神奇的招财能力，每次击杀怪物都能获得丰厚金币。",
	},
	[15] = { 
		xls_id = 15,
		attDesc = "挂机时，受到的伤害减少5%",
		TMtype = 1,
		buffId = 10001,
		name = "挂机佬",
		attackType = 10,
		fontDesc = "专精于挂机状态，受到的伤害显著减少，更加安全。",
	},
	[16] = { 
		xls_id = 16,
		attDesc = "组队时全属性增加200-200",
		TMtype = 3,
		value = 29,
		name = "共振共鸣",
		fontDesc = "组队作战时，团队成员之间产生共鸣，全属性大幅提升。",
	},
	[17] = { 
		xls_id = 17,
		attr = {
			[1] = {
				[1] = 24,
				[2] = 7,
			},
		},
		attDesc = "7%的暴击抵抗",
		TMtype = 2,
		name = "深渊噬魂",
		fontDesc = "灵魂深处的防御，抵御暴击伤害，增加暴击抵抗力。",
	},
	[18] = { 
		xls_id = 18,
		attr = {
			[1] = {
				[1] = 78,
				[2] = 80,
			},
		},
		attDesc = "攻击附带80点破甲效果",
		TMtype = 2,
		name = "混元之矛",
		fontDesc = "攻击时附带破甲之力，轻松击穿敌人的防御。",
	},
	[19] = { 
		xls_id = 19,
		attr = {
			[1] = {
				[1] = 75,
				[2] = 1000,
			},
		},
		attDesc = "怪物伤害提升10%",
		TMtype = 2,
		name = "斩妖除魔",
		fontDesc = "专注于清除邪恶势力，对怪物造成的伤害大幅提升。",
	},
	[20] = { 
		xls_id = 20,
		attDesc = "被怪物攻击时3%概率恢复10%的血量。",
		TMtype = 1,
		buffId = 9000,
		name = "越战越勇",
		attackType = 9,
		fontDesc = "在战斗中愈加勇猛，被怪物攻击时有几率迅速恢复血量。",
	},
	[21] = { 
		xls_id = 21,
		attDesc = "当暗夜降临时提升8%最大生命暗夜时间(23:00-8:59）",
		TMtype = 3,
		value = 234,
		name = "暗黑",
		fontDesc = "当黑暗笼罩大地，夜幕降临之时，生命之力随着暗夜的降临而复苏",
	},
	[22] = { 
		xls_id = 22,
		attDesc = "当黎明降临时提升8%最大攻击黎明时间(9:00-22:59)",
		TMtype = 3,
		value = 235,
		name = "黎明",
		fontDesc = "破晓之光照耀大地，赋予持有者新的力量",
	},
	[23] = { 
		xls_id = 23,
		attr = {
			[1] = {
				[1] = 200,
				[2] = 1111,
			},
			[2] = {
				[1] = 206,
				[2] = 3,
			},
		},
		attDesc = "对怪切割+1111，最大攻击+3%",
		TMtype = 2,
		name = "杀伐之道",
		fontDesc = "此道乃为战斗而生，血与火的洗礼中铸就无情的锋芒",
	},
	[24] = { 
		xls_id = 24,
		attDesc = "全技能伤害增加3%",
		TMtype = 3,
		value = 236,
		name = "疋杀地蔵",
		fontDesc = "每一招每一式都带着灭绝一切的杀意，令敌人无所遁形",
	},
}
return config
