local config = { 
	[1] = { 
		xls_id = 1,
		id = 1,
		remarks = "进入游戏发送欢迎邮件",
		title = "欢迎来到蓝月争霸！",
		boxReward = "499#1000000#0&6#500#0",
		content = "这个游戏非常好玩，快点喊你家人来玩",
	},
	[2] = { 
		xls_id = 2,
		id = 2,
		remarks = "等级到50",
		title = "恭喜达到50级！",
		content = {
			[1] = "请继续升级，50级还没有入门。你可以通过<font color='#01f801'><u><a href='event:open",
			[2] = 509,
			[3] = "3'>击杀BOSS</a></u></font></font>来提升自己的逼格",
		},
	},
	[3] = { 
		xls_id = 3,
		id = 3,
		remarks = "等级到80",
		title = "恭喜达到80级！",
		content = {
			[1] = "请继续升级，你可以准备转生啦。你可以通过<font color='#01f801'><u><a href='event:open",
			[2] = 509,
			[3] = "3'>击杀BOSS</a></u></font></font>来提升自己的逼格",
		},
	},
	[4] = { 
		xls_id = 4,
		id = 4,
		remarks = "巅峰竞技每周结算",
		title = "巅峰竞技排名奖励",
		content = "你在本周巅峰竞技中的今日排名为{0}，你获得了如下奖励",
	},
	[5] = { 
		xls_id = 5,
		id = 5,
		remarks = "巅峰竞技被人打败",
		title = "巅峰竞技排名下降",
		content = {
			[1] = "<font color='#53b436'>{0}</font>在巅峰竞技中击败了你，你的排名下降到了{1}，快去巅峰竞技中复仇吧。<font color='#53b436'><u><a href='event:open",
			[2] = 539,
			[3] = "2'>点击前往巅峰竞技</a></u></font></font>",
		},
	},
	[6] = { 
		xls_id = 6,
		id = 6,
		remarks = "开服冲榜通用奖励",
		title = "冲榜活动排名奖励",
		content = "恭喜！您在<font color='#01f801'>{0}</font>的活动中力压群雄，名列第<font color='#01f801'>{1}</font>，以下是为您奉上的丰厚奖励，请查收！",
	},
	[7] = { 
		xls_id = 7,
		id = 7,
		remarks = "天梯排名奖励",
		title = "天梯排名奖励",
		content = "你在上上赛季的天梯排名尚未领取，系统已为你自动领取。",
	},
	[8] = { 
		xls_id = 8,
		id = 11,
		remarks = "开服特戒回馈奖励",
		title = "特戒回馈活动返利",
		content = "您在开服第一天特戒回馈活动中购买了活动道具，以下是给您<font color='#01f801'>全额返还</font>的灵符，请查收！",
	},
	[9] = { 
		xls_id = 9,
		id = 12,
		remarks = "红包退还邮件",
		title = "红包退回",
		content = "您于{0}时派发的红包未被抢完，余额{1}，请领取。",
	},
	[10] = { 
		xls_id = 10,
		id = 13,
		remarks = "沙城霸主奖励",
		title = "沙城主奖励",
		content = "恭喜贵帮占领沙城，以下是为恭喜帮主获得如下奖励，现在为您发放<font color='#53b436'>嘉奖奖励</font>，请查收！",
	},
	[11] = { 
		xls_id = 11,
		id = 14,
		remarks = "沙城争霸行会排名",
		title = "沙城争霸行会排名",
		content = "贵帮在沙城争霸活动中，获得了{0}积分，排名第{1}，以下是贵帮的排名奖励，请查收。",
	},
	[12] = { 
		xls_id = 12,
		id = 15,
		remarks = "沙城争霸个人排名",
		title = "沙城争霸个人排名",
		content = "您在沙城争霸活动中，获得了{0}积分，排名第{1}，以下是您的排名奖励，请查收。",
	},
	[13] = { 
		xls_id = 13,
		id = 16,
		remarks = "沙城争霸积分奖励",
		title = "沙城争霸积分奖励",
		content = "您在沙城争霸活动中尚有积分达标奖励未被领取，请领取。",
	},
	[14] = { 
		xls_id = 14,
		id = 17,
		remarks = "竞技场排行奖励",
		title = "竞技场排行奖励",
		content = "鉴于你在上赛季竞技场中的优异表现，排名第{0}，以下是您的排名奖励，请查收",
	},
	[15] = { 
		xls_id = 15,
		id = 18,
		remarks = "竞技场段位邮件",
		title = "竞技场段位奖励",
		content = "以下时你在上赛季的竞技场中的段位奖励，请查收",
	},
	[16] = { 
		xls_id = 16,
		id = 19,
		remarks = "物品找回",
		title = "物品找回",
		content = "盟重城守卫在野外巡逻时发现了一些物品，似乎是你遗失的物品。",
	},
	[17] = { 
		xls_id = 17,
		id = 20,
		remarks = "财富幸运儿大奖",
		title = "财富幸运儿",
		content = "恭喜你在财富幸运儿中得幸运大奖，这是你的奖励，请查收",
	},
	[18] = { 
		xls_id = 18,
		id = 21,
		remarks = "我要变强",
		title = "我要变强",
		boxReward = "1007#1#0&1#8#0&2#8#0&6#8#0&20#8#0&41#8#0&499#8#0&19#8#0",
		content = {
			[1] = "亲爱的玩家：<br>欢迎您来到本游戏，感谢您对本游戏的支持和热爱。<br>恭喜您达到<font color='#01f801'>100级</font>，后续的勇士之路还很漫长<br>您可以通过<font color='#01f801'><u><a href='event:open",
			[2] = 556,
			[3] = "0'>我要变强</a></u></font></font>来了解如何提升自己更多实力。<br>寻找一个帮派，和志同道合的兄弟一起打天下！<br><font color='#01f801'><u><a href='event:open",
			[4] = 506,
			[5] = "0'>点击打开</a></u></font></font>",
		},
	},
	[19] = { 
		xls_id = 19,
		id = 22,
		remarks = "作废",
		title = "作废！",
		content = "恭喜你上周在<font color='#01f801'>王者禁地</font>中，通关至第{0}层，如下是你的奖励，请及时领取",
	},
	[20] = { 
		xls_id = 20,
		id = 23,
		remarks = "王者禁地周排行奖励",
		title = "王者禁地周排行奖励",
		content = "恭喜你上周在<font color='#01f801'>王者禁地</font>中，排行第{0}，如下是你的奖励，请及时领取",
	},
	[21] = { 
		xls_id = 21,
		id = 24,
		remarks = "爱微游关注礼包",
		title = "关注礼包",
		boxReward = "20445718#1",
		content = "感谢您的关注，以下是为您奉上关注礼包，请查收。",
	},
	[22] = { 
		xls_id = 22,
		id = 25,
		remarks = "爱微游邀请礼包",
		title = "邀请礼包",
		boxReward = "20445719#1",
		content = "您已成功邀请好友加入游戏，以下是为您奉上邀请礼包，请查收。",
	},
	[23] = { 
		xls_id = 23,
		id = 28,
		remarks = "踢出行会通知",
		title = "您被踢出行会",
		content = "  非常遗憾，您被<font color='#01f801'>{0}</font>踢出了行会<font color='#01f801'>{1}</font>。",
	},
	[24] = { 
		xls_id = 24,
		id = 29,
		remarks = "开服英雄等级冲榜奖励",
		title = "英雄等级冲榜活动排名奖励",
		content = "恭喜！您在开服英雄等级冲榜的活动中力压群雄，名列第{0}，以下是为您奉上的丰厚奖励，请查收。",
	},
	[25] = { 
		xls_id = 25,
		id = 30,
		remarks = "宝物被夺",
		title = "宝物被夺",
		content = {
			[1] = "<font color='#53b436'>{0}</font>抢夺了你的<font color='#53b436'>{1}</font>，前往夺宝复仇吧。<font color='#01f801'><u><a href='event:open",
			[2] = 321,
			[3] = "0'>前往夺回</a></u></font></font>",
		},
	},
	[26] = { 
		xls_id = 26,
		id = 34,
		remarks = "轮回BOSS参与奖励",
		title = "轮回BOSS参与奖励",
		content = "很遗憾没能成功击杀轮回BOSS，这是为您奉上的参与奖励以示慰藉。",
	},
	[27] = { 
		xls_id = 27,
		id = 35,
		remarks = "合服沙城霸主奖励",
		title = "合服沙城霸主奖励",
		content = "恭喜贵帮在合服后第一次沙城争霸占领沙城，以下是沙城霸主奖励，请查收。",
	},
	[28] = { 
		xls_id = 28,
		id = 36,
		remarks = "合服沙城精英奖励",
		title = "合服沙城精英奖励",
		content = "恭喜贵帮在合服后第一次沙城争霸占领沙城，以下是沙城精英奖励，请查收。",
	},
	[29] = { 
		xls_id = 29,
		id = 38,
		remarks = "野战排行奖励",
		title = "野战排行奖励",
		content = "恭喜！您在昨天的野战中表现优秀，名列第{0}，以下是为您奉上的丰厚奖励，请查收。",
	},
	[30] = { 
		xls_id = 30,
		id = 43,
		remarks = "天降红包",
		title = "天降红包",
		content = "恭喜！以下是您在天降红包中获得的灵符，请查收。",
	},
	[31] = { 
		xls_id = 31,
		id = 44,
		remarks = "BOSS护盾奖励",
		title = "BOSS护盾奖励",
		content = "恭喜！您在攻击BOSS护盾时获得幸运大奖，以下是为您奉上的丰厚奖励，请查收。",
	},
	[32] = { 
		xls_id = 32,
		id = 45,
		remarks = "限时惊喜",
		title = "限时惊喜",
		content = "你的限时惊喜的返利道具忘了领取，请查收",
	},
	[33] = { 
		xls_id = 33,
		id = 46,
		remarks = "热血乱斗场奖励",
		title = "热血乱斗场奖励",
		content = "恭喜！您在热血乱斗场活动中力压群雄，名列第{0}，以下是为您奉上的丰厚奖励，请查收。",
	},
	[34] = { 
		xls_id = 34,
		id = 47,
		remarks = "封魔奖励",
		title = "封魔奖励",
		content = "这是您遗漏在封魔中的奖励！",
	},
	[35] = { 
		xls_id = 35,
		id = 49,
		remarks = "沙城争霸霸主奖励",
		title = "沙城主额外奖励",
		content = "恭喜贵帮在本次沙城争霸活动中成功占领沙城，以下是沙城霸主奖励，请查收。",
	},
	[36] = { 
		xls_id = 36,
		id = 50,
		remarks = "沙城争霸精英奖励",
		title = "沙城成员额外奖励",
		content = "恭喜贵帮在本次沙城争霸活动中成功占领沙城，以下是沙城精英奖励，请查收。",
	},
	[37] = { 
		xls_id = 37,
		id = 51,
		remarks = "七日狂欢",
		title = "七日狂欢",
		content = "恭喜！你在七日狂欢活动中累计完成了{0}个任务，获得了如下奖励，请查收",
	},
	[38] = { 
		xls_id = 38,
		id = 52,
		remarks = "开服灵宝冲榜奖励",
		title = "开服灵宝冲榜奖励",
		content = "恭喜！您在开服灵宝冲榜的活动中力压群雄，名列第{0}，以下是为您奉上的丰厚奖励，请查收。",
	},
	[39] = { 
		xls_id = 39,
		id = 53,
		remarks = "7转炼魂开启邮件",
		title = "炼魂系统开启",
		content = {
			[1] = "恭喜您成功激活了炼魂系统！<font color='#01f801'><u><a href='event:open",
			[2] = 501,
			[3] = "6'>前往升级</a></u></font></font><br>1.炼魂六道分为：地狱道、饿鬼道、畜生道、修罗道、人间道、天道<br>2.每道分为<font color='0x01f801'>六境</font>，依次为：玄、生、破、虚、妄、灭<br>3.消耗一定的<font color='0x01f801'>业力</font>由玄境开始顺时针依次激活六境<br>4.升级炼魂可获得无视防御的连击神圣伤害，威力巨大<br>5.获取“业力”提升炼魂，可消耗经验或者购买炼魂丹来兑换<br>6.炼魂达到地狱道·破境即可开启第一组<font color='0x01f801'>炼魂BOSS</font>，在遗迹BOSS页面击杀；炼魂等级越高，开启的炼魂BOSS越多<br>7.炼魂BOSS产出大量<font color='0x01f801'>炼魂装备</font>，穿戴炼魂装备可获得无视防御的神圣伤害、提高神圣伤害百分比的神圣精通和合击伤害减免，威力极其巨大",
		},
	},
	[40] = { 
		xls_id = 40,
		id = 54,
		remarks = "每日累充活动奖励",
		title = "每日累充奖励",
		content = "这是您遗漏的每日累充奖励，敬请查收！",
	},
	[41] = { 
		xls_id = 41,
		id = 55,
		remarks = "每周累充活动奖励",
		title = "每周累充奖励",
		content = "这是您遗漏的每周累充奖励，敬请查收！",
	},
	[42] = { 
		xls_id = 42,
		id = 56,
		remarks = "58级引导邮件",
		title = "提升攻略",
		content = {
			[1] = "恭喜您达到了58级，以下攻略可助您快速提升战力：<br>1.挑战关卡可以提升<font color='#01f801'>【经验】</font>，提升关卡效率<br>2.进行<font color='#01f801'>无尽封魔</font>和<font color='#01f801'>百炼塔</font>可以快速获得海量<font color='#01f801'>【经验】</font>，等级飙升<br>3.<font color='#01f801'>首充</font>可获得永久保值<font color='#01f801'>无级别神装</font>、<font color='#01f801'>等级直升丹</font>、以及<font color='#01f801'>海量灵符</font>，<font color='#01f801'>【战力】暴涨200000</font>，轻松碾压各种BOSS<br>4.<font color='#01f801'>至尊2</font>可提前解锁第二个角色，<font color='#01f801'>至尊4</font>可提前解锁第三个角色，战力倍增，助你推关升级无往不利<br>5.<font color='#01f801'>充值至尊</font>可极速飞升战力<font color='0x01f801'><u><a href='event:open",
			[2] = "599'>前往充值</a></u></font></font>",
		},
	},
	[43] = { 
		xls_id = 43,
		id = 57,
		remarks = "开服2天引导",
		title = "圣域BOSS开启",
		boxReward = "1007#1",
		content = {
			[1] = "开服第二天开启<font color='#01f801'>圣域BOSS</font><br>1.人物等级或者转生等级越高，可击杀的圣域BOSS数量越多<br>2.BOSS等级越高，掉落<font color='#01f801'>高阶圣域装备</font>和<font color='#01f801'>高阶人物战装</font>概率越大<br>3.奖励分为<font color='#01f801'>归属者</font>奖励和<font color='#01f801'>非归属者</font>奖励，归属者奖励获得极品的概率提升<font color='#01f801'>5倍<br>4.每次进入消耗1次挑战次数，挑战次数每<font color='#01f801'>2</font>小时恢复一次，最高可累计<font color='#01f801'>12</font>次<br><font color='0x01f801'><u><a href='event:open",
			[2] = 549,
			[3] = "2'>前往挑战</a></u></font></font>",
		},
	},
	[44] = { 
		xls_id = 44,
		id = 58,
		parameter = 9999,
		remarks = "开服4天引导",
		title = "宝石系统开启",
		boxReward = "1046#1",
		content = {
			[1] = "开服第四天开启<font color='#01f801'>宝石系统</font><br>1.消耗<font color='#01f801'>打孔石</font>可解锁人物宝石槽，解锁槽位后镶嵌宝石可增加<font color='#01f801'>大量战力</font><br>2.挑战百炼塔可获得<font color='#01f801'>大量宝石</font>和<font color='#01f801'>解锁宝石槽位</font><br>3.百炼塔每通关一重天可参与转盘抽奖，奖励包括<font color='#01f801'>高级宝石</font>、<font color='#01f801'>角色红装</font>等极品奖励等你来<br><font color='0x01f801'><u><a href='event:open",
			[2] = 513,
			[3] = "2'>前往查看</a></u></font></font>",
		},
	},
	[45] = { 
		xls_id = 45,
		id = 59,
		parameter = 9999,
		remarks = "开服5天引导",
		title = "跨服主城开启",
		boxReward = "1172#1",
		content = {
			[1] = "开服第五天开启<font color='#01f801'>跨服主城</font<br>1.玩家通过第二大陆<font color='#01f801'>传送阵</font>前往跨服主城<br>2.击杀跨服主城<font color='#01f801'>特殊BOSS</font>可获得稀有魂装<br><font color='0x01f801'><u><a href='event:open",
			[2] = 314,
			[3] = "1'>前往查看</a></u></font></font>",
		},
	},
	[46] = { 
		xls_id = 46,
		id = 60,
		parameter = 9999,
		remarks = "开服6天引导",
		title = "兽巢开启",
		content = "开服第六天开启<font color='#01f801'>兽巢</font>多人副本，人物达到<font color='#01f801'>4</font>转可挑战<br>1.兽巢可单人挑战，也可以多人组队一起挑战<br>2.首次通关可获得首通奖励，每周二、周六刷新首通奖励",
	},
	[47] = { 
		xls_id = 47,
		id = 61,
		parameter = 9999,
		remarks = "开服8天引导",
		title = "跨服战场开启",
		content = {
			[1] = "开服第八天开启<font color='#01f801'>跨服战场</font><br>1.参与跨服战场可以获得<font color='#01f801'>绝版守护</font>奖励<br>2.每天回复<font color='#01f801'>3次</font>归属和协助奖励次数<br>3.协助同行会的兄弟获得归属奖励时，自己也将获得一份<font color='#01f801'>归属奖励</font><br><font color='0x01f801'><u><a href='event:open",
			[2] = 314,
			[3] = "2'>前往挑战</a></u></font></font>",
		},
	},
	[48] = { 
		xls_id = 48,
		id = 62,
		remarks = "开服11天引导",
		title = "洛神图系统开启",
		content = {
			[1] = "开服第十一天开启<font color='#01f801'>洛神图</font>及专属副本<font color='#01f801'>王者禁地</font><br>1.王者禁地每日可挑战一次<br>2.击杀BOSS后有几率掉落稀有<font color='#01f801'>洛神图</font>及<font color='#01f801'>洛神之魂</font>，疯狂增长战力<br><font color='0x01f801'><u><a href='event:open",
			[2] = 513,
			[3] = "5'>前往挑战</a></u></font></font>",
		},
	},
	[49] = { 
		xls_id = 49,
		id = 63,
		remarks = "开服12天引导",
		title = "寻宝福利开启",
		content = "1.寻宝达到<font color='#01f801'>一定次数</font>即可领取超值奖励<br>2.涅槃圣石、诛仙装备、超级幸运药水统统都有",
	},
	[50] = { 
		xls_id = 50,
		id = 64,
		remarks = "守护系统引导",
		title = "守护系统开启",
		content = "恭喜您成功激活了守护系统！<br>1.开服达到<font color='0x01f801'>14</font>天，角色达到<font color='0x01f801'>5转</font>，即可开启人物的【守护】系统<br>2.使用<font color='0x01f801'>守护精元</font>可以提升守护星数，每满10星可以提升到下一阶<br>3.圣盾守护达到1阶10星即可开启<font color='0x01f801'>守护附体</font>天赋；开启守护附体天赋后，守护便可以被附体到角色上协同作战<br>4.提升守护等级可以提升守护属性，解锁<font color='0x01f801'>利刃</font>、<font color='0x01f801'>不动</font>、<font color='0x01f801'>鹰击</font>、<font color='0x01f801'>统帅</font>等四个技能，提升能力，增强战场统治力<br>5.不同等阶的守护可以使用不同数量的<font color='0x01f801'>守护资质丹</font>和<font color='0x01f801'>守护飞升丹</font>，飞速提升守护属性<br>6.守护可以穿戴<font color='0x01f801'>圣石</font>、<font color='0x01f801'>圣纹</font>、<font color='0x01f801'>圣晶</font>、<font color='0x01f801'>圣珠</font>四种装备，无等级限制，可在<font color='0x01f801'>合成</font>界面升级到更高品质<br>7.在<font color='0x01f801'>幻化</font>界面可以幻化守护的外形，获得额外的属性和战力<br>8.所有天赋激活后可<font color='0x01f801'>同时生效</font>，无需幻化，幻化只是改变守护的外观",
	},
	[51] = { 
		xls_id = 51,
		id = 65,
		remarks = "合服沙城争霸",
		title = "合服沙城争霸",
		content = "恭喜贵帮在合服后沙城争霸中占领沙城，贵帮获得了以下活动奖励，请查收",
	},
	[52] = { 
		xls_id = 52,
		id = 66,
		remarks = "合服沙城争霸",
		title = "合服沙城争霸",
		content = "恭喜贵帮在合服后沙城争霸占中领沙城，您在活动中名列贵帮个人积分排名前三名，获得了以下获得奖励，请查收",
	},
	[53] = { 
		xls_id = 53,
		id = 67,
		remarks = "开服14天引导",
		title = "守护系统开启",
		content = {
			[1] = "开服第十四天开启<font color='#01f801'>守护系统</font><font color='0x01f801'><u><a href='event:open",
			[2] = 505,
			[3] = "6'>前往激活</a></u></font></font><br>1.角色达到<font color='#01f801'>5</font>转可激活守护系统<br>2.圣盾守护达到1阶10星即可开启<font color='0x01f801'>守护附体</font>天赋，战斗时会出现守护的<font color='0x01f801'>外观</font>进行协同作战<br>3.升级<font color='#01f801'>守护</font>可获得<font color='#01f801'>海量战力</font>！",
		},
	},
	[54] = { 
		xls_id = 54,
		id = 68,
		remarks = "充值双倍重置",
		title = "充值双倍重置",
		content = {
			[1] = "亲爱的玩家您好，您的每档灵符的首次充值获得双倍灵符的奖励已重置，现在每档灵符首次充值都可以获得双倍灵符，<font color='#01f801'><u><a href='event:open",
			[2] = "599'>前往查看</a></u></font></font>。",
		},
	},
	[55] = { 
		xls_id = 55,
		id = 69,
		remarks = "行会解散",
		title = "行会解散",
		content = "亲爱的玩家您好，您所在的行会<font color='#01f801'>{0}</font>已被<font color='#01f801'>{1}</font>解散",
	},
	[56] = { 
		xls_id = 56,
		id = 70,
		remarks = "寻宝积分奖励",
		title = "寻宝积分奖励",
		content = "亲爱的玩家您好，您昨日有未领取的寻宝积分奖励，现通过邮件发放给您，请查收！",
	},
	[57] = { 
		xls_id = 57,
		id = 72,
		remarks = "开服15天引导",
		title = "沙城帝国开启",
		content = {
			[1] = "开服第十五天开启<font color='#01f801'>沙城帝国</font>和<font color='#01f801'>兽巢副本</font><font color='0x01f801'><u><a href='event:open",
			[2] = "314'>前往激活</a></u></font></font><br>1.角色达到<font color='#01f801'>5</font>转可激活沙城帝国<br>2.开服第<font color='#01f801'>30</font>天沙城帝国开放跨服地图<br>3.参与沙城帝国-守卫沙城可获得<font color='0x01f801'>稀有守护</font>和极品<font color='0x01f801'>守护装备</font>",
		},
	},
	[58] = { 
		xls_id = 58,
		id = 73,
		remarks = "开服25天引导",
		title = "结界系统开启",
		boxReward = "221#1",
		content = {
			[1] = "第二十五天开启<font color='#01f801'>结界系统</font><br>1.角色达到<font color='#01f801'>6</font>转可激活<br>2.激活阵法将获得海量的属性，且不同的阵法可以为现有的其他系统进行<font color='#01f801'>巨额加成</font><br>3.击杀<font color='#01f801'>沙城帝国——上古皇陵</font>内的BOSS可以掉落结界<font color='#01f801'>激活材料</font><u><a href='event:open",
			[2] = 314,
			[3] = "6'>前往</a></u></font></font>",
		},
	},
	[59] = { 
		xls_id = 59,
		id = 74,
		remarks = "人皇榜每周结算",
		title = "人皇榜排名奖励",
		content = "你在本周人皇榜中的今日排名为{0}，你获得了如下奖励",
	},
	[60] = { 
		xls_id = 60,
		id = 75,
		remarks = "开服18天引导",
		title = "神兵系统开启",
		content = {
			[1] = "开服第十八天开启<font color='#01f801'>神兵系统</font>和<font color='#01f801'>暗之秘境BOSS</font>副本<font color='0x01f801'><u><a href='event:open",
			[2] = 569,
			[3] = "7'>前往</a></u></font></font><br>1.角色达到<font color='#01f801'>6</font>转可激活神兵系统<br>2.开服第<font color='#01f801'>18</font>开启暗之秘境BOSS副本<br>3.击杀暗之秘境BOSS可有几率获得<font color='0x01f801'>神兵装备</font>！",
		},
	},
	[61] = { 
		xls_id = 61,
		id = 76,
		remarks = "开服6天引导",
		title = "组队副本开启",
		content = {
			[1] = "开服第六天开启<font color='#01f801'>组队副本-兽巢</font><br>1.<font color='#01f801'>兽巢副本</font>首杀可获得<font color='#01f801'>大量奖励</font>，更有几率获得<font color='#01f801'>幻化守护</font>！<br>2.每周<font color='#01f801'>二、六</font>重置首杀，闯关越多<font color='#01f801'>奖励越多</font>！<br><font color='0x01f801'><u><a href='event:open",
			[2] = 517,
			[3] = "6'>前往挑战</a></u></font></font>",
		},
	},
	[62] = { 
		xls_id = 62,
		id = 77,
		parameter = 9999,
		remarks = "开服20天开启荣耀之路、法器",
		title = "法器、荣耀之路",
		content = "开服第二十天开启<font color='#01f801'>法器和荣耀之路</font>，人物达到<font color='#01f801'>5</font>转可挑战荣耀之路副本和培养法器<br>1.通关荣耀之路副本可获得法器激活材料<br>2.法器激活后可以获得魔力转换被动效果，消耗魔法抵挡伤害",
	},
	[63] = { 
		xls_id = 63,
		id = 93,
		remarks = "灵符消费冲榜奖励",
		title = "灵符消费排名奖励",
		content = "恭喜！您在跨服灵符消费冲榜的活动中力压群雄，名列第{0}，以下是为您奉上的丰厚奖励，请查收。",
	},
	[64] = { 
		xls_id = 64,
		id = 94,
		remarks = "道具到期提醒",
		title = "道具到期提醒",
		content = "您的<font color='#fcd132'>{a}</font>已过期，敬请知晓！",
	},
	[65] = { 
		xls_id = 65,
		id = 95,
		remarks = "投资计划",
		title = "投资计划",
		content = "你的聚宝盆奖励忘记领取了，请查收。",
	},
	[66] = { 
		xls_id = 66,
		id = 96,
		remarks = "威名降级",
		title = "威名降级",
		content = {
			[1] = "非常遗憾，您的威名等级降低至<font color='#01f801'>名垂千古</font>!威名等级越低，越容易被高威名玩家压制。<br>完成日常任务可获取大量威望<font color='#01f801'><u><a href='event:open",
			[2] = "578'>前往查看</a></u></font></font><br>参与沙城争霸可获取大量威望<font color='#01f801'><u><a href='event:open",
			[3] = "506#7'>前往查看</a></u></font></font><br>参与热血乱斗场可获取大量威望<font color='#01f801'><u><a href='event:open",
			[4] = "531'>前往查看</a></u></font></font><br>购买月卡可获得额外20%的威望<font color='#01f801'><u><a href='event:open",
			[5] = "574#1'>前往查看</a></u></font></font>",
		},
	},
	[67] = { 
		xls_id = 67,
		id = 97,
		remarks = "威名降级",
		title = "威名降级",
		content = {
			[1] = "非常遗憾，您的威名等级降低至<font color='#01f801'>盖世无双</font>!威名等级越低，越容易被高威名玩家压制。<br>完成日常任务可获取大量威望<font color='#01f801'><u><a href='event:open",
			[2] = "578'>前往查看</a></u></font></font><br>参与沙城争霸可获取大量威望<font color='#01f801'><u><a href='event:open",
			[3] = "506#7'>前往查看</a></u></font></font><br>参与热血乱斗场可获取大量威望<font color='#01f801'><u><a href='event:open",
			[4] = "531'>前往查看</a></u></font></font><br>购买月卡可获得额外20%的威望<font color='#01f801'><u><a href='event:open",
			[5] = "574#1'>前往查看</a></u></font></font>",
		},
	},
	[68] = { 
		xls_id = 68,
		id = 98,
		remarks = "威名降级",
		title = "威名降级",
		content = {
			[1] = "非常遗憾，您的威名等级降低至<font color='#01f801'>登峰造极</font>!威名等级越低，越容易被高威名玩家压制。<br>完成日常任务可获取大量威望<font color='#01f801'><u><a href='event:open",
			[2] = "578'>前往查看</a></u></font></font><br>参与沙城争霸可获取大量威望<font color='#01f801'><u><a href='event:open",
			[3] = "506#7'>前往查看</a></u></font></font><br>参与热血乱斗场可获取大量威望<font color='#01f801'><u><a href='event:open",
			[4] = "531'>前往查看</a></u></font></font><br>购买月卡可获得额外20%的威望<font color='#01f801'><u><a href='event:open",
			[5] = "574#1'>前往查看</a></u></font></font>",
		},
	},
	[69] = { 
		xls_id = 69,
		id = 99,
		remarks = "威名降级",
		title = "威名降级",
		content = {
			[1] = "非常遗憾，您的威名等级降低至<font color='#01f801'>出神入化</font>!威名等级越低，越容易被高威名玩家压制。<br>完成日常任务可获取大量威望<font color='#01f801'><u><a href='event:open",
			[2] = "578'>前往查看</a></u></font></font><br>参与沙城争霸可获取大量威望<font color='#01f801'><u><a href='event:open",
			[3] = "506#7'>前往查看</a></u></font></font><br>参与热血乱斗场可获取大量威望<font color='#01f801'><u><a href='event:open",
			[4] = "531'>前往查看</a></u></font></font><br>购买月卡可获得额外20%的威望<font color='#01f801'><u><a href='event:open",
			[5] = "574#1'>前往查看</a></u></font></font>",
		},
	},
	[70] = { 
		xls_id = 70,
		id = 100,
		remarks = "威名降级",
		title = "威名降级",
		content = {
			[1] = "非常遗憾，您的威名等级降低至<font color='#01f801'>超凡脱俗</font>!威名等级越低，越容易被高威名玩家压制。<br>完成日常任务可获取大量威望<font color='#01f801'><u><a href='event:open",
			[2] = "578'>前往查看</a></u></font></font><br>参与沙城争霸可获取大量威望<font color='#01f801'><u><a href='event:open",
			[3] = "506#7'>前往查看</a></u></font></font><br>参与热血乱斗场可获取大量威望<font color='#01f801'><u><a href='event:open",
			[4] = "531'>前往查看</a></u></font></font><br>购买月卡可获得额外20%的威望<font color='#01f801'><u><a href='event:open",
			[5] = "574#1'>前往查看</a></u></font></font>",
		},
	},
	[71] = { 
		xls_id = 71,
		id = 101,
		remarks = "威名回收",
		title = "威名回收",
		content = "亲爱的玩家您好，您当前的威名称号为<font color='#01f801'>{0}</font>，今日回收威望值为<font color='#01f801'>{1}</font>，威望值可通过完成威望任务和一些活动中获得。",
	},
	[72] = { 
		xls_id = 72,
		id = 102,
		remarks = "龙珠寻宝未领奖励",
		title = "龙珠寻宝",
		content = "亲爱的玩家您好，您的龙珠寻宝活动中未领取的龙珠奖励，现通过邮件发放给您，请查收！",
	},
	[73] = { 
		xls_id = 73,
		id = 103,
		remarks = "0元购",
		title = "0元购",
		content = "亲爱的玩家您好，这是您参与0元购活动返还的灵符，请查收！",
	},
	[74] = { 
		xls_id = 74,
		id = 104,
		remarks = "限时直购奖励",
		title = "限时直购奖励",
		content = "亲爱的玩家您好，这是您参与{0}元限时直购奖励，请查收！",
	},
	[75] = { 
		xls_id = 75,
		id = 105,
		remarks = "传奇云购",
		title = "传奇云购",
		content = "恭喜你在传奇云购中得幸运大奖，这是你的奖励，请查收",
	},
	[76] = { 
		xls_id = 76,
		id = 106,
		remarks = "寻宝送礼",
		title = "寻宝送礼",
		content = "亲爱的玩家您好，您的寻宝送礼活动中未领取的次数奖励，现通过邮件发放给您，请查收！",
	},
	[77] = { 
		xls_id = 77,
		id = 107,
		remarks = "转盘送礼",
		title = "转盘送礼",
		content = "亲爱的玩家您好，您的转盘送礼活动中未领取的次数奖励，现通过邮件发放给您，请查收！",
	},
	[78] = { 
		xls_id = 78,
		id = 108,
		remarks = "元素圣域排名奖励",
		title = "元素圣域排名奖励",
		content = "亲爱的玩家您好，您这是您参与本次元素圣域积分排名的奖励，请查收！",
	},
	[79] = { 
		xls_id = 79,
		id = 109,
		remarks = "元素圣域积分奖励",
		title = "元素圣域积分奖励",
		content = "亲爱的玩家您好，本周元素圣域积分及奖励已重置，您尚未领取奖励，现通过邮件发放给您，请查收！",
	},
	[80] = { 
		xls_id = 80,
		id = 110,
		remarks = "开服第60天引导",
		title = "元素圣域开启",
		content = "开服第60天开启<font color='#01f801'>元素圣域</font><br>1.副本每周首次通关，将会获得<font color='0x01f801'>首通奖励</font>，可使用<font color='0x01f801'>扫荡</font>再次挑战已通关的副本<br>2.上一层所有副本必须全部通关后，才可继续挑战下一层<br>3.同一层副本，需率先通关青龙、白虎、朱雀、玄武四个副本后，才可挑战麒麟副本<br>4.副本进度<font color='0x01f801'>每周重置一次</font>，排行及排行奖励，积分奖励也同样会重置<br>5.每周日晚22:00<font color='0x01f801'>锁死排名及积分</font>，不允许挑战副本，不再累加积分，直至次日0点<br>6.锁死排名半个小时后，通过邮件发放积分排名奖励；<br>7.未领取的积分奖励，也将通过邮件发放",
	},
	[81] = { 
		xls_id = 81,
		id = 111,
		remarks = "37公测预约邮件",
		title = "公测预约好礼",
		content = "亲爱的玩家您好，您在本平台参加公测预约及邀请等活动的奖励，现通过邮件发放给您，请查收！",
	},
	[82] = { 
		xls_id = 82,
		id = 112,
		remarks = "每周任务",
		title = "每周任务",
		content = "恭喜！你在每周任务活动中累计完成了{0}个任务，获得了如下奖励，请查收",
	},
	[83] = { 
		xls_id = 83,
		id = 113,
		remarks = "镖车奖励",
		title = "镖车奖励",
		content = "亲爱的玩家您好，这是您押镖获取的奖励，请查收！",
	},
	[84] = { 
		xls_id = 84,
		id = 114,
		remarks = "劫镖奖励",
		title = "劫镖奖励",
		content = "亲爱的玩家您好，这是您的劫镖获取的奖励，请查收！每天最多只能劫获3次哦！",
	},
	[85] = { 
		xls_id = 85,
		id = 115,
		remarks = "BOSS首杀奖励",
		title = "BOSS首杀奖励",
		content = "亲爱的玩家您好，这是您的BOSS首杀奖励，请查收！",
	},
	[86] = { 
		xls_id = 86,
		id = 116,
		remarks = "永久回收奖励",
		title = "永久回收奖励",
		content = "亲爱的玩家您好，这是您参与装备回收活动获得的奖励，请查收！",
	},
	[87] = { 
		xls_id = 87,
		id = 117,
		remarks = "装备首爆奖励",
		title = "装备首爆奖励",
		content = "亲爱的玩家您好，您爆出了<font color='#01f801'>{0}</font>，完成了装备首爆活动，请查收奖励！",
	},
	[88] = { 
		xls_id = 88,
		id = 118,
		remarks = "押镖失败",
		title = "押镖失败",
		content = "亲爱的玩家您好，您的镖车被击破或者放弃押镖，剩余奖励请查收！",
	},
	[89] = { 
		xls_id = 89,
		id = 119,
		parameter = 6,
		remarks = "死亡掉落记录",
		title = "死亡掉落记录",
		content = "您于【%s】在【%s（%d：%d）】 被【%s】击败！爆出物品【%s】",
	},
	[90] = { 
		xls_id = 90,
		id = 120,
		remarks = "特权触发",
		title = "特权触发",
		content = "特权护体，恭喜您，本次白金特权触发死亡不掉落装备，真是美滋滋！",
	},
	[91] = { 
		xls_id = 91,
		id = 121,
		parameter = 5,
		remarks = "死亡记录",
		title = "死亡记录",
		content = "您于【%s】在【%s（%d：%d）】 被【%s】击败！",
	},
	[92] = { 
		xls_id = 92,
		id = 122,
		parameter = 9999,
		remarks = "幻兽攻略",
		title = "幻兽攻略",
		boxReward = "1007#1",
		content = "亲爱的玩家：<br>欢迎您来到本游戏，感谢您对本游戏的支持和热爱。<br>幻兽震撼开启，它的特点如下：<br>1.幻兽分为<font color='#01f801'>出战</font>和<font color='#01f801'>合体</font>两个状态，合体后角色获得<font color='#01f801'>刀刀斩杀</font>和<font color='#01f801'>刀刀冰冻</font>神技<br>2.幻兽<font color='#01f801'>3阶</font>后可出战，可以<font color='#01f801'>单挑</font>任何BOSS，帮你打BOSS的不二之选<br>3.幻兽升级只需要花费<font color='#01f801'>灵符</font>，增加幻兽<font color='#01f801'>攻击</font>和<font color='#01f801'>斩杀</font>伤害<br>4.幻兽升到满级可以<font color='#01f801'>100%</font>麻痹BOSS<br><br>满地图都是BOSS，<font color='#01f801'>幻兽</font>可以单挑任何BOSS",
	},
	[93] = { 
		xls_id = 93,
		id = 123,
		parameter = 9999,
		remarks = "快速升级攻略",
		title = "快速升级攻略",
		boxReward = "501#1",
		content = "亲爱的玩家：<br>欢迎您来到本游戏，感谢您对本游戏的支持和热爱。<br>本游戏的升级方式非常特殊<br>1.本游戏没有获得经验值的途径，升级只能靠<font color='#01f801'>等级丹</font>道具升级<br>2.击杀<font color='#01f801'>野外BOSS</font>可以爆出等级丹<br>3.<font color='#01f801'>等级炼制</font>可以在前期快速提升等级<br><br>满地图都是BOSS，<font color='#01f801'>幻兽</font>可以单挑任何BOSS",
	},
	[94] = { 
		xls_id = 94,
		id = 124,
		parameter = 9999,
		remarks = "切割攻略",
		title = "切割攻略",
		boxReward = "1007#1",
		content = "亲爱的玩家：<br>欢迎您来到本游戏，感谢您对本游戏的支持和热爱。<br>切割震撼开启，它的特点如下：<br>1.切割可以对BOSS造成<font color='#01f801'>百分比伤害</font><br>2.切割升级只需要花费<font color='#01f801'>灵符</font><br>3.切割升到满级可以几率秒杀怪物<font color='#01f801'>10%</font>血量上限<br><br>满地图都是BOSS，<font color='#01f801'>幻兽</font>可以单挑任何BOSS",
	},
	[95] = { 
		xls_id = 95,
		id = 125,
		parameter = 9999,
		remarks = "军衔攻略",
		title = "军衔攻略",
		boxReward = "1236#5",
		content = "亲爱的玩家：<br>欢迎您来到本游戏，感谢您对本游戏的支持和热爱。<br>军衔震撼开启，它的特点如下：<br>1.军衔升级可以大幅增加<font color='#01f801'>怪物爆率</font><br>2.军衔升级只需要花费<font color='#01f801'>功勋</font><br>3.功勋可以用<font color='#01f801'>灵符</font>直接兑换获得<br><br>满地图都是BOSS，<font color='#01f801'>幻兽</font>可以单挑任何BOSS",
	},
	[96] = { 
		xls_id = 96,
		id = 126,
		parameter = 9999,
		remarks = "第二大陆攻略",
		title = "第二大陆攻略",
		boxReward = "1007#1",
		content = "亲爱的玩家：<br>欢迎您来到本游戏，感谢您对本游戏的支持和热爱。<br>恭喜你升级到了300级，可以开始征服星辰大海的梦想了：<br>1.300级其实还只是一个<font color='#01f801'>开始</font><br>2.前往寻找NPC传送使者进入<font color='#01f801'>第二大陆</font>，你的征途才是真正的开始<br><br>满地图都是BOSS，<font color='#01f801'>幻兽</font>可以单挑任何BOSS",
	},
	[97] = { 
		xls_id = 97,
		id = 127,
		remarks = "劫镖已上限",
		title = "劫镖奖励",
		content = "亲爱的玩家您好，您的劫镖次数已上限，无法获得奖励！",
	},
	[98] = { 
		xls_id = 98,
		id = 150,
		remarks = "龙神秘宝参与奖励",
		title = "龙神秘宝",
		content = "亲爱的玩家您好，以下是您在龙神秘宝活动中未领取的奖励，请查收。",
	},
	[99] = { 
		xls_id = 99,
		id = 151,
		remarks = "龙神秘宝持有奖励",
		title = "龙神秘宝",
		content = "以下是你在龙神秘宝中获得的夺宝奖励，请查收！",
	},
	[100] = { 
		xls_id = 100,
		id = 152,
		remarks = "摆摊退还邮件",
		title = "摆摊退还",
		content = "以下是你在摆摊中的物品，摊位已收起，请查收！",
	},
	[101] = { 
		xls_id = 101,
		id = 153,
		remarks = "摆摊收益邮件",
		title = "摆摊收益",
		content = "<font color='#01f801'>{0}</font>已被其他玩家购买，以下是你在摆摊中获得的收益，请查收！",
	},
	[102] = { 
		xls_id = 102,
		id = 154,
		remarks = "比奇积分奖励",
		title = "热血乱斗场积分奖励",
		content = "亲爱的玩家您好，这是在热血乱斗场活动中未领取的奖励，请查收。",
	},
	[103] = { 
		xls_id = 103,
		id = 164,
		remarks = "炎魔神狱奖励",
		title = "炎魔神狱奖励",
		content = "亲爱的玩家您好，您领取了炎魔神狱{0}的奖励，请您查收。",
	},
	[104] = { 
		xls_id = 104,
		id = 165,
		remarks = "背包满时通过邮件发送奖励",
		title = "背包已满",
		content = "亲爱的玩家您好，您的背包已满无法获得奖励，奖励通过邮件的形式发放！",
	},
	[105] = { 
		xls_id = 105,
		id = 166,
		remarks = "摆摊退还",
		title = "摆摊退还",
		content = "亲爱的玩家您好，您在摆摊中的物品已被售空，所以并无物品返还。",
	},
	[106] = { 
		xls_id = 106,
		id = 167,
		remarks = "触发装备投保",
		title = "触发装备投保",
		content = "亲爱的玩家您好，您因为死亡触发了装备<font color='#01f801'>{0}</font>的保险，该装备保险次数消耗<font color='#01f801'>1</font>次！",
	},
	[107] = { 
		xls_id = 107,
		id = 168,
		remarks = "500万悬赏奖励",
		title = "500万悬赏奖励",
		content = "亲爱的玩家您好，这是在500万悬赏活动中未领取的奖励，请查收。",
	},
	[108] = { 
		xls_id = 108,
		id = 169,
		remarks = "三日封神奖励",
		title = "三日封神奖励",
		content = "亲爱的玩家您好，这是在三日封神活动中未领取的奖励，请查收。",
	},
	[109] = { 
		xls_id = 109,
		id = 170,
		remarks = "合服狂欢奖励",
		title = "合服狂欢奖励",
		content = "亲爱的玩家您好，这是在合服狂欢活动中未领取的奖励，请查收。",
	},
	[110] = { 
		xls_id = 110,
		id = 172,
		remarks = "背包满时通过邮件发送奖励",
		title = "背包已满",
		content = "亲爱的玩家您好，您的背包已满，这是您在仙灵宝藏中探险所得，请及时领取！",
	},
	[111] = { 
		xls_id = 111,
		id = 173,
		remarks = "身份验证奖励",
		title = "身份验证奖励",
		content = "身份验证奖励",
	},
	[112] = { 
		xls_id = 112,
		id = 174,
		remarks = "激活码奖励",
		title = "激活码奖励",
		content = "这是您激活码所兑换的奖励，敬请查收！",
	},
	[113] = { 
		xls_id = 113,
		id = 175,
		remarks = "决战海岛胜方",
		title = "决战海岛胜方",
		content = "恭喜！您在跨服决战-决战海岛中获得胜利，获得<font color='#01f801'>10000</font>声望奖励，声望可在声望商城兑换稀有道具！",
	},
	[114] = { 
		xls_id = 114,
		id = 176,
		remarks = "决战海岛败方",
		title = "决战海岛败方",
		content = "很遗憾！您在跨服决战-决战海岛中对抗失败，获得<font color='#01f801'>5000</font>声望奖励，声望可在声望商城兑换稀有道具，请再接再厉！",
	},
	[115] = { 
		xls_id = 115,
		id = 177,
		remarks = "决战海岛消极比赛",
		title = "决战海岛消极比赛",
		content = "非常抱歉！您在跨服决战-决战海岛中贡献积分不足20，被判定为消极比赛，无法获得结算声望奖励，下次请努力！",
	},
	[116] = { 
		xls_id = 116,
		id = 178,
		remarks = "王者争霸赛季奖励",
		title = "王者争霸赛季奖励",
		content = "亲爱的玩家您好，您在王者争霸本赛季结算时荣登<font color='#01f801'>{0}</font>段位，特为您发放奖励，请查收！",
	},
	[117] = { 
		xls_id = 117,
		id = 179,
		remarks = "王者争霸每日奖励",
		title = "王者争霸每日奖励",
		content = "亲爱的玩家您好，今日您在王者争霸中位于<font color='#01f801'>{0}</font>段位，特为您发放奖励，请查收！",
	},
	[118] = { 
		xls_id = 118,
		id = 180,
		remarks = "王者争霸排名奖励",
		title = "王者争霸排名奖励",
		content = "亲爱的玩家您好，您本赛季王者争霸的最终排名为<font color='#01f801'>第{0}名</font>，特为您发放奖励，请查收！",
	},
	[119] = { 
		xls_id = 119,
		id = 181,
		remarks = "双倍重置卡",
		title = "双倍充值重置",
		content = "亲爱的玩家您好，您的双倍充值额度已重置，以下是您未领取的元宝，请查收",
	},
	[120] = { 
		xls_id = 120,
		id = 182,
		remarks = "勇者峡谷胜方",
		title = "勇者峡谷胜方",
		content = "恭喜！您在勇者峡谷中获得胜利，获得<font color='#01f801'>大量</font>荣誉值奖励等奖励，荣誉值可在荣誉商城兑换稀有道具！",
	},
	[121] = { 
		xls_id = 121,
		id = 183,
		remarks = "勇者峡谷败方",
		title = "勇者峡谷败方",
		content = "很遗憾！您在勇者峡谷中对抗失败，获得<font color='#01f801'>少量</font>荣誉值奖励等奖励，荣誉值可在荣誉商城兑换稀有道具，请再接再厉！",
	},
	[122] = { 
		xls_id = 122,
		id = 184,
		remarks = "勇者峡谷个人奖励",
		title = "勇者峡谷个人奖励",
		content = "您在跨服远征-勇者峡谷中积分排名第<font color='#01f801'>{0}</font>，特为您发放奖励，请查收！",
	},
	[123] = { 
		xls_id = 123,
		id = 185,
		remarks = "同盟解散",
		title = "同盟解散",
		content = "你所在的同盟已解散",
	},
	[124] = { 
		xls_id = 124,
		id = 186,
		remarks = "踢出同盟",
		title = "踢出同盟",
		content = "同盟成员<font color='#01f801'>{0}</font>已经被踢出同盟",
	},
	[125] = { 
		xls_id = 125,
		id = 187,
		remarks = "解除同盟",
		title = "解除同盟",
		content = "同盟成员<font color='#01f801'>{0}</font>的帮主主动解除同盟关系",
	},
	[126] = { 
		xls_id = 126,
		id = 188,
		remarks = "申请同盟",
		title = "申请同盟",
		content = "<font color='#01f801'>{0}</font>申请加入同盟，望盟主同意",
	},
	[127] = { 
		xls_id = 127,
		id = 189,
		remarks = "决战沙巴克帮主奖励",
		title = "决战沙巴克帮主奖励",
		content = "恭喜贵盟占领沙城，是帮主额外奖励如下，元宝奖励，<font color='#53b436'>称号</font>奖励已为你自动激活。请查收。",
	},
	[128] = { 
		xls_id = 128,
		id = 190,
		remarks = "决战沙巴克行会排名",
		title = "决战沙巴克行会排名",
		content = "贵帮在沙城争霸活动中取得胜利，恭喜贵帮排名第{0}，以下是贵帮的排名奖励，请查收。",
	},
	[129] = { 
		xls_id = 129,
		id = 191,
		remarks = "决战沙巴克个人排名",
		title = "决战沙巴克个人排名",
		content = "您在沙城争霸活动中，排名第{0}，以下是您的排名奖励，请查收。",
	},
	[130] = { 
		xls_id = 130,
		id = 192,
		remarks = "决战沙巴克积分奖励",
		title = "决战沙巴克积分奖励",
		content = "您在沙城争霸活动中尚有积分达标奖励未被领取，请领取。",
	},
	[131] = { 
		xls_id = 131,
		id = 193,
		remarks = "决战沙巴克安慰奖",
		title = "决战沙巴克安慰奖",
		content = "贵帮在决战沙巴克活动中，与胜利失之交臂，以下是贵帮的<font color='#53b436'>安慰奖</font>，请查收。",
	},
	[132] = { 
		xls_id = 132,
		id = 194,
		remarks = "会员到期邮件",
		title = "会员过期",
		content = "亲爱的玩家您好，您的<font color='#01f801'>{0}会员</font>已到期，享有的相关特权被取消。",
	},
	[133] = { 
		xls_id = 133,
		id = 195,
		remarks = "跨服帮战霸主奖励",
		title = "决战沙巴克霸主奖励",
		content = "恭喜贵帮占领皇宫，成为群雄霸主，以下是为恭喜霸主的奖励，请查收！",
	},
	[134] = { 
		xls_id = 134,
		id = 196,
		remarks = "跨服帮战行会排名，成员奖励",
		title = "决战沙巴克行会奖励",
		content = "贵帮在决战沙巴克活动中，积分排名第{0}，以下是贵帮的排名奖励，请查收。",
	},
	[135] = { 
		xls_id = 135,
		id = 197,
		remarks = "跨服帮战行会内个人排名",
		title = "决战沙巴克个人奖励",
		content = "您在决战沙巴克活动中，获得了{0}积分，在活动内排名第{1}，以下是您的排名奖励，请查收。",
	},
	[136] = { 
		xls_id = 136,
		id = 198,
		remarks = "跨服帮战个人积分达标奖励",
		title = "决战沙巴克积分奖励",
		content = "您在决战沙巴克活动中尚有积分达标奖励未被领取，请领取。",
	},
	[137] = { 
		xls_id = 137,
		id = 199,
		remarks = "跨服帮战匹配失败",
		title = "决战沙巴克匹配失败",
		boxReward = "41#1000000&679#5",
		content = "贵帮在决战沙巴克活动中<font color='#01f801'>没有匹配到旗鼓相当的对手</font>，还望贵帮不要气馁，抓紧提升实力，占领皇宫，夺取元宝！",
	},
	[138] = { 
		xls_id = 138,
		id = 200,
		remarks = "护送奖励（双倍）",
		title = "护送奖励",
		content = "亲爱的玩家您好，<font color='#01f801'>因在双倍期间接取跟护送</font>，这是您护送成功的双倍奖励，请查收！",
	},
	[139] = { 
		xls_id = 139,
		id = 201,
		remarks = "劫镖奖励",
		title = "劫镖奖励",
		content = "亲爱的玩家您好，这是您的劫镖获取的奖励，请查收！每天最多只能劫获4次哦！",
	},
	[140] = { 
		xls_id = 140,
		id = 202,
		remarks = "护送失败（双倍）",
		title = "护送失败",
		content = "亲爱的玩家您好，您的灵鲲被击破或者放弃护送，<font color='#01f801'>因在双倍期间接取</font>，你获取的奖励双倍，请查收！",
	},
	[141] = { 
		xls_id = 141,
		id = 203,
		remarks = "劫镖已上限",
		title = "劫镖奖励",
		content = "亲爱的玩家您好，您的劫镖次数已上限，无法获得奖励！",
	},
	[142] = { 
		xls_id = 142,
		id = 204,
		remarks = "跨服帮战帮主排名奖励",
		title = "群雄逐鹿帮主奖励",
		content = "恭喜贵帮再群雄逐鹿活动中，获得了第{0}名，以下是帮主的激励奖励，请查收！",
	},
	[143] = { 
		xls_id = 143,
		id = 205,
		remarks = "群雄逐鹿匹配成功",
		title = "群雄逐鹿匹配成功",
		content = "恭喜贵帮在群雄逐鹿活动中匹配到<font color='#01f801'>旗鼓相当</font>的对手，望贵帮在活动中<font color='#01f801'>大杀四方，夺取豪华奖励！</font>",
	},
	[144] = { 
		xls_id = 144,
		id = 206,
		remarks = "群雄逐鹿可以报名",
		title = "群雄逐鹿报名开启",
		content = {
			[1] = "一周一次的<font color='#01f801'>群雄逐鹿</font>活动开启啦，<font color='#01f801'>豪华奖励</font>在等着你！快去拉上兄弟叫<font color='#01f801'>帮主或副帮主</font>报名吧！<br><font color='#01f801'>合服后请重新报名哦！</font><br><font color='#01f801'><u><a href='event:open",
			[2] = 318,
			[3] = 1,
			[4] = "3'>快速报名！</a></u></font>",
		},
	},
	[145] = { 
		xls_id = 145,
		id = 207,
		remarks = "购买成功",
		title = "购买成功",
		content = "恭喜你在拍卖行中成功的以<font color='#01f801'>{0}{1}</font>购买了<font color='#01f801'>{2}</font>，请及时领取购入物品",
	},
	[146] = { 
		xls_id = 146,
		id = 208,
		remarks = "出售成功",
		title = "出售成功",
		content = "恭喜你在拍卖行中成功的以<font color='#01f801'>{0}{1}</font>售出了<font color='#01f801'>{2}</font>，税率扣除<font color='#01f801'>{3}{1}</font>，请及时领取拍卖收益",
	},
	[147] = { 
		xls_id = 147,
		id = 209,
		remarks = "拍品流拍",
		title = "拍品流拍",
		content = "您上架的<font color='#01f801'>{0}</font>无人购买，请在邮件中取回",
	},
	[148] = { 
		xls_id = 148,
		id = 210,
		remarks = "行会拍品结算",
		title = "行会拍品结算",
		content = "您的行会在行会活动中获得的<font color='#01f801'>{0}</font>在世界拍卖中售出了<font color='#01f801'>{1}{2}</font>，由您获得了共计<font color='#01f801'>{3}{4}</font>的收益，请及时领取",
	},
	[149] = { 
		xls_id = 149,
		id = 211,
		remarks = "行会拍品结算",
		title = "行会拍品结算",
		content = "您的行会在行会活动中获得的<font color='#01f801'>{0}</font>在行会拍卖中售出了<font color='#01f801'>{1}{2}</font>，由您获得了共计<font color='#01f801'>{3}{4}</font>的收益，请及时领取",
	},
	[150] = { 
		xls_id = 150,
		id = 212,
		remarks = "行会拍品结算",
		title = "行会拍品结算",
		content = "您的行会在行会活动中获得的<font color='#01f801'>{0}</font>等<font color='#01f801'>{1}</font>件拍品在世界拍卖中售出了<font color='#01f801'>{2}{3}</font>，由您获得了共计<font color='#01f801'>{4}{5}</font>的收益，请及时领取",
	},
	[151] = { 
		xls_id = 151,
		id = 213,
		remarks = "行会拍品结算",
		title = "行会拍品结算",
		content = "您的行会在行会活动中获得的<font color='#01f801'>{0}</font>等<font color='#01f801'>{1}</font>件拍品在行会拍卖中售出了<font color='#01f801'>{2}{3}</font>，由您获得了共计<font color='#01f801'>{4}{5}</font>的收益，请及时领取",
	},
	[152] = { 
		xls_id = 152,
		id = 216,
		remarks = "第三方软件预警",
		title = "第三方软件预警",
		content = "亲爱的玩家，系统检测到您有使用第三方软件，影响了游戏平衡，当前给与预警，希望后续不再使用第三方软件，否则将会采取关禁闭的方式处理！",
	},
	[153] = { 
		xls_id = 153,
		id = 217,
		remarks = "护送奖励（单倍）",
		title = "护送奖励",
		content = "亲爱的玩家您好，<font color='#01f801'>因未在双倍期间接取跟护送</font>，这是您护送成功的单倍奖励，请查收！",
	},
	[154] = { 
		xls_id = 154,
		id = 218,
		remarks = "护送失败（单倍）",
		title = "护送失败",
		content = "亲爱的玩家您好，您的灵鲲被击破或者放弃护送，<font color='#01f801'>因未在双倍活动期间内接取或护送</font>，这是您获得的单倍奖励！",
	},
	[155] = { 
		xls_id = 155,
		id = 219,
		remarks = "返利属性，绑定灵符",
		title = "充值额外奖励",
		content = "亲爱的玩家您好，根据您当前<font color='#01f801'>充值奖励</font>特殊属性，本次充值您额外获得了<font color='#01f801'>{0}灵符</font>，请查收！",
	},
	[156] = { 
		xls_id = 156,
		id = 220,
		remarks = "拍卖物品竞价后被买走",
		title = "参与拍卖物品被买走",
		content = "您对{0}的竞拍价已被买走，已返还竞拍的{1}积分",
	},
	[157] = { 
		xls_id = 157,
		id = 221,
		remarks = "拍卖物品竞价后被超过",
		title = "拍卖物品竞价被超过",
		content = "您对{0}的竞拍价被超过，已返还竞拍的{1}积分",
	},
	[158] = { 
		xls_id = 158,
		id = 222,
		remarks = "报名奖励",
		title = "天下第一报名奖励",
		boxReward = "105107#1",
		content = "成功报名天下第一争霸赛，这是报名奖励，请查收！",
	},
	[159] = { 
		xls_id = 159,
		id = 223,
		remarks = "16强奖励",
		title = "天下第一16强奖励",
		content = "恭喜您在天下第一争霸赛中成功位列16强，请再接再厉，这是您的奖励，请查收！",
	},
	[160] = { 
		xls_id = 160,
		id = 224,
		remarks = "8强奖励",
		title = "天下第一8强奖励",
		content = "恭喜您在天下第一争霸赛中成功位列8强，请再接再厉，这是您的奖励，请查收！",
	},
	[161] = { 
		xls_id = 161,
		id = 225,
		remarks = "4强奖励",
		title = "天下第一4强奖励",
		content = "恭喜您在天下第一争霸赛中成功位列4强，请再接再厉，这是您的奖励，请查收！",
	},
	[162] = { 
		xls_id = 162,
		id = 226,
		remarks = "亚军奖励",
		title = "天下第一亚军奖励",
		content = "恭喜您在天下第一争霸赛中成功夺得亚军，请不要气馁，您距离冠军只有一步之遥，请继续努力，这是您的奖励，请查收！",
	},
	[163] = { 
		xls_id = 163,
		id = 227,
		remarks = "冠军奖励",
		title = "天下第一冠军奖励",
		content = "恭喜您在天下第一争霸赛中成功夺得冠军，称霸真龙，非你莫属，这是您的奖励，请查收！",
	},
	[164] = { 
		xls_id = 164,
		id = 228,
		remarks = "二级锁重置邮件",
		title = "二级密码已重置",
		content = "亲爱的用户，您的二级密码已重置，快去设置新的密码吧！",
	},
	[165] = { 
		xls_id = 165,
		id = 229,
		remarks = "挖矿奖励",
		title = "比奇矿洞",
		content = "亲爱的玩家您好，这是您在比奇矿洞中的收获，请查收！",
	},
	[166] = { 
		xls_id = 166,
		id = 230,
		remarks = "行会首领参与奖励",
		title = "行会首领",
		content = "亲爱的玩家您好，这是您在行会首领活动中的挑战奖励，请查收！",
	},
	[167] = { 
		xls_id = 167,
		id = 231,
		remarks = "参与胜利奖励",
		title = "天下第一争霸赛冒泡赛参与奖励",
		content = "感谢参与天下第一活动，请继续努力，这是您的奖励，请查收！",
	},
	[168] = { 
		xls_id = 168,
		id = 232,
		remarks = "参与失败奖励",
		title = "天下第一争霸赛冒泡赛参与奖励",
		content = "感谢参与天下第一活动，请不要气馁，这是您的奖励，请查收！",
	},
	[169] = { 
		xls_id = 169,
		id = 233,
		remarks = "天下第一争霸赛菠菜胜利邮件",
		title = "天下第一争霸赛菠菜胜利邮件",
		content = "天下第一争霸赛菠菜胜利邮件",
	},
	[170] = { 
		xls_id = 170,
		id = 234,
		remarks = "被掠夺日志",
		title = "比奇矿洞",
		content = "亲爱的玩家您好，您的矿被<font color='#01f801'>{0}</font>掠夺了，赶紧召唤小伙伴去夺回吧！",
	},
	[171] = { 
		xls_id = 171,
		id = 235,
		remarks = "老玩家回归",
		title = "老玩家回归",
		boxReward = "41#1000000",
		content = "亲爱的老玩家你好，你离开这片大陆已经很长时间了，快拿起宝刀为兄弟奋战吧，感谢你的回归，以下是你的回归福利，请查收！",
	},
	[172] = { 
		xls_id = 172,
		id = 236,
		remarks = "名人堂结束提示",
		title = "名人堂结算提示",
		content = "名人堂将在<font color='#01f801'>今天23:30分</font>开始结算，为期30分钟，结算期间将不再更新数据。当前距离结算还剩<font color='#01f801'>{0}小时</font>，敬请知晓",
	},
	[173] = { 
		xls_id = 173,
		id = 237,
		remarks = "答题排名邮件",
		title = "答题排名邮件",
		content = "您的行会在活动中排名第{0}，以下是您的奖励",
	},
	[174] = { 
		xls_id = 174,
		id = 238,
		remarks = "青铜会员奖励",
		title = "青铜会员",
		content = "亲爱青铜会员用户您好，这是您今日的特权礼包，请查收！",
	},
	[175] = { 
		xls_id = 175,
		id = 239,
		remarks = "白银会员",
		title = "白银会员",
		content = "亲爱白银会员用户您好，这是您今日的特权礼包，请查收！",
	},
	[176] = { 
		xls_id = 176,
		id = 240,
		remarks = "黄金会员",
		title = "黄金会员",
		content = "亲爱黄金会员用户您好，这是您今日的特权礼包，请查收！",
	},
	[177] = { 
		xls_id = 177,
		id = 241,
		remarks = "首充档位奖励",
		title = "首充档位奖励",
		content = "感谢您的充值，以下是您的奖励，请查收",
	},
	[178] = { 
		xls_id = 178,
		id = 242,
		remarks = "星装返还邮件",
		title = "星装返还邮件",
		content = "这是您的星装",
	},
	[179] = { 
		xls_id = 179,
		id = 243,
		remarks = "金币邮件",
		title = "金币邮件",
		content = "这是您的金币",
	},
	[180] = { 
		xls_id = 180,
		id = 244,
		remarks = "鲜花榜结算",
		title = "侠义榜结算",
		content = "侠义榜又刷新啦，你上周的排名为第{0}名，这是您的奖励，请查收！",
	},
	[181] = { 
		xls_id = 181,
		id = 259,
		remarks = "桃园秘境遗漏奖励",
		title = "桃园秘境奖励",
		content = "这是您活动遗漏的个人积分奖励，敬请查收！",
	},
	[182] = { 
		xls_id = 182,
		id = 262,
		remarks = "超值豪礼倒计时",
		title = "超值豪礼倒计时",
		content = "亲爱的玩家你好，你的<font color='#01f801'>{0}</font>活动将在<font color='#01f801'>24小时</font>后到期，若有未领取的奖励请及时领取哦！",
	},
	[183] = { 
		xls_id = 183,
		id = 263,
		remarks = "一折礼包返还",
		title = "免费礼包返还",
		content = "亲爱的玩家你好，由于你参加了<font color='#01f801'>免费礼包</font>活动，特此为您全额返还消耗，以及额外礼包奖励，请查收。",
	},
	[184] = { 
		xls_id = 184,
		id = 264,
		remarks = "沙城成员奖励",
		title = "沙城成员奖励",
		content = "恭喜贵帮占领沙城，以下是为恭喜你获得如下奖励，现在为您发放<font color='#53b436'>嘉奖奖励</font>，请查收！",
	},
	[185] = { 
		xls_id = 185,
		id = 265,
		remarks = "沙捐奖励",
		title = "沙捐奖励",
		content = "恭喜贵帮占领沙城，以下是为您发放的沙捐奖池平分奖励，请查收！",
	},
	[186] = { 
		xls_id = 186,
		id = 1001,
		remarks = "系统",
		title = "致所有亲爱的朋友",
		content = "欢迎我的老朋友，<br><br><font color='#ffe4c7'>无兄弟不传奇</font>!",
	},
	[187] = { 
		xls_id = 187,
		id = 300,
		remarks = "系统",
		title = "【尸王争夺战】",
		content = "尊敬的玩家：<br>恭喜您在<p><font colorStyleID='1010007'>【尸王争夺战】</font>夺得“<font colorStyleID='1010007'>无字天书</font>”！<br>以下是您应得的奖励，请查收。",
	},
	[188] = { 
		xls_id = 188,
		id = 301,
		remarks = "系统",
		title = "【尸王争夺战】",
		boxReward = "3000311#2",
		content = "尊敬的玩家：<br>以下是您参与<p><font colorStyleID='1010007'>【尸王争夺战】</font>活动的奖励！<br>请查收",
	},
	[189] = { 
		xls_id = 189,
		id = 302,
		remarks = "系统",
		title = "【世界BOSS】",
		content = "尊敬的玩家：<br>以下是您参与<p><font colorStyleID='1010007'>【世界BOSS】</font>活动对BOSS的伤害奖励！<br>请查收",
	},
	[190] = { 
		xls_id = 190,
		id = 303,
		remarks = "系统",
		title = "【世界BOSS】",
		content = "尊敬的玩家：<br>以下是您参与<p><font colorStyleID='1010007'>【世界BOSS】</font>活动击杀了世界BOSS！<br>请查收",
	},
	[191] = { 
		xls_id = 191,
		id = 304,
		remarks = "系统",
		title = "【世界BOSS】",
		content = "尊敬的玩家：<br>以下是您参与<p><font colorStyleID='1010007'>【世界BOSS】</font>活动对BOSS的伤害排名奖励！<br>请查收",
	},
	[192] = { 
		xls_id = 192,
		id = 305,
		remarks = "系统",
		title = "【神威狱】",
		content = "尊敬的玩家：<br>以下是您参与<p><font colorStyleID='1010007'>【神威狱】</font>活动的奖励！<br>请查收",
	},
	[193] = { 
		xls_id = 193,
		id = 306,
		remarks = "系统",
		title = "【逆魔古阵】",
		content = "尊敬的玩家：<br>以下是您参与<p><font colorStyleID='1010007'>【逆魔古阵】</font>活动的奖励！<br>请查收",
	},
	[194] = { 
		xls_id = 194,
		id = 307,
		remarks = "系统",
		title = "【热血乱斗场】",
		content = "尊敬的玩家：<br>以下是您参与<p><font colorStyleID='1010007'>【热血乱斗场】</font>活动的积分排名奖励！<br>请查收",
	},
	[195] = { 
		xls_id = 195,
		id = 308,
		remarks = "系统",
		title = "【热血乱斗场】",
		content = "尊敬的玩家：<br>以下是您参与<p><font colorStyleID='1010007'>【热血乱斗场】</font>活动的奖励！<br>请查收",
	},
	[196] = { 
		xls_id = 196,
		id = 309,
		remarks = "系统",
		title = "【行会地宫】",
		content = "尊敬的玩家：<br>以下是您参与<p><font colorStyleID='1010007'>【行会地宫】</font>活动的奖励！<br>请查收",
	},
	[197] = { 
		xls_id = 197,
		id = 310,
		remarks = "系统",
		title = "背包已满",
		content = "尊敬的玩家，您的背包已满，现将获得的奖励暂存在邮箱中，请及时领取！",
	},
	[198] = { 
		xls_id = 198,
		id = 311,
		remarks = "系统",
		title = "出售成功",
		content = "尊敬的玩家，您上架的【%s】出售成功！成交价：%s，交易税：%s",
	},
	[199] = { 
		xls_id = 199,
		id = 312,
		remarks = "系统",
		title = "排行榜",
		content = "尊敬的玩家，恭喜您成为【战神排行榜第一名】，可喜可贺！",
	},
	[200] = { 
		xls_id = 200,
		id = 313,
		remarks = "系统",
		title = "排行榜",
		content = "尊敬的玩家，恭喜您成为【法圣排行榜第一名】，可喜可贺！",
	},
	[201] = { 
		xls_id = 201,
		id = 314,
		remarks = "系统",
		title = "排行榜",
		content = "尊敬的玩家，恭喜您成为【道尊排行榜第一名】，可喜可贺！",
	},
	[202] = { 
		xls_id = 202,
		id = 315,
		remarks = "系统",
		title = "魔龙主城",
		content = "尊敬的勇士，<font color='#ffe4c7'>【魔龙主城】</font>已对全区玩家开启<br><br>    开放内容如下<br><font color='#ffe4c7'>疗伤圣石</font>：野外PK、挂机 再也不用带药水了<br><font color='#ffe4c7'>魔龙套装</font>：经典炫酷外形，带你重温经典<br>",
	},
	[203] = { 
		xls_id = 203,
		id = 316,
		remarks = "系统",
		title = "石原主城",
		content = "尊敬的勇士，<font color='#ffe4c7'>【石原主城】</font>已对全区玩家开启<br><br>    开放内容如下<br> <font color='#ffe4c7'>疗伤圣石</font>：野外PK、挂机 再也不用带药水了<br><font color='#ffe4c7'>魔龙套装</font>：经典炫酷外形，带你重温经典<br>",
	},
	[204] = { 
		xls_id = 204,
		id = 317,
		remarks = "系统",
		title = "【等级冲榜】",
		content = "尊敬的勇士：<br>恭喜您在<font colorStyleID='1010007'>【等级冲榜】</font>中排名第<font color='#ffe4c7'>%d</font>名，可喜可贺！以下是活动的奖励！<br>请查收",
	},
	[205] = { 
		xls_id = 205,
		id = 318,
		remarks = "系统",
		title = "【神之玉佩】",
		content = "尊敬的勇士：<br>恭喜您在<font colorStyleID='1010007'>【神之玉佩】</font>中排名第<font color='#ffe4c7'>%d</font>名，可喜可贺！以下是活动的奖励！<br>请查收",
	},
	[206] = { 
		xls_id = 206,
		id = 319,
		remarks = "系统",
		title = "石原主城",
		content = "尊敬的勇士，<font color='#ffe4c7'>【石原主城】</font>已对全区玩家开启<br><br>    开放内容如下<br> <font color='#ffe4c7'>疗伤圣石</font>：野外PK、挂机 再也不用带药水了<br><font color='#ffe4c7'>魔龙套装</font>：经典炫酷外形，带你重温经典<br>",
	},
	[207] = { 
		xls_id = 207,
		id = 320,
		remarks = "系统",
		title = "石原主城",
		content = "尊敬的勇士，<font color='#ffe4c7'>【石原主城】</font>已对全区玩家开启<br><br>    开放内容如下<br> <font color='#ffe4c7'>疗伤圣石</font>：野外PK、挂机 再也不用带药水了<br><font color='#ffe4c7'>魔龙套装</font>：经典炫酷外形，带你重温经典<br>",
	},
	[208] = { 
		xls_id = 208,
		id = 321,
		remarks = "系统",
		title = "石原主城",
		content = "尊敬的勇士，<font color='#ffe4c7'>【石原主城】</font>已对全区玩家开启<br><br>    开放内容如下<br> <font color='#ffe4c7'>疗伤圣石</font>：野外PK、挂机 再也不用带药水了<br><font color='#ffe4c7'>魔龙套装</font>：经典炫酷外形，带你重温经典<br>",
	},
	[209] = { 
		xls_id = 209,
		id = 322,
		remarks = "系统",
		title = "【行会首领】",
		content = "尊敬的勇士：<br>鉴于您在【行会首领】活动中的出色表现，向您发放参与奖励！<br>请查收",
	},
	[210] = { 
		xls_id = 210,
		id = 323,
		remarks = "系统",
		title = "【行会首领】",
		content = "尊敬的勇士：<br>您在【行会首领】活动中的表现卓越，本行会中您的伤害量排在第%s位，以下是排名奖励！<br>请查收",
	},
	[211] = { 
		xls_id = 211,
		id = 324,
		remarks = "系统",
		title = "【竞拍返还】",
		content = "尊敬的勇士：<br>您参与竞拍的%s价格被超过，请领取返还的竞拍花费！<br>请查收",
	},
	[212] = { 
		xls_id = 212,
		id = 325,
		remarks = "系统",
		title = "【竞拍成功】",
		content = "尊敬的勇士：<br>恭喜您成功竞拍%s！请前往“我的竞拍”界面领取！",
	},
	[213] = { 
		xls_id = 213,
		id = 326,
		remarks = "系统",
		title = "【签到奖励】",
		content = "尊敬的勇士：<br>以下是您忘记领取的签到奖励！<br>请查收",
	},
	[214] = { 
		xls_id = 214,
		id = 327,
		remarks = "系统",
		title = "【拍卖成功】",
		content = "尊敬的勇士：<br>恭喜您成功出售%s，请领取拍卖收入！",
	},
	[215] = { 
		xls_id = 215,
		id = 328,
		remarks = "系统",
		title = "【拍卖流拍】",
		content = "尊敬的勇士：<br>您出售的%s流拍，请前往“我的上架”查看！",
	},
	[216] = { 
		xls_id = 216,
		id = 329,
		remarks = "系统",
		title = "【拍卖下架】",
		content = "尊敬的勇士：<br>您竞拍的%s已下架，请领取返还的竞拍花费！<br>请查收",
	},
	[217] = { 
		xls_id = 217,
		id = 330,
		remarks = "系统",
		title = "【行会分红】",
		content = "尊敬的勇士：<br>%s成功拍出，请领取拍卖分红！<br>请查收",
	},
	[218] = { 
		xls_id = 218,
		id = 331,
		remarks = "系统",
		title = "【功能开启】",
		content = "尊敬的勇士：<br>今天是开服<font colorStyleID='1010007'>第%s天</font>，活动<font colorStyleID='1010007'>【押运镖车】</font>已全面开放:<br>您接取镖车并成功护送到目标地点，即可获取<font colorStyleID='1010007'>海量经验</font>及<font colorStyleID='1010007'>金币奖励</font>。（小心途中意图袭击劫取镖车的敌人！）",
	},
	[219] = { 
		xls_id = 219,
		id = 332,
		remarks = "系统",
		title = "【功能开启】",
		content = "尊敬的勇士：<br>今天是开服<font colorStyleID='1010007'>第%s天</font>，活动<font colorStyleID='1010007'>【押运镖车】</font>已全面开放:<br>您接取镖车并成功护送到目标地点，即可获取<font colorStyleID='1010007'>海量经验</font>及<font colorStyleID='1010007'>金币奖励</font>。（小心途中意图袭击劫取镖车的敌人！）",
	},
	[220] = { 
		xls_id = 220,
		id = 333,
		remarks = "系统",
		title = "【功能开启】",
		content = "尊敬的勇士：<br>今天是开服<font colorStyleID='1010007'>第%s天</font>，活动<font colorStyleID='1010007'>【押运镖车】</font>已全面开放:<br>您接取镖车并成功护送到目标地点，即可获取<font colorStyleID='1010007'>海量经验</font>及<font colorStyleID='1010007'>金币奖励</font>。（小心途中意图袭击劫取镖车的敌人！）",
	},
	[221] = { 
		xls_id = 221,
		id = 334,
		remarks = "系统",
		title = "【功能开启】",
		content = "尊敬的勇士：<br>今天是开服<font colorStyleID='1010007'>第%s天</font>，活动<font colorStyleID='1010007'>【押运镖车】</font>已全面开放:<br>您接取镖车并成功护送到目标地点，即可获取<font colorStyleID='1010007'>海量经验</font>及<font colorStyleID='1010007'>金币奖励</font>。（小心途中意图袭击劫取镖车的敌人！）",
	},
	[222] = { 
		xls_id = 222,
		id = 335,
		remarks = "系统",
		title = "【礼包累充】",
		content = "尊敬的勇士：<br>您的累充礼包奖励尚未领取！<br>请查收",
	},
	[223] = { 
		xls_id = 223,
		id = 336,
		remarks = "系统",
		title = "【沙巴克】",
		content = "尊敬的勇士：恭喜你在沙巴克攻城活动中，奋勇杀敌，坚韧不屈，成功赢取了%s点积分，排名第%s。现向您发放嘉奖奖励！",
	},
	[224] = { 
		xls_id = 224,
		id = 337,
		remarks = "系统",
		title = "【群英汇】",
		content = "恭喜！在群英汇活动中答题正确，奖励已下发至背包，请注意查收！",
	},
	[225] = { 
		xls_id = 225,
		id = 338,
		remarks = "系统",
		title = "【群英汇】",
		content = "恭喜！您的行会在群英汇活动中排名第%s，好似文曲星组团下凡，可喜可贺！",
	},
	[226] = { 
		xls_id = 226,
		id = 339,
		remarks = "系统",
		title = "【道具掉落】",
		content = "尊敬的玩家，您在【<font color='#4FE21B'>%s</font>】被【<font color='#4FE21B'>%s</font>】击杀了，很不幸，您的【<font color='#ff0500'>%s</font>】掉落了",
	},
	[227] = { 
		xls_id = 227,
		id = 340,
		remarks = "系统",
		title = "【道具掉落】",
		content = "尊敬的玩家，您在【<font color='#4FE21B'>%s</font>】被击杀了，很不幸，您的【<font color='#ff0500'>%s</font>】掉落了",
	},
	[228] = { 
		xls_id = 228,
		id = 341,
		remarks = "系统",
		title = "【会长弹劾】",
		content = "尊敬的玩家，由于会长【<font color='#4FE21B'>{0}</font>】长期未登录<br>现在会长转移给了行会成员【<font color='#4FE21B'>{1}</font>】",
	},
	[229] = { 
		xls_id = 229,
		id = 342,
		remarks = "系统",
		title = "【行会】",
		content = "尊敬的玩家，您被踢出了【<font color='#4FE21B'>{0}</font>】行会",
	},
	[230] = { 
		xls_id = 230,
		id = 343,
		remarks = "系统",
		title = "【尸王争夺战】",
		content = "尊敬的玩家：<br>您在<p><font colorStyleID='1010007'>【尸王争夺战】</font>表现出色，获得“<font colorStyleID='1010007'>技能书页</font>”！<br>以下是您应得的奖励，请查收。",
	},
	[231] = { 
		xls_id = 231,
		id = 344,
		remarks = "系统",
		title = "【沙城霸主】",
		content = "尊敬的玩家：恭喜您的行会<font colorStyleID='1010007'>成功攻占沙巴克</font>！您荣登<font colorStyleID='1010007'>【沙城霸主】</font>，现向您发放<font colorStyleID='1010007'>嘉奖奖励</font>，请查收！",
	},
	[232] = { 
		xls_id = 232,
		id = 345,
		remarks = "系统",
		title = "【充值豪礼】",
		content = "尊敬的玩家：您在<font colorStyleID='1010007'>【合服豪礼】</font>中有奖励未领取，特发送邮件，请查收奖励！祝您游戏愉快！",
	},
	[233] = { 
		xls_id = 233,
		id = 346,
		remarks = "系统",
		title = "【结盟失败】",
		content = "很抱歉，您向<font color='#4FE21B'>{0}</font>行会发起的结盟申请被拒绝！请查收返还的花费！",
	},
	[234] = { 
		xls_id = 234,
		id = 347,
		remarks = "系统",
		title = "【攻城特殊奖励】",
		content = "尊敬的玩家：恭喜您的行会<font colorStyleID='1010007'>成功攻占沙巴克</font>！现向您发放<font colorStyleID='1010007'>特殊奖励</font>，请查收！",
	},
	[235] = { 
		xls_id = 235,
		id = 348,
		remarks = "系统",
		title = "【运镖失败】",
		content = "尊敬的玩家：<br>您下线期间<font colorStyleID='1010007'>运镖失败</font>！现向您发放<font colorStyleID='1010007'>奖励</font>，请查收！",
	},
	[236] = { 
		xls_id = 236,
		id = 349,
		remarks = "系统",
		title = "【灵符退还】",
		content = "尊敬的玩家：<br>您发出的行会红包未被领取完，现将剩余灵符退还",
	},
	[237] = { 
		xls_id = 237,
		id = 350,
		remarks = "系统",
		title = "【陨落的王冠】",
		boxReward = "3018155#3&8575#1&41#30000",
		content = "尊敬的玩家：<br>您的行会在【陨落的王冠】活动中夺得王冠，获得以下奖励",
	},
	[238] = { 
		xls_id = 238,
		id = 351,
		remarks = "系统",
		title = "【问卷奖励】",
		content = "尊敬的玩家：<br>感谢您参与游戏的问卷调查！特此发放奖励一份，希望您游戏愉快！",
	},
	[239] = { 
		xls_id = 239,
		id = 352,
		remarks = "系统",
		title = "【焰火屠魔】",
		content = "尊敬的玩家：<br>恭喜你的小队在【焰火屠魔】中奋勇作战，惩治邪恶，现向您发放奖励，请查收",
	},
	[240] = { 
		xls_id = 240,
		id = 353,
		remarks = "系统",
		title = "【陨落的王冠】",
		boxReward = "3018155#1&41#10000",
		content = "尊敬的玩家：<br>您的行会在【陨落的王冠】活动中尚未夺得王冠，获得以下参与奖励",
	},
	[241] = { 
		xls_id = 241,
		id = 354,
		remarks = "系统",
		title = "【装备归还】",
		content = "尊敬的玩家：<br>这是您的装备，请注意查收",
	},
	[242] = { 
		xls_id = 242,
		id = 355,
		remarks = "系统",
		title = "【沙城霸主】",
		content = "尊敬的玩家：恭喜您的行会<font colorStyleID='1010007'>成功攻占沙巴克</font>！您荣登<font colorStyleID='1010007'>【沙城霸主】</font>，现向您发放<font colorStyleID='1010007'>沙城霸主称号</font>，请查收！",
	},
	[243] = { 
		xls_id = 243,
		id = 356,
		remarks = "系统",
		title = "【斗笠投资】",
		content = "尊敬的玩家：<br>您昨日在【斗笠投资】中的奖励未领取，请查收",
	},
	[244] = { 
		xls_id = 244,
		id = 357,
		remarks = "系统",
		title = "【七日目标】",
		content = "尊敬的玩家：<br>您在【七日目标】中的奖励未领取，请查收",
	},
	[245] = { 
		xls_id = 245,
		id = 358,
		remarks = "系统",
		title = "【攻城提醒】",
		content = "尊敬的玩家：<font colorStyleID='1010007'>【决战沙巴克】</font>即将在<font colorStyleID='1010007'>今晚</font>开启，还请勇士们厉兵秣马，备战沙城！",
	},
	[246] = { 
		xls_id = 246,
		id = 359,
		remarks = "系统",
		title = "【勇士，欢迎回来！】",
		content = "好久不见，勇士！您的回归让玛法大陆蓬荜生辉！<br>非常感谢您能耐心的看完这封邮件！您将在我的帮助下，快速成长，雄震天下。 <br>接下来，您需要完成主线任务，重新熟悉相关功能及操作。<br> <br>很期待在不久的将来，能再次听到您的威名传遍玛法大陆！",
	},
	[247] = { 
		xls_id = 247,
		id = 360,
		remarks = "系统",
		title = "【跨服竞技场】",
		content = "尊敬的玩家：<br>您在上个赛季的【跨服竞技场】中的排名第%s位，威震天下，希望您再接再厉，再创辉煌！",
	},
	[248] = { 
		xls_id = 248,
		id = 361,
		remarks = "系统",
		title = "【跨服竞技场】",
		content = "尊敬的玩家：<br>您在上个赛季的【跨服竞技场】中的达到%s段位，声名显赫，希望您再接再厉，再创辉煌！",
	},
	[249] = { 
		xls_id = 249,
		id = 362,
		remarks = "系统",
		title = "【跨服首领】",
		content = "尊敬的勇士：<br>您在【跨服首领】活动中的表现卓越，您的伤害量排在第%s位，以下是排名奖励！<br>请查收",
	},
	[250] = { 
		xls_id = 250,
		id = 363,
		remarks = "系统",
		title = "【跨服首领】",
		content = "尊敬的勇士：<br>您在【跨服首领】活动中的表现卓越，以下是参与奖励！<br>请查收",
	},
	[251] = { 
		xls_id = 251,
		id = 364,
		remarks = "系统",
		title = "【帝王出巡】",
		content = "尊敬的勇士：<br>您在【帝王出巡】活动中的表现卓越，以下是参与奖励！<br>请查收",
	},
	[252] = { 
		xls_id = 252,
		id = 365,
		remarks = "系统",
		title = "【金秋豪礼】",
		content = "尊敬的玩家：您在<font colorStyleID='1010007'>【金秋有礼】</font>中有奖励未领取，特发送邮件，请查收奖励！祝您游戏愉快！",
	},
	[253] = { 
		xls_id = 253,
		id = 366,
		remarks = "系统",
		title = "【消费排行榜】",
		content = "尊敬的玩家：<br>您在【消费排行榜】中获得第%s名，腰缠万贯，富可敌国！以下是排名奖励！<br>请查收",
	},
	[254] = { 
		xls_id = 254,
		id = 367,
		remarks = "系统",
		title = "【消费排行榜】",
		content = "尊敬的玩家：<br>您在【消费排行榜】中一掷千金，以下是奖励！<br>请查收",
	},
	[255] = { 
		xls_id = 255,
		id = 368,
		remarks = "系统",
		title = "【巅峰竞技场】",
		content = "尊敬的玩家：<br>您在本赛季的【跨服竞技场】中的排名第%s位，威震天下，获得参加【巅峰竞技场】资格，请于次日21点20准时参加！",
	},
	[256] = { 
		xls_id = 256,
		id = 369,
		remarks = "系统",
		title = "【巅峰竞技场】",
		boxReward = "20#1",
		content = "尊敬的玩家：<br>您在本赛季的【巅峰竞技场】中成功晋级八强赛，请于次日21点20准时参加！",
	},
	[257] = { 
		xls_id = 257,
		id = 370,
		remarks = "系统",
		title = "【巅峰竞技场】",
		boxReward = "20#1",
		content = "尊敬的玩家：<br>您在本赛季的【巅峰竞技场】中成功晋级四强赛，请于次日21点20准时参加！",
	},
	[258] = { 
		xls_id = 258,
		id = 371,
		remarks = "系统",
		title = "【巅峰竞技场】",
		boxReward = "20#1",
		content = "尊敬的玩家：<br>您在本赛季的【巅峰竞技场】中成功晋级冠军赛，请于次日21点20准时参加！",
	},
	[259] = { 
		xls_id = 259,
		id = 372,
		remarks = "系统",
		title = "【巅峰竞技场】",
		boxReward = "20#1",
		content = "尊敬的玩家：<br>您在本赛季的【巅峰竞技场】中获得季军赛资格，请于次日21点20准时参加！",
	},
	[260] = { 
		xls_id = 260,
		id = 373,
		remarks = "系统",
		title = "【保险专员】",
		boxReward = "20#1",
		content = "尊敬的玩家：<br>您投保的装备<font colorStyleID='1010007'>%s</font>触发了掉落！<br>现已成功扣除保险次数，并将装备返还给您！<br>请注意查收",
	},
	[261] = { 
		xls_id = 261,
		id = 374,
		remarks = "系统",
		title = "【巅峰竞技场】",
		boxReward = "20#1",
		content = "尊敬的玩家：<br>您在本赛季的【巅峰竞技场】竞猜中，成功押中胜利的一方，特发送邮件，请查收奖励！祝您游戏愉快！",
	},
	[262] = { 
		xls_id = 262,
		id = 375,
		remarks = "系统",
		title = "【巅峰竞技场】",
		boxReward = "20#1",
		content = "尊敬的玩家：<br>您在本赛季的【巅峰竞技场】竞猜中，未能成功押中胜利的一方，特发送邮件！再接再厉！",
	},
	[263] = { 
		xls_id = 263,
		id = 376,
		remarks = "系统",
		title = "【巅峰竞技场】",
		boxReward = "20#1",
		content = "尊敬的玩家：<br>您在本赛季的【巅峰竞技场】中，勇夺十六强，神威盖世，特发送邮件，请查收奖励！祝您游戏愉快！",
	},
	[264] = { 
		xls_id = 264,
		id = 377,
		remarks = "系统",
		title = "【巅峰竞技场】",
		boxReward = "20#1",
		content = "尊敬的玩家：<br>您在本赛季的【巅峰竞技场】中，勇夺八强，威震天下，特发送邮件，请查收奖励！祝您游戏愉快！",
	},
	[265] = { 
		xls_id = 265,
		id = 378,
		remarks = "系统",
		title = "【巅峰竞技场】",
		boxReward = "20#1",
		content = "尊敬的玩家：<br>您在本赛季的【巅峰竞技场】中，勇夺第四名，声名鹊起，特发送邮件，请查收奖励！祝您游戏愉快！",
	},
	[266] = { 
		xls_id = 266,
		id = 379,
		remarks = "系统",
		title = "【巅峰竞技场】",
		boxReward = "20#1",
		content = "尊敬的玩家：<br>您在本赛季的【巅峰竞技场】中，勇夺季军，扬名天下，特发送邮件，请查收奖励！祝您游戏愉快！",
	},
	[267] = { 
		xls_id = 267,
		id = 380,
		remarks = "系统",
		title = "【巅峰竞技场】",
		boxReward = "20#1",
		content = "尊敬的玩家：<br>您在本赛季的【巅峰竞技场】中，勇夺亚军，雄霸天下，特发送邮件，请查收奖励！祝您游戏愉快！",
	},
	[268] = { 
		xls_id = 268,
		id = 381,
		remarks = "系统",
		title = "【巅峰竞技场】",
		boxReward = "20#1",
		content = "尊敬的玩家：<br>您在本赛季的【巅峰竞技场】中，勇夺冠军，四海响彻您的大名，天下无双，唯我独尊，特发送邮件，请查收奖励！祝您游戏愉快！",
	},
	[269] = { 
		xls_id = 269,
		id = 382,
		remarks = "系统",
		title = "【陨落的王冠】",
		boxReward = "8574#1",
		content = "尊敬的玩家：<br>您的行会在【陨落的王冠】活动中夺得王冠，会长额外获得行会红包奖励",
	},
	[270] = { 
		xls_id = 270,
		id = 383,
		parameter = 9999,
		remarks = "系统",
		title = "【神秘地带开启】",
		boxReward = "41#10000",
		content = {
			[1] = "传闻：上古某位帝皇皇陵已现世，里面的怪物异常凶猛，奖励更加丰厚，只有成为一位伟大的<font color='0x01f801'>摸金校尉</font>才能进入<font color='0x01f801'>【上古地宫】</font><br>挥起锄头100次必定获得称号，您要不要试一试？<br><font color='0x01f801'><u><a href='event:deliver",
			[2] = 214991,
			[3] = "14991'>立即前往！</a></u></font>",
		},
	},
	[271] = { 
		xls_id = 271,
		id = 384,
		parameter = 9999,
		remarks = "系统",
		title = "【蛮荒古城开启】",
		boxReward = "41#10000",
		content = {
			[1] = "全新地图<font color='0x01f801'>【蛮荒古城】</font>开启，该地图为<font color='0x01f801'>跨服地图</font>，玩家需要激活摸金校尉称号才可进入，激活称号后，可从<font color='0x01f801'>【神秘地带】</font>内的<font color='0x01f801'>【上古地宫】</font>处前往【地宫长廊】，在【地宫长廊】的<font color='0x01f801'>【次元裂缝】</font>进入，若玩家拥有摸金校尉称号即可在<font color='0x01f801'>跨服战场面板内</font>，快速传送到次元裂缝<br><font color='0x01f801'>摸金校尉称号可在神秘地带挖掘100次获得</font><br><font color='0x01f801'><u><a href='event:deliver",
			[2] = 214991,
			[3] = "14991'>立即前往！</a></u></font>",
		},
	},
	[272] = { 
		xls_id = 272,
		id = 385,
		remarks = "系统",
		title = "【身份验证奖励】",
		content = "亲爱的玩家您好，以下是您在身份验证所获得的奖励，请查收。",
	},
	[273] = { 
		xls_id = 273,
		id = 386,
		parameter = 9999,
		remarks = "系统",
		title = "【跨服战场开启】",
		content = "<font color='#28ef01'>跨服战场</font>活动开启。<br>　<br>封印着诸多魔神的跨服战场内埋藏着大量宝藏，转生等级达到<font color='#28ef01'>2转</font>的玩家可前往<font color='#28ef01'>跨服战场</font>地图<br>　<br>完成<font color='#28ef01'>圣物采集</font>任务有概率获得<font color='#ffe400'>功勋令</font>、<font color='#ffe400'>圣域镖令</font>、<font color='#ffe400'>荣誉之魂</font>，使用<font color='#28ef01'>宝箱卷轴</font>可以增加采集次数。<br>　<br>击杀圣域首领可获得大量材料，使用<font color='#28ef01'>首领卷轴</font>可以增加首领击杀次数。<br>　<br>更有双倍押镖活动，每日11:00-12:00和21:00-22:00参与押镖即可获得<font color='#ffe400'>双倍</font>奖励。",
	},
	[274] = { 
		xls_id = 274,
		id = 387,
		parameter = 9999,
		remarks = "系统",
		title = "【陨落的王冠开启】",
		content = "<font color='#28ef01'>陨落的王冠</font>活动开启<br>　<br>加入行会的玩家可前往主城NPC-<font color='#28ef01'>陨落的王冠</font>处进入皇宫争夺王冠，胜利的行会将获得红包奖励，快来和兄弟们一起行动",
	},
	[275] = { 
		xls_id = 275,
		id = 388,
		parameter = 9999,
		remarks = "系统",
		title = "【行会晶核开启】",
		content = "<font color='#28ef01'>行会晶核</font>活动开启<br>　<br>加入行会且3转以上的玩家可前往主城NPC-<font color='#28ef01'>行会晶核</font>处领取任务，每天完成前两环即可获得高额奖励。<br>　<br>行会每周完成任务达到要求次数，也有大量奖励哦",
	},
	[276] = { 
		xls_id = 276,
		id = 389,
		parameter = 9999,
		remarks = "系统",
		title = "【恶魔祭坛开启】",
		content = "<font color='#28ef01'>恶魔祭坛</font>活动开启<br>　<br>达到要求的玩家可点击<font color='#28ef01'>跨服战场-恶魔祭坛</font>前往参与活动，参与活动即可获得大量奖励，协助行会成员还能获得协助奖励。<br>　<br>恶魔祭坛分为多层，玩家可根据自身情况选择合适的层数，只有拥有封印值的玩家才能获得boss归属，玩家获得boss归属后扣除封印值，每日0点全部回复。<br>　<br>有行会的玩家可以点击协助向行会成员发起求助，没有封印值的玩家无法请求协助，若请求协助的玩家封印值归零或退出活动地图，则协助状态消失。<br>　<br>快来和行会兄弟一起战斗吧",
	},
	[277] = { 
		xls_id = 277,
		id = 390,
		parameter = 9999,
		remarks = "系统",
		title = "【无间炼狱开启】",
		content = "跨服活动<font color='0x01f801'>无间炼狱</font>开启<br> <br>玩家可从<font color='0x01f801'>【神秘地带】</font>内的<font color='0x01f801'>【上古地宫】</font>处寻找地宫老人，前往【地宫长廊】的<font color='0x01f801'>【次元裂缝】</font>处进入<font color='0x01f801'>【蛮荒古城】</font>，从蛮荒古城内NPC<font color='0x01f801'>【无间炼狱】</font>处参与活动<br> <br>每日16点和21点都有混世魔王出现，击杀魔王就有概率获得高级装备，同行会成员获得boss归属，其他玩家也能获得协助奖励",
	},
	[278] = { 
		xls_id = 278,
		id = 391,
		parameter = 6,
		remarks = "系统",
		title = "【远古遗迹第二层开启】",
		content = "<font color='0x01f801'>远古遗迹第二层</font>开启<br>　<br>·开服已达<font color='#28ef01'>6天</font>，开启<font color='#28ef01'>远古遗迹第二层</font>地图。<br>·玩家可从<font color='0x01f801'>【首领挑战-遗迹】</font>进入参与活动。<br>",
	},
	[279] = { 
		xls_id = 279,
		id = 392,
		parameter = 8,
		remarks = "系统",
		title = "【车迟国斗法开启】",
		content = "<font color='0x01f801'>车迟国斗法</font>开启<br>　<br>·开服已达<font color='#28ef01'>8天</font>，开启<font color='#28ef01'>车迟国斗法</font>地图。<br>·玩家可从<font color='0x01f802'>【跨服战场-车迟斗法】</font>进入参与活动。<br>",
	},
	[280] = { 
		xls_id = 280,
		id = 396,
		parameter = 31,
		remarks = "系统",
		title = "【混沌领域开启】",
		content = "<font color='#28ef01'>一、混沌领域地图开启</font><br>1、开服35天且18转开启六耳猕猴领域地图，同时开放混沌神将装备。<br>2、六耳猕猴领域分两层，1层是本服地图，可通过界面进入，2层是跨服地图，可通过1层传送进入。<br>3、本服中是六耳猕猴和分身，跨服中是六耳猕猴幻影和分身。<br>4、本服BOSS拥有群雷技能，跨服BOSS拥有单雷技能，本服BOSS攻击更强，掉落更高。<br>5、分身复活时间为14~22小时，幻影和本尊复活时间为24小时<br>6、地图内掉落超酷炫足迹<br><br><font color='#28ef01'>二、混沌神将装备开放</font><br>1、完成混沌神将内任务后，可解锁对应装备槽。<br>2、想穿戴神将装备必须先解锁装备槽，完成对应任务可解锁对应装备槽，完成入门、精通、化境全部任务后可解锁全部装备槽。",
	},
	[281] = { 
		xls_id = 281,
		id = 500,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "十二生肖开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>十二生肖</font>功能开启<br>　<br>·等级达到<font color='#28ef01'>40级</font>后，开启<font color='#28ef01'>十二生肖</font>装备。<br>·通过<font color='#28ef01'>击杀BOSS</font>掉落或开启<font color='#28ef01'>极品生肖盒</font>，可获得十二生肖装备。<br>·集齐十二生肖，攻击即可触发<font color='#28ef01'>冰冻神力</font>。<br>极品生肖盒可从火龙宝箱内获得。",
	},
	[282] = { 
		xls_id = 282,
		id = 501,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "勇闯天关开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>勇闯天关</font>功能开启<br>　<br>·等级达到<font color='#28ef01'>42级</font>后，开启勇闯天关挑战。<br>·<font color='#28ef01'>每日</font>有<font color='#28ef01'>3次</font>挑战勇闯天关成功的机会，<font color='#28ef01'>挑战成功</font>后获得<font color='#28ef01'>技能书</font>和<font color='#28ef01'>极品斗笠</font>。<br>·达成当前关卡的<font color='#28ef01'>三星任务</font>，即可<font color='#28ef01'>解锁</font>下一个关卡。",
	},
	[283] = { 
		xls_id = 283,
		id = 502,
		parameter = 1,
		remarks = "【新手宝典】",
		title = "熔炉开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>熔炉</font>功能开启<br>　<br>·开服已达<font color='#28ef01'>1天</font>，<font color='#28ef01'>熔炉</font>功能开启。<br>·<font color='#28ef01'>星王级以上的装备</font>可以进行<font color='#28ef01'>熔炼</font>，可随机获得<font color='#28ef01'>神技书页、木之结晶</font>等珍稀材料。<font color='#28ef01'>贪狼级</font>以上装备必得元宝、极品赦令，装备等级越高，熔炼获得的材料越多。",
	},
	[284] = { 
		xls_id = 284,
		id = 503,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "装备觉醒开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>装备觉醒</font>功能开启<br>　<br>·开服已达<font color='#28ef01'>5天</font>，可以<font color='#28ef01'>觉醒装备</font>。<br>·<font color='#28ef01'>玉佩</font>，<font color='#28ef01'>盾牌</font>，<font color='#28ef01'>勋章</font>，<font color='#28ef01'>斗笠</font>，<font color='#28ef01'>疗伤石</font>，<font color='#28ef01'>面纱</font>可进行<font color='#28ef01'>觉醒</font>。<br>·觉醒提升到<font color='#28ef01'>特殊等级</font>将<font color='#28ef01'>额外</font>获得<font color='#28ef01'>强力特殊技能</font>。<br>·觉醒后的属性，无论是否佩戴该部位装备都生效。<br>　<br><font color='#28ef01'>斗笠：攻击怪物时，造成额外伤害<br>盾牌：战斗中，受到的伤害降低<br>勋章：触发致命一击时，伤害额外增加<br>疗伤石：药品恢复效果提升<br>玉佩：战斗中，造成的伤害增加<br>面纱：血祭等级高于目标时，伤害额外增加</font>。",
	},
	[285] = { 
		xls_id = 285,
		id = 504,
		parameter = 85,
		remarks = "【新手宝典】",
		title = "转生开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>转生</font>功能开启<br>　<br>·等级达到<font color='#28ef01'>85级</font>后，开启<font color='#28ef01'>转生</font>系统。<br>·转生需要完成<font color='#28ef01'>3个任务</font>，完成任务后提升转生等级。<br>·转生等级提升后，能佩戴更高品质的装备。",
	},
	[286] = { 
		xls_id = 286,
		id = 505,
		parameter = 4,
		remarks = "【新手宝典】",
		title = "跨服战场开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>跨服战场</font>功能开启<br>　<br>·开服已达<font color='#28ef01'>4天</font>，开启<font color='#28ef01'>跨服战场</font>地图。<br>·每日可完成<font color='#28ef01'>圣物采集</font>任务。<br>·<font color='#28ef01'>击杀</font>山庄刷新的首领怪物，有概率获得<font color='#28ef01'>极品装备</font>。",
	},
	[287] = { 
		xls_id = 287,
		id = 506,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "魔神押镖开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>跨服战场</font>功能开启<br>　<br>·开服已达<font color='#28ef01'>7天</font>，跨服战场开启<font color='#28ef01'>魔神刷新</font>和<font color='#28ef01'>押镖任务</font>。<br>·每<font color='#28ef01'>周六周日</font>会刷新魔神怪物，击杀后可获得<font color='#28ef01'>极品奖励</font>。<br>·护送<font color='#28ef01'>镖车到达终点</font>，可获得<font color='#28ef01'>极品奖励</font>。<br>·每日有<font color='#28ef01'>双倍押镖时间</font>，能获得<font color='#28ef01'>双倍奖励</font>。",
	},
	[288] = { 
		xls_id = 288,
		id = 507,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "灵魂殿堂开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>灵魂殿堂</font>功能开启<br>　<br>·开服已到<font color='#28ef01'>第8天</font>，<font color='#28ef01'>搜索BOSS尸体</font>，将会有概率获得<font color='#28ef01'>蕴含怪物灵魂的稀有材料</font>，<br>·前往庄园，通过NPC进入<font color='#28ef01'>灵魂殿堂</font>，消耗材料激活、升级怪物雕像，将会获得<font color='#28ef01'>大量属性</font>。",
	},
	[289] = { 
		xls_id = 289,
		id = 508,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "洗练开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>洗练</font>功能开启<br>　<br>·开服已达<font color='#28ef01'>第9天</font>，可以<font color='#28ef01'>洗练装备</font>。<br>·消耗洗练石可洗练出<font color='#28ef01'>极品属性</font>，需要点击“保存属性”才会生效。<br>·切换装备或关闭界面，未保存的洗练属性将不会保留。<br>洗练石可从<font color='#28ef01'>行会首领</font>活动中获得。",
	},
	[290] = { 
		xls_id = 290,
		id = 509,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "圣域幻境开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>圣域幻境</font>功能开启<br>　<br>·开服已达<font color='#28ef01'>第12天</font>，开启<font color='#28ef01'>圣域幻境</font>地图。<br>·圣域幻境地图的怪物比普通幻境更加强大。<br>·击杀圣域幻境的怪物，将获得<font color='#28ef01'>元宝、炼魂材料、强星材料等稀有奖励</font>。<br>　<br><font color='#28ef01'>炼魂</font>功能开启<br>　<br>·开服已达<font color='#28ef01'>第12天</font>，可以<font color='#28ef01'>炼魂装备</font>。<br>·消耗<font color='#28ef01'>绿宝石矿</font>可对<font color='#28ef01'>火龙级以上装备</font>进行<font color='#28ef01'>炼魂</font>。<br>·炼魂存在成功率，所使用的材料品质越高，数量越多，炼魂成功率越高。<br>·<font color='#28ef01'>炼魂</font>能够<font color='#28ef01'>提升装备精炼上限</font>和<font color='#28ef01'>强星上限</font>。<br>　<br><font color='#28ef01'>4转装备合成</font><br>　<br>·开服已达<font color='#28ef01'>第12天</font>，开启<font color='#28ef01'>主宰级装备</font>的合成。<br>·可在熔炉锻造界面消耗主宰锻造书材料和金牛级装备进行合成。",
	},
	[291] = { 
		xls_id = 291,
		id = 510,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "卧龙遗迹开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>卧龙遗迹</font>开启<br>　<br>·开服已达<font color='#28ef01'>第18天</font>，开启<font color='#28ef01'>卧龙遗迹</font>地图。<br>·可从跨服战场面板进入，可以<font color='#28ef01'>挑战神龙守将</font>。<br>·击杀一定次数神龙守将一定次数后，将开启前往蛮荒古城的次元裂缝<br>　<br>·<font color='#28ef01'>传奇级装备</font>开启<font color='#28ef01'>合成</font>。<br>·可在熔炉锻造界面消耗传奇锻造书材料和主宰级装备进行合成。",
	},
	[292] = { 
		xls_id = 292,
		id = 511,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "跨服蛮荒古城",
		boxReward = "41#500",
		content = "<font color='#28ef01'>跨服蛮荒古城</font><br>　<br>·开服已达<font color='#28ef01'>第21天</font>，开启<font color='#28ef01'>蛮荒古城</font>地图。<br>·卧龙遗迹击败神龙守将后，可从次元裂缝中进入蛮荒古城。<br>·蛮荒古城会刷新强大的<font color='#28ef01'>远古首领</font>，击杀后可获得<font color='#28ef01'>极品掉落</font>。",
	},
	[293] = { 
		xls_id = 293,
		id = 512,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "精炼开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>精炼</font>功能开启<br>　<br>·开服已达<font color='#28ef01'>第25天</font>，可以<font color='#28ef01'>精炼装备</font>。<br>·消耗精炼石可对<font color='#28ef01'>火龙级及以上装备</font>进行精炼。<br>·装备品质等级越高，精炼获得的属性就越高。",
	},
	[294] = { 
		xls_id = 294,
		id = 513,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "元素时装",
		boxReward = "41#500",
		content = "<font color='#28ef01'>元素时装</font>功能开启<br>　<br>·开服已达<font color='#28ef01'>第29天</font>，开启<font color='#28ef01'>元素时装</font>。<br>·可在<font color='#28ef01'>熔炉锻造界面</font>使用<font color='#28ef01'>时装碎片</font>合成<font color='#28ef01'>元素时装</font>。<br>·可在角色时装中设置元素时装的外观显示。<br>·可从击杀boss或合成获得时装碎片。",
	},
	[295] = { 
		xls_id = 295,
		id = 514,
		parameter = 25,
		remarks = "【新手宝典】",
		title = "焰火屠魔开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>焰火屠魔</font>功能开启<br>　<br>·开服已达<font color='#28ef01'>第25天</font>，开启<font color='#28ef01'>焰火屠魔</font>玩法。<br>·可以1-3人组队前往第三大陆-西游秘境的焰火屠魔挑战多人副本。<br>·根据通关成功时长评出S、A、B级评分，获得<font color='#28ef01'>S级评分</font>即可<font color='#28ef01'>解锁下一难度</font>。<br>·每周首次通关会获得<font color='#28ef01'>首通奖励</font>，<font color='#28ef01'>协助</font>其他玩家通关会获得<font color='#28ef01'>侠义之心</font>，根据道具数量每周结算并重置<font color='#28ef01'>排名奖励</font>。",
	},
	[296] = { 
		xls_id = 296,
		id = 515,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "生肖殿堂开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>生肖殿堂</font>功能开启<br>　<br>·开服已达<font color='#28ef01'>第60天</font>，开启<font color='#28ef01'>生肖殿堂</font>地图。<br>·生肖地图盘踞着12只生肖怪物，击杀后有机会获得<font color='#28ef01'>生肖装备</font>。<br>真龙级装备开启合成。<br>·可在熔炉锻造界面消耗真龙锻造书材料和热血级装备进行合成。",
	},
	[297] = { 
		xls_id = 297,
		id = 516,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "铭文开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>铭文</font>功能开启<br>　<br>·开服已达<font color='#28ef01'>第60天</font>，可以给装备<font color='#28ef01'>镶嵌铭文</font>。<br>·可通过击杀boss获得<font color='#28ef01'>源石道具</font>。<br>·可前往庄园的<font color='#28ef01'>铭文锻造师</font>切割源石，获得<font color='#28ef01'>装备铭文</font>。<br>·火龙级及以上装备在打孔后可以镶嵌最多3个铭文。<br>·铭文需穿戴装备后才生效，同类型的铭文只能生效三个最高级的。",
	},
	[298] = { 
		xls_id = 298,
		id = 517,
		parameter = 9999,
		remarks = "【新手宝典】",
		title = "觉醒技能开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>觉醒技能</font>开启<br>　<br>·开服已达<font color='#28ef01'>第75天</font>，开启<font color='#28ef01'>觉醒技能</font>。<br>·可在技能书合成中合成<font color='#28ef01'>觉醒技能书</font>。<br>·觉醒技能升级失败时有概率降低技能等级。<br>·最强技能无需升级，基础觉醒技能中等级最高的技能将激活同等级的最强技能。",
	},
	[299] = { 
		xls_id = 299,
		id = 518,
		parameter = 4,
		remarks = "【新手宝典】",
		title = "王者争霸开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>王者争霸</font>开启<br>　<br>·开服已达<font color='#28ef01'>4天</font>，开启<font color='#28ef01'>王者争霸</font><br>·可从游戏右上角点击<font color='#28ef01'>跨服远征-王者争霸</font>进入",
	},
	[300] = { 
		xls_id = 300,
		id = 519,
		parameter = 15,
		remarks = "【新手宝典】",
		title = "新地图开启",
		boxReward = "41#500",
		content = "<font color='#28ef01'>新地图</font>开启<br>　<br>·开服已达<font color='#28ef01'>15天</font>，开启全新地图：<font color='#28ef01'>跨服冰宫</font>，<br>·可在游戏页面右上角点击<font color='#28ef01'>首领挑战-跨服冰宫</font>进入。",
	},
	[301] = { 
		xls_id = 301,
		id = 520,
		remarks = "行会晶核奖励一",
		title = "行会晶核奖励",
		boxReward = "41#10000",
		content = "尊敬的勇士：<br>根据您每周为行会做出的贡献，以下是行会晶核的奖励！<br>请查收",
	},
	[302] = { 
		xls_id = 302,
		id = 521,
		remarks = "行会晶核奖励二",
		title = "行会晶核奖励",
		boxReward = "41#50000&11#1000",
		content = "尊敬的勇士：<br>根据您每周为行会做出的贡献，以下是行会晶核的奖励！<br>请查收",
	},
	[303] = { 
		xls_id = 303,
		id = 522,
		remarks = "行会晶核奖励三",
		title = "行会晶核奖励",
		boxReward = "41#100000&11#2000&3000877#1",
		content = "尊敬的勇士：<br>根据您每周为行会做出的贡献，以下是行会晶核的奖励！<br>请查收",
	},
	[304] = { 
		xls_id = 304,
		id = 523,
		remarks = "自然装备保护",
		title = "自然装备死亡掉落保护",
		content = "尊敬的玩家：<br>很不幸您的装备由于死亡掉落触发保护，以下是您的附魔的自然装备！<br>请查收",
	},
	[305] = { 
		xls_id = 305,
		id = 530,
		remarks = "系统",
		title = "【四方迷阵】",
		content = "尊敬的玩家：<br>以下是您参与<p><font colorStyleID='1010007'>【四方迷阵】</font>活动的行会排名第{0}名奖励！<br>请查收",
	},
	[306] = { 
		xls_id = 306,
		id = 524,
		remarks = "活动奖励",
		title = "活动奖励",
		content = "这是您遗漏的活动奖励，敬请查收！",
	},
	[307] = { 
		xls_id = 307,
		id = 307,
		remarks = "系统",
		title = "【热血乱斗场】",
		content = "尊敬的玩家：以下是您参与【热血乱斗场】活动的排名奖励！请查收",
	},
	[308] = { 
		xls_id = 308,
		id = 308,
		remarks = "系统",
		title = "【热血乱斗场】",
		content = "尊敬的玩家：以下是您参与【热血乱斗场】活动的积分奖励！请查收",
	},
	[309] = { 
		xls_id = 309,
		id = 309,
		parameter = 4,
		remarks = "系统",
		title = "【江湖名望】",
		content = "尊敬的玩家：以下是您提升至【%s】奖励！请查收",
	},
	[310] = { 
		xls_id = 310,
		id = 310,
		parameter = 15,
		remarks = "系统",
		title = "【江湖名望】",
		content = "尊敬的玩家：以下是您购买的【%s】特惠礼包！请查收",
	},
}
return config
