local config = {
	[1] = {
		CategoryID = 1,
		SubcategoryID = 1,
		name = "01阶-05阶装备",
		imagePath = 1,
	},
	[2] = {
		CategoryID = 1,
		SubcategoryID = 2,
		name = "06阶-10阶装备",
		imagePath = 2,
	},
	[3] = {
		CategoryID = 1,
		SubcategoryID = 3,
		name = "11阶-15阶装备",
		imagePath = 3,
	},
	[4] = {
		CategoryID = 1,
		SubcategoryID = 4,
		name = "16阶-20阶装备",
		imagePath = 4,
	},
	[5] = {
		CategoryID = 1,
		SubcategoryID = 5,
		name = "21阶-22阶装备",
		imagePath = 5,
	},
	[6] = {
		CategoryID = 1,
		SubcategoryID = 6,
		name = "普通[珍宝]",
		imagePath = 6,
	},
	[7] = {
		CategoryID = 1,
		SubcategoryID = 7,
		name = "普通[首饰]",
		imagePath = 7,
	},
	[8] = {
		CategoryID = 1,
		SubcategoryID = 8,
		name = "普通[时装]",
		imagePath = 8,
	},
	[9] = {
		CategoryID = 2,
		SubcategoryID = 9,
		name = "高级神器[首饰]",
		imagePath = 1,
	},
	[10] = {
		CategoryID = 2,
		SubcategoryID = 10,
		name = "高级神器[剑甲]",
		imagePath = 2,
	},
	[11] = {
		CategoryID = 2,
		SubcategoryID = 11,
		name = "特殊神器",
		imagePath = 3,
	},
	[12] = {
		CategoryID = 2,
		SubcategoryID = 12,
		name = "特殊套装",
		imagePath = 4,
	},
	[13] = {
		CategoryID = 3,
		SubcategoryID = 13,
		name = "价值灵石[01~03]",
		imagePath = 1,
	},
	[14] = {
		CategoryID = 3,
		SubcategoryID = 14,
		name = "价值灵石[04~06]",
		imagePath = 2,
	},
	[15] = {
		CategoryID = 3,
		SubcategoryID = 15,
		name = "价值灵石[07~10]",
		imagePath = 3,
	},
	[16] = {
		CategoryID = 3,
		SubcategoryID = 16,
		name = "价值灵石[11~15]",
		imagePath = 4,
	},
	[17] = {
		CategoryID = 3,
		SubcategoryID = 17,
		name = "价值灵石[16~20]",
		imagePath = 5,
	},
	[18] = {
		CategoryID = 3,
		SubcategoryID = 18,
		name = "价值灵石[30]",
		imagePath = 6,
	},
	[19] = {
		CategoryID = 3,
		SubcategoryID = 19,
		name = "价值灵石[40]",
		imagePath = 7,
	},
	[20] = {
		CategoryID = 3,
		SubcategoryID = 20,
		name = "价值灵石[50]",
		imagePath = 8,
	},
	[21] = {
		CategoryID = 3,
		SubcategoryID = 21,
		name = "价值灵石[60]",
		imagePath = 9,
	},
	[22] = {
		CategoryID = 4,
		SubcategoryID = 22,
		name = "玄天大陆材料",
		imagePath = 1,
	},
	[23] = {
		CategoryID = 4,
		SubcategoryID = 23,
		name = "天元大陆材料",
		imagePath = 2,
	},
	[24] = {
		CategoryID = 4,
		SubcategoryID = 24,
		name = "神龙帝国材料",
		imagePath = 3,
	},
	[25] = {
		CategoryID = 4,
		SubcategoryID = 25,
		name = "酆都鬼城材料",
		imagePath = 8,
	},
	[26] = {
		CategoryID = 4,
		SubcategoryID = 26,
		name = "极恶大陆材料",
		imagePath = 4,
	},
	[27] = {
		CategoryID = 4,
		SubcategoryID = 27,
		name = "太阳圣城材料",
		imagePath = 5,
	},
	[28] = {
		CategoryID = 4,
		SubcategoryID = 28,
		name = "破晓之境材料",
		imagePath = 6,
	},
	[29] = {
		CategoryID = 4,
		SubcategoryID = 29,
		name = "其他材料",
		imagePath = 7,
	},
	[30] = {
		CategoryID = 5,
		SubcategoryID = 30,
		name = "经验卷",
		imagePath = 1,
	},
	[31] = {
		CategoryID = 5,
		SubcategoryID = 31,
		name = "美酒",
		imagePath = 2,
	},
	[32] = {
		CategoryID = 5,
		SubcategoryID = 32,
		name = "普通禁物",
		imagePath = 3,
	},
	[33] = {
		CategoryID = 5,
		SubcategoryID = 33,
		name = "稀有禁物",
		imagePath = 4,
	},
	[34] = {
		CategoryID = 5,
		SubcategoryID = 34,
		name = "史诗禁物",
		imagePath = 5,
	},
	[35] = {
		CategoryID = 5,
		SubcategoryID = 35,
		name = "传说禁物",
		imagePath = 6,
	},
}
return config