local config = { 
	[31] = { 
		xls_id = 31,
		attDesc = "自身HP减少12%攻魔道增加10%",
		buffId = 31076,
		fontDesc = "“在战斗中，唯有勇者敢以生命为赌注，唤醒体内沉睡的怒火",
		name = "血怒之誓",
		TMtype = 4,
	},
	[1] = { 
		xls_id = 1,
		attDesc = "专属装备爆率+50%，装备爆率增加20%",
		value = 57,
		name = "天选之人",
		TMtype = 3,
	},
	[2] = { 
		xls_id = 2,
		attDesc = "攻击时对生命值低于30%的怪物额外造成75%的真实伤害",
		attackType = 3,
		buffId = 3002,
		name = "摧枯拉朽",
		TMtype = 1,
	},
	[3] = { 
		xls_id = 3,
		attDesc = "选择后，每一重混元功法技能都会额外提供10点攻击力跟100点生命值",
		value = 52,
		name = "终身进修",
		TMtype = 3,
	},
	[4] = { 
		xls_id = 4,
		attDesc = "攻击怪物时刀刀恢复1888点生命值",
		attackType = 3,
		buffId = 3003,
		fontDesc = "汲取灵魂之力，每次攻击怪物时恢复大量生命值，持续作战。",
		name = "灵魂吸虹",
		TMtype = 1,
	},
	[5] = { 
		xls_id = 5,
		attDesc = "每次攻击时都会增加人物1%的切割伤害（最高上限10%）停止攻击5秒后状态清零！",
		attackType = 3,
		buffId = 3004,
		name = "双全手",
		TMtype = 1,
	},
	[6] = { 
		xls_id = 6,
		attDesc = "当人物死亡时有概率增加50点攻击力（上限3000点）",
		value = 36,
		attackType = 16,
		buffId = 16000,
		fontDesc = "每次死亡后愈发坚韧，有概率提升攻击力，勇气倍增。",
		name = "越挫越勇",
		TMtype = {
			[1] = 1,
			[2] = 3,
		},
	},
	[7] = { 
		xls_id = 7,
		attDesc = "被玩家击杀后，额外给击杀者增加200点PK值",
		attackType = 16,
		buffId = 16001,
		fontDesc = "身负诅咒，被击杀后让对方承受代价，额外增加其PK值。",
		name = "诅咒之体",
		TMtype = 1,
	},
	[8] = { 
		xls_id = 8,
		attDesc = "所有攻击伤害+8%，受到的伤害+8%",
		value = 38,
		attackType = 4,
		buffId = 4000,
		fontDesc = "自信过剩，攻击伤害大幅提升，但同时也增加了受到的伤害。",
		name = "狂妄自大",
		TMtype = {
			[1] = 1,
			[2] = 3,
		},
	},
	[9] = { 
		xls_id = 9,
		attDesc = "每占卜一次，额外增加20点攻魔道，最多增加200点。",
		value = 39,
		fontDesc = "占卜获取神秘祝福，显著提升自身战斗属性。",
		name = "祝福之体",
		TMtype = 3,
	},
	[10] = { 
		xls_id = 10,
		attDesc = "每杀死1个玩家，降低100PK值",
		attackType = 15,
		buffId = 15000,
		fontDesc = "得到天道击杀许可。击杀不但不会增加PK值，反而会降低PK值。",
		name = "合法击杀",
		TMtype = 1,
	},
	[11] = { 
		xls_id = 11,
		attDesc = "装备强化时，成功几率+5%",
		value = 40,
		fontDesc = "拥有卓越的强化技艺，装备强化成功几率大增",
		name = "强化大师",
		TMtype = 3,
	},
	[12] = { 
		xls_id = 12,
		attDesc = "任何攻击你的敌人都会被灼自己最大生命的%2",
		attackType = 7,
		buffId = 7000,
		fontDesc = "持续5S，CD30S",
		name = "烈焰焚身",
		TMtype = 1,
	},
	[13] = { 
		xls_id = 13,
		attDesc = "攻击玩家时，有1%的概率窃取身上1%的金币。（每次最多100W）每天最高2000W",
		attackType = 2,
		buffId = 2001,
		name = "绝世神偷",
		TMtype = 1,
	},
	[14] = { 
		xls_id = 14,
		attDesc = "攻击比自己等级高的玩家时，每相差1级，造成2%的额外伤害。最多20%",
		attackType = 5,
		buffId = 5000,
		name = "越级挑战",
		TMtype = 1,
	},
	[15] = { 
		xls_id = 15,
		attDesc = "死亡时对杀死自己的敌人造成对方最大HP30%的真实伤害。",
		attackType = 16,
		buffId = 16002,
		fontDesc = "在生命的最后一刻，爆发出惊人力量，对敌人造成真实伤害。",
		name = "同归于尽",
		TMtype = 1,
	},
	[16] = { 
		xls_id = 16,
		attDesc = "不组队时，对怪伤害+15%",
		attackType = 6,
		buffId = 6000,
		fontDesc = "孤身作战，无惧挑战，不组队时对怪物伤害大幅提升。",
		name = "独狼",
		TMtype = 1,
	},
	[17] = { 
		xls_id = 17,
		attDesc = "增加烈火剑法伤害10%",
		attackType = 4,
		buffId = 4001,
		fontDesc = "心如烈焰，炽热无比，烈火剑法伤害大幅提升。",
		name = "烈焰之心",
		TMtype = 1,
	},
	[18] = { 
		xls_id = 18,
		attr = {
			[1] = {
				[1] = 28,
				[2] = 13,
			},
		},
		attDesc = "忽视目标防御12%",
		fontDesc = "洞察一切，攻击忽视目标防御，精准打击敌人。",
		name = "天眼通",
		TMtype = 2,
	},
	[19] = { 
		xls_id = 19,
		attr = {
			[1] = {
				[1] = 220,
				[2] = 13,
			},
		},
		attDesc = "增加闪避率+12%",
		fontDesc = "身形灵动，飘逸若仙，闪避率大幅提升，轻松避开攻击。",
		name = "逍遥游",
		TMtype = 2,
	},
	[20] = { 
		xls_id = 20,
		attr = {
			[1] = {
				[1] = 219,
				[2] = 13,
			},
		},
		attDesc = "增加命中率+12%",
		fontDesc = "轻盈如花，敏捷若月，命中率大幅提升，精准打击目标。",
		name = "飞花逐月",
		TMtype = 2,
	},
	[21] = { 
		xls_id = 21,
		attDesc = "对怪暴击概率+15%",
		attackType = 6,
		buffId = 6001,
		fontDesc = "专精猎杀邪魔，对怪物的暴击概率大幅提升。",
		name = "猎魔人",
		TMtype = 1,
	},
	[22] = { 
		xls_id = 22,
		attDesc = "攻击时3%概率召唤五雷轰顶对目标造成最大攻击60%的伤害",
		attackType = 1,
		buffId = 1001,
		fontDesc = "引天雷之力，攻击时有概率召唤五雷轰顶，对目标造成毁灭性伤害。",
		name = "天雷诀",
		TMtype = 1,
	},
	[23] = { 
		xls_id = 23,
		attDesc = "击杀怪物后有概率复活其为自己战斗，持续10分钟.最多3只",
		attackType = 14,
		buffId = 14001,
		fontDesc = "操控灵魂，击杀怪物后有概率复活其为己所用，持续战斗助力。",
		name = "拘灵遣将",
		TMtype = 1,
	},
	[24] = { 
		xls_id = 24,
		attDesc = "被攻击时，有5%的概率释放治疗术。",
		attackType = 7,
		buffId = 7001,
		fontDesc = "神奇医术，受到攻击时有概率触发治疗术，迅速恢复生命。",
		name = "妙手回春",
		TMtype = 1,
	},
	[25] = { 
		xls_id = 25,
		attr = {
			[1] = {
				[1] = 216,
				[2] = 10,
			},
			[2] = {
				[1] = 204,
				[2] = 40,
			},
		},
		attDesc = "装备回收+10% 怪物爆率+40%",
		name = "宝藏猎人",
		TMtype = 2,
	},
	[26] = { 
		xls_id = 26,
		attDesc = "神力倍数增加5%",
		value = 244,
		name = "火力全开",
		TMtype = 3,
	},
	[27] = { 
		xls_id = 27,
		attDesc = "当天每杀死一个狂暴玩家将提升1%回收比例最高可获得提升50点",
		value = 245,
		fontDesc = "每一次勇敢的出击，都将带来额外的战斗收益",
		name = "聚宝术",
		TMtype = 3,
	},
	[28] = { 
		xls_id = 28,
		attr = {
			[1] = {
				[1] = 26,
				[2] = 5,
			},
			[2] = {
				[1] = 27,
				[2] = 5,
			},
			[3] = {
				[1] = 207,
				[2] = 5,
			},
		},
		attDesc = "伤害减免+5% 最大生命+5%",
		fontDesc = "身经百战、历经磨砺，‘皮糙肉厚’象征着战士不屈的韧性与持久的生命力",
		name = "皮糙肉厚",
		TMtype = 2,
	},
	[29] = { 
		xls_id = 29,
		attr = {
			[1] = {
				[1] = 25,
				[2] = 5,
			},
			[2] = {
				[1] = 206,
				[2] = 5,
			},
		},
		attDesc = "攻击伤害+5% 最大攻击+5%",
		fontDesc = "生来便为战斗而生，‘杀戮使者’赐予持有者无尽的战斗渴望与力量",
		name = "杀戮使者",
		TMtype = 2,
	},
	[30] = { 
		xls_id = 30,
		attDesc = "杀死目标后恢复5%生命值（对人有效）",
		attackType = 15,
		buffId = 15003,
		fontDesc = "“传说中，此秘术源自远古战场，专为战士在激烈厮杀中迅速恢复生命而生。‘",
		name = "吸元秘术",
		TMtype = 1,
	},
	[32] = { 
		xls_id = 32,
		attDesc = "血量低于60%提升自身双防提升20%",
		value = 246,
		attackType = 7,
		buffId = 7005,
		fontDesc = "唯有历经生死，方能铸就真正的钢铁意志。",
		name = "铮铮铁骨",
		TMtype = {
			[1] = 3,
			[2] = 1,
		},
	},
}
return config
