--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(54)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1136.0000, height = 640.0000})
layout:setStretchWidthEnabled(true)
layout:setStretchHeightEnabled(true)
Scene:addChild(Panel_1)

--Create Panel_2
local Panel_2 = ccui.Layout:create()
Panel_2:ignoreContentAdaptWithSize(false)
Panel_2:setClippingEnabled(false)
Panel_2:setBackGroundColorOpacity(102)
Panel_2:setTouchEnabled(true);
Panel_2:setLayoutComponentEnabled(true)
Panel_2:setName("Panel_2")
Panel_2:setTag(47)
Panel_2:setCascadeColorEnabled(true)
Panel_2:setCascadeOpacityEnabled(true)
Panel_2:setAnchorPoint(0.5000, 0.5000)
Panel_2:setPosition(568.0000, 320.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.5722)
layout:setPercentHeight(0.6250)
layout:setSize({width = 650.0000, height = 400.0000})
layout:setLeftMargin(243.0000)
layout:setRightMargin(243.0000)
layout:setTopMargin(120.0000)
layout:setBottomMargin(120.0000)
Scene:addChild(Panel_2)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("res/public/1900000600.png",0)
Image_2:setScale9Enabled(true)
Image_2:setCapInsets({x = 10, y = 10, width = 432, height = 159})
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(48)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(325.0000, 200.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 650.0000, height = 400.0000})
Panel_2:addChild(Image_2)

--Create ScrollView_content
local ScrollView_content = ccui.ScrollView:create()
ScrollView_content:setInnerContainerSize({width = 550, height = 300})
ScrollView_content:ignoreContentAdaptWithSize(false)
ScrollView_content:setClippingEnabled(true)
ScrollView_content:setBackGroundColorOpacity(102)
ScrollView_content:setLayoutComponentEnabled(true)
ScrollView_content:setName("ScrollView_content")
ScrollView_content:setTag(51)
ScrollView_content:setCascadeColorEnabled(true)
ScrollView_content:setCascadeOpacityEnabled(true)
ScrollView_content:setAnchorPoint(0.5000, 1.0000)
ScrollView_content:setPosition(325.0000, 385.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ScrollView_content)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.9625)
layout:setPercentWidth(0.8462)
layout:setPercentHeight(0.7500)
layout:setSize({width = 550.0000, height = 300.0000})
layout:setLeftMargin(50.0000)
layout:setRightMargin(50.0000)
layout:setTopMargin(15.0000)
layout:setBottomMargin(85.0000)
Panel_2:addChild(ScrollView_content)

--Create Button_agree
local Button_agree = ccui.Button:create()
Button_agree:ignoreContentAdaptWithSize(false)
Button_agree:loadTextureNormal("res/private/server/btn_jryx_02.png",0)
Button_agree:loadTexturePressed("res/private/server/btn_jryx_02_1.png",0)
Button_agree:setTitleFontName("fonts/font.ttf")
Button_agree:setTitleFontSize(18)
Button_agree:setTitleText("同 意")
Button_agree:setScale9Enabled(true)
Button_agree:setCapInsets({x = 15, y = 11, width = 96, height = 56})
Button_agree:setLayoutComponentEnabled(true)
Button_agree:setName("Button_agree")
Button_agree:setTag(53)
Button_agree:setCascadeColorEnabled(true)
Button_agree:setCascadeOpacityEnabled(true)
Button_agree:setPosition(455.0000, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_agree)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.7000)
layout:setPositionPercentY(0.1250)
layout:setPercentWidth(0.1938)
layout:setPercentHeight(0.1950)
layout:setSize({width = 126.0000, height = 78.0000})
layout:setLeftMargin(392.0000)
layout:setRightMargin(132.0000)
layout:setTopMargin(311.0000)
layout:setBottomMargin(11.0000)
Panel_2:addChild(Button_agree)

--Create Button_refuse
local Button_refuse = ccui.Button:create()
Button_refuse:ignoreContentAdaptWithSize(false)
Button_refuse:loadTextureNormal("res/private/server/btn_jryx_02.png",0)
Button_refuse:loadTexturePressed("res/private/server/btn_jryx_02_1.png",0)
Button_refuse:setTitleFontName("fonts/font.ttf")
Button_refuse:setTitleFontSize(18)
Button_refuse:setTitleText("拒 绝")
Button_refuse:setScale9Enabled(true)
Button_refuse:setCapInsets({x = 15, y = 11, width = 96, height = 56})
Button_refuse:setLayoutComponentEnabled(true)
Button_refuse:setName("Button_refuse")
Button_refuse:setTag(13)
Button_refuse:setCascadeColorEnabled(true)
Button_refuse:setCascadeOpacityEnabled(true)
Button_refuse:setPosition(195.0000, 49.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_refuse)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentX(0.3000)
layout:setPositionPercentY(0.1225)
layout:setPercentWidth(0.1938)
layout:setPercentHeight(0.1950)
layout:setSize({width = 126.0000, height = 78.0000})
layout:setLeftMargin(132.0000)
layout:setRightMargin(392.0000)
layout:setTopMargin(312.0000)
layout:setBottomMargin(10.0000)
Panel_2:addChild(Button_refuse)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

