--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create Panel_bg
local Panel_bg = ccui.Layout:create()
Panel_bg:ignoreContentAdaptWithSize(false)
Panel_bg:setClippingEnabled(false)
Panel_bg:setBackGroundColorOpacity(102)
Panel_bg:setTouchEnabled(true);
Panel_bg:setLayoutComponentEnabled(true)
Panel_bg:setName("Panel_bg")
Panel_bg:setTag(150)
Panel_bg:setCascadeColorEnabled(true)
Panel_bg:setCascadeOpacityEnabled(true)
Panel_bg:setAnchorPoint(0.5000, 0.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_bg)
layout:setSize({width = 162.0000, height = 54.0000})
layout:setLeftMargin(-81.0000)
layout:setRightMargin(-81.0000)
layout:setTopMargin(-27.0000)
layout:setBottomMargin(-27.0000)
Node:addChild(Panel_bg)

--Create Button_group
local Button_group = ccui.Button:create()
Button_group:ignoreContentAdaptWithSize(false)
Button_group:loadTextureNormal("res/private/server/fuguchuanqi.apk_000857.png",0)
Button_group:loadTexturePressed("res/private/server/fuguchuanqi.apk_000858.png",0)
Button_group:setTitleFontName("fonts/font.ttf")
Button_group:setTitleFontSize(18)
Button_group:setTitleText("推荐区组")
Button_group:setScale9Enabled(true)
Button_group:setCapInsets({x = 15, y = 11, width = 132, height = 32})
Button_group:setLayoutComponentEnabled(true)
Button_group:setName("Button_group")
Button_group:setTag(156)
Button_group:setCascadeColorEnabled(true)
Button_group:setCascadeOpacityEnabled(true)
Button_group:setPosition(81.0000, 27.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_group)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 162.0000, height = 54.0000})
Panel_bg:addChild(Button_group)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

