--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_1:setBackGroundColorOpacity(102)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(29)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1136.0000, height = 640.0000})
layout:setStretchWidthEnabled(true)
layout:setStretchHeightEnabled(true)
Scene:addChild(Panel_1)

--Create Panel_2
local Panel_2 = ccui.Layout:create()
Panel_2:ignoreContentAdaptWithSize(false)
Panel_2:setClippingEnabled(false)
Panel_2:setBackGroundColorOpacity(102)
Panel_2:setTouchEnabled(true);
Panel_2:setLayoutComponentEnabled(true)
Panel_2:setName("Panel_2")
Panel_2:setTag(31)
Panel_2:setCascadeColorEnabled(true)
Panel_2:setCascadeOpacityEnabled(true)
Panel_2:setAnchorPoint(0.5000, 0.5000)
Panel_2:setPosition(568.0000, 320.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.6162)
layout:setPercentHeight(0.5781)
layout:setSize({width = 700.0000, height = 370.0000})
layout:setLeftMargin(218.0000)
layout:setRightMargin(218.0000)
layout:setTopMargin(135.0000)
layout:setBottomMargin(135.0000)
Scene:addChild(Panel_2)

--Create Image_2
local Image_2 = ccui.ImageView:create()
Image_2:ignoreContentAdaptWithSize(false)
Image_2:loadTexture("res/private/server/announce/bg_hefubq_01.jpg",0)
Image_2:setLayoutComponentEnabled(true)
Image_2:setName("Image_2")
Image_2:setTag(32)
Image_2:setCascadeColorEnabled(true)
Image_2:setCascadeOpacityEnabled(true)
Image_2:setPosition(350.0000, 185.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Image_2)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9700)
layout:setPercentHeight(0.9838)
layout:setSize({width = 679.0000, height = 364.0000})
layout:setLeftMargin(10.5000)
layout:setRightMargin(10.5000)
layout:setTopMargin(3.0000)
layout:setBottomMargin(3.0000)
Panel_2:addChild(Image_2)

--Create Button_close
local Button_close = ccui.Button:create()
Button_close:ignoreContentAdaptWithSize(false)
Button_close:loadTextureNormal("res/private/server/announce/1900000510.png",0)
Button_close:loadTexturePressed("res/private/server/announce/1900000511.png",0)
Button_close:setTitleFontSize(14)
Button_close:setTitleColor({r = 65, g = 65, b = 70})
Button_close:setScale9Enabled(true)
Button_close:setCapInsets({x = 8, y = 11, width = 10, height = 20})
Button_close:setLayoutComponentEnabled(true)
Button_close:setName("Button_close")
Button_close:setTag(33)
Button_close:setCascadeColorEnabled(true)
Button_close:setCascadeOpacityEnabled(true)
Button_close:setPosition(702.9996, 347.5000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_close)
layout:setPositionPercentX(1.0043)
layout:setPositionPercentY(0.9392)
layout:setPercentWidth(0.0371)
layout:setPercentHeight(0.1135)
layout:setSize({width = 26.0000, height = 42.0000})
layout:setLeftMargin(689.9996)
layout:setRightMargin(-15.9996)
layout:setTopMargin(1.5000)
layout:setBottomMargin(326.5000)
Panel_2:addChild(Button_close)

--Create ListView_group
local ListView_group = ccui.ListView:create()
ListView_group:setDirection(1)
ListView_group:setGravity(0)
ListView_group:ignoreContentAdaptWithSize(false)
ListView_group:setClippingEnabled(true)
ListView_group:setBackGroundColorOpacity(102)
ListView_group:setLayoutComponentEnabled(true)
ListView_group:setName("ListView_group")
ListView_group:setTag(34)
ListView_group:setCascadeColorEnabled(true)
ListView_group:setCascadeOpacityEnabled(true)
ListView_group:setAnchorPoint(0.0000, 1.0000)
ListView_group:setPosition(20.0000, 357.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ListView_group)
layout:setPositionPercentX(0.0286)
layout:setPositionPercentY(0.9649)
layout:setPercentWidth(0.1786)
layout:setPercentHeight(0.9297)
layout:setSize({width = 125.0000, height = 344.0000})
layout:setLeftMargin(20.0000)
layout:setRightMargin(555.0000)
layout:setTopMargin(13.0000)
layout:setBottomMargin(13.0000)
Panel_2:addChild(ListView_group)

--Create ScrollView_content
local ScrollView_content = ccui.ScrollView:create()
ScrollView_content:setInnerContainerSize({width = 500, height = 220})
ScrollView_content:ignoreContentAdaptWithSize(false)
ScrollView_content:setClippingEnabled(true)
ScrollView_content:setBackGroundColorOpacity(102)
ScrollView_content:setLayoutComponentEnabled(true)
ScrollView_content:setName("ScrollView_content")
ScrollView_content:setTag(36)
ScrollView_content:setCascadeColorEnabled(true)
ScrollView_content:setCascadeOpacityEnabled(true)
ScrollView_content:setAnchorPoint(0.5000, 1.0000)
ScrollView_content:setPosition(415.0000, 305.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ScrollView_content)
layout:setPositionPercentX(0.5929)
layout:setPositionPercentY(0.8243)
layout:setPercentWidth(0.7143)
layout:setPercentHeight(0.5946)
layout:setSize({width = 500.0000, height = 220.0000})
layout:setLeftMargin(165.0000)
layout:setRightMargin(35.0000)
layout:setTopMargin(65.0000)
layout:setBottomMargin(85.0000)
Panel_2:addChild(ScrollView_content)

--Create Node_title
local Node_title=cc.Node:create()
Node_title:setName("Node_title")
Node_title:setTag(43)
Node_title:setCascadeColorEnabled(true)
Node_title:setCascadeOpacityEnabled(true)
Node_title:setPosition(415.0000, 330.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Node_title)
layout:setPositionPercentX(0.5929)
layout:setPositionPercentY(0.8919)
layout:setLeftMargin(415.0000)
layout:setRightMargin(285.0000)
layout:setTopMargin(40.0000)
layout:setBottomMargin(330.0000)
Panel_2:addChild(Node_title)

--Create Button_sure
local Button_sure = ccui.Button:create()
Button_sure:ignoreContentAdaptWithSize(false)
Button_sure:loadTextureNormal("res/private/server/announce/1900000662.png",0)
Button_sure:loadTexturePressed("res/private/server/announce/1900000663.png",0)
Button_sure:setTitleFontName("fonts/font.ttf")
Button_sure:setTitleFontSize(18)
Button_sure:setTitleText("确 定")
Button_sure:setScale9Enabled(true)
Button_sure:setCapInsets({x = 15, y = 11, width = 85, height = 15})
Button_sure:setLayoutComponentEnabled(true)
Button_sure:setName("Button_sure")
Button_sure:setTag(37)
Button_sure:setCascadeColorEnabled(true)
Button_sure:setCascadeOpacityEnabled(true)
Button_sure:setPosition(415.0000, 50.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_sure)
layout:setPositionPercentX(0.5929)
layout:setPositionPercentY(0.1351)
layout:setPercentWidth(0.1643)
layout:setPercentHeight(0.1000)
layout:setSize({width = 115.0000, height = 37.0000})
layout:setLeftMargin(357.5000)
layout:setRightMargin(227.5000)
layout:setTopMargin(301.5000)
layout:setBottomMargin(31.5000)
Panel_2:addChild(Button_sure)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

