--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Scene
local Scene=cc.Node:create()
Scene:setName("Scene")

--Create Panel_1
local Panel_1 = ccui.Layout:create()
Panel_1:ignoreContentAdaptWithSize(false)
Panel_1:setClippingEnabled(false)
Panel_1:setBackGroundColorType(1)
Panel_1:setBackGroundColor({r = 0, g = 0, b = 0})
Panel_1:setBackGroundColorOpacity(204)
Panel_1:setTouchEnabled(true);
Panel_1:setLayoutComponentEnabled(true)
Panel_1:setName("Panel_1")
Panel_1:setTag(16)
Panel_1:setCascadeColorEnabled(true)
Panel_1:setCascadeOpacityEnabled(true)
layout = ccui.LayoutComponent:bindLayoutComponent(Panel_1)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 1136.0000, height = 640.0000})
Scene:addChild(Panel_1)

--Create TextField_export
local TextField_export = ccui.TextField:create()
TextField_export:ignoreContentAdaptWithSize(false)
tolua.cast(TextField_export:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
TextField_export:setFontSize(18)
TextField_export:setPlaceHolder("")
TextField_export:setString([[]])
TextField_export:setMaxLength(10)
TextField_export:setLayoutComponentEnabled(true)
TextField_export:setName("TextField_export")
TextField_export:setTag(17)
TextField_export:setCascadeColorEnabled(true)
TextField_export:setCascadeOpacityEnabled(true)
TextField_export:setPosition(568.0000, 320.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TextField_export)
layout:setPositionPercentXEnabled(true)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.5000)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentHeightEnabled(true)
layout:setPercentWidth(0.9000)
layout:setPercentHeight(0.9000)
layout:setSize({width = 1022.4000, height = 576.0000})
layout:setLeftMargin(56.8000)
layout:setRightMargin(56.8000)
layout:setTopMargin(32.0000)
layout:setBottomMargin(32.0000)
Panel_1:addChild(TextField_export)

--Create Button_close
local Button_close = ccui.Button:create()
Button_close:ignoreContentAdaptWithSize(false)
Button_close:loadTextureNormal("Default/Button_Normal.png",0)
Button_close:loadTexturePressed("Default/Button_Press.png",0)
Button_close:loadTextureDisabled("Default/Button_Disable.png",0)
Button_close:setTitleFontSize(16)
Button_close:setTitleText("退出")
Button_close:setTitleColor({r = 0, g = 0, b = 0})
Button_close:setScale9Enabled(true)
Button_close:setCapInsets({x = 15, y = 11, width = 16, height = 14})
Button_close:setLayoutComponentEnabled(true)
Button_close:setName("Button_close")
Button_close:setTag(18)
Button_close:setCascadeColorEnabled(true)
Button_close:setCascadeOpacityEnabled(true)
Button_close:setAnchorPoint(1.0000, 1.0000)
Button_close:setPosition(1130.0000, 640.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_close)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.9947)
layout:setPositionPercentY(1.0000)
layout:setPercentWidth(0.0440)
layout:setPercentHeight(0.0469)
layout:setSize({width = 50.0000, height = 30.0000})
layout:setLeftMargin(1080.0000)
layout:setRightMargin(6.0000)
layout:setBottomMargin(610.0000)
Panel_1:addChild(Button_close)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Scene
return result;
end

return Result

