--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create file_cell
local file_cell = ccui.Layout:create()
file_cell:ignoreContentAdaptWithSize(false)
file_cell:setClippingEnabled(true)
file_cell:setBackGroundColorOpacity(102)
file_cell:setTouchEnabled(true);
file_cell:setLayoutComponentEnabled(true)
file_cell:setName("file_cell")
file_cell:setTag(238)
file_cell:setCascadeColorEnabled(true)
file_cell:setCascadeOpacityEnabled(true)
file_cell:setVisible(false)
file_cell:setPosition(1256.1100, 286.1200)
layout = ccui.LayoutComponent:bindLayoutComponent(file_cell)
layout:setSize({width = 600.0000, height = 22.0000})
layout:setLeftMargin(1256.1100)
layout:setRightMargin(-1856.1100)
layout:setTopMargin(-308.1200)
layout:setBottomMargin(286.1200)
Node:addChild(file_cell)

--Create cell_bg_1
local cell_bg_1 = ccui.Layout:create()
cell_bg_1:ignoreContentAdaptWithSize(false)
cell_bg_1:setClippingEnabled(false)
cell_bg_1:setBackGroundColorOpacity(102)
cell_bg_1:setLayoutComponentEnabled(true)
cell_bg_1:setName("cell_bg_1")
cell_bg_1:setTag(239)
cell_bg_1:setCascadeColorEnabled(true)
cell_bg_1:setCascadeOpacityEnabled(true)
cell_bg_1:setVisible(false)
cell_bg_1:setAnchorPoint(0.0000, 0.5000)
cell_bg_1:setPosition(1.0000, 11.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(cell_bg_1)
layout:setPositionPercentX(0.0017)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9967)
layout:setPercentHeight(0.8182)
layout:setSize({width = 598.0000, height = 18.0000})
layout:setLeftMargin(1.0000)
layout:setRightMargin(1.0000)
layout:setTopMargin(2.0000)
layout:setBottomMargin(2.0000)
file_cell:addChild(cell_bg_1)

--Create cell_text
local cell_text = ccui.Text:create()
cell_text:ignoreContentAdaptWithSize(true)
cell_text:setTextAreaSize({width = 0, height = 0})
cell_text:setFontName("fonts/font.ttf")
cell_text:setFontSize(16)
cell_text:setString([[]])
cell_text:setTextVerticalAlignment(1)
cell_text:setLayoutComponentEnabled(true)
cell_text:setName("cell_text")
cell_text:setTag(240)
cell_text:setCascadeColorEnabled(true)
cell_text:setCascadeOpacityEnabled(true)
cell_text:setAnchorPoint(0.0000, 0.5000)
cell_text:setPosition(18.0000, 11.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(cell_text)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0300)
layout:setPositionPercentY(0.5000)
layout:setLeftMargin(18.0000)
layout:setRightMargin(582.0000)
layout:setTopMargin(11.0000)
layout:setBottomMargin(11.0000)
file_cell:addChild(cell_text)

--Create fileMask
local fileMask = ccui.ImageView:create()
fileMask:ignoreContentAdaptWithSize(false)
fileMask:loadTexture("res/private/gui_edit/image_1.png",0)
fileMask:setLayoutComponentEnabled(true)
fileMask:setName("fileMask")
fileMask:setTag(241)
fileMask:setCascadeColorEnabled(true)
fileMask:setCascadeOpacityEnabled(true)
fileMask:setPosition(9.0000, 10.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(fileMask)
layout:setPositionPercentX(0.0150)
layout:setPositionPercentY(0.4545)
layout:setPercentWidth(0.0500)
layout:setPercentHeight(0.9091)
layout:setSize({width = 30.0000, height = 20.0000})
layout:setLeftMargin(-6.0000)
layout:setRightMargin(576.0000)
layout:setTopMargin(2.0000)
file_cell:addChild(fileMask)

--Create cell_bg_2
local cell_bg_2 = ccui.Layout:create()
cell_bg_2:ignoreContentAdaptWithSize(false)
cell_bg_2:setClippingEnabled(false)
cell_bg_2:setBackGroundColorType(1)
cell_bg_2:setBackGroundColor({r = 191, g = 191, b = 191})
cell_bg_2:setBackGroundColorOpacity(106)
cell_bg_2:setLayoutComponentEnabled(true)
cell_bg_2:setName("cell_bg_2")
cell_bg_2:setTag(242)
cell_bg_2:setCascadeColorEnabled(true)
cell_bg_2:setCascadeOpacityEnabled(true)
cell_bg_2:setVisible(false)
cell_bg_2:setAnchorPoint(0.0000, 0.5000)
cell_bg_2:setPosition(1.0000, 11.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(cell_bg_2)
layout:setPositionPercentX(0.0017)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.9967)
layout:setPercentHeight(0.8182)
layout:setSize({width = 598.0000, height = 18.0000})
layout:setLeftMargin(1.0000)
layout:setRightMargin(1.0000)
layout:setTopMargin(2.0000)
layout:setBottomMargin(2.0000)
file_cell:addChild(cell_bg_2)

--Create tree_cell
local tree_cell = ccui.Layout:create()
tree_cell:ignoreContentAdaptWithSize(false)
tree_cell:setClippingEnabled(false)
tree_cell:setBackGroundColorOpacity(102)
tree_cell:setTouchEnabled(true);
tree_cell:setLayoutComponentEnabled(true)
tree_cell:setName("tree_cell")
tree_cell:setTag(234)
tree_cell:setCascadeColorEnabled(true)
tree_cell:setCascadeOpacityEnabled(true)
tree_cell:setVisible(false)
tree_cell:setPosition(1249.5440, 257.4185)
layout = ccui.LayoutComponent:bindLayoutComponent(tree_cell)
layout:setSize({width = 200.0000, height = 24.0000})
layout:setLeftMargin(1249.5440)
layout:setRightMargin(-1449.5440)
layout:setTopMargin(-281.4185)
layout:setBottomMargin(257.4185)
Node:addChild(tree_cell)

--Create Button_arr
local Button_arr = ccui.Button:create()
Button_arr:ignoreContentAdaptWithSize(false)
Button_arr:loadTextureNormal("res/private/gui_edit/arr.png",0)
Button_arr:loadTexturePressed("res/private/gui_edit/arr.png",0)
Button_arr:loadTextureDisabled("Default/Button_Disable.png",0)
Button_arr:setTitleFontSize(14)
Button_arr:setTitleColor({r = 65, g = 65, b = 70})
Button_arr:setLayoutComponentEnabled(true)
Button_arr:setName("Button_arr")
Button_arr:setTag(235)
Button_arr:setCascadeColorEnabled(true)
Button_arr:setCascadeOpacityEnabled(true)
Button_arr:setPosition(9.0000, 12.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Button_arr)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.0450)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.0750)
layout:setPercentHeight(0.6250)
layout:setSize({width = 15.0000, height = 15.0000})
layout:setLeftMargin(1.5000)
layout:setRightMargin(183.5000)
layout:setTopMargin(4.5000)
layout:setBottomMargin(4.5000)
tree_cell:addChild(Button_arr)

--Create cell_bg_1
local cell_bg_1 = ccui.Layout:create()
cell_bg_1:ignoreContentAdaptWithSize(false)
cell_bg_1:setClippingEnabled(false)
cell_bg_1:setBackGroundColorOpacity(102)
cell_bg_1:setLayoutComponentEnabled(true)
cell_bg_1:setName("cell_bg_1")
cell_bg_1:setTag(236)
cell_bg_1:setCascadeColorEnabled(true)
cell_bg_1:setCascadeOpacityEnabled(true)
cell_bg_1:setAnchorPoint(0.0000, 0.5000)
cell_bg_1:setPosition(0.0000, 12.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(cell_bg_1)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 200.0000, height = 24.0000})
tree_cell:addChild(cell_bg_1)

--Create cell_bg_2
local cell_bg_2 = ccui.Layout:create()
cell_bg_2:ignoreContentAdaptWithSize(false)
cell_bg_2:setClippingEnabled(false)
cell_bg_2:setBackGroundColorType(1)
cell_bg_2:setBackGroundColor({r = 191, g = 191, b = 191})
cell_bg_2:setBackGroundColorOpacity(153)
cell_bg_2:setLayoutComponentEnabled(true)
cell_bg_2:setName("cell_bg_2")
cell_bg_2:setTag(237)
cell_bg_2:setCascadeColorEnabled(true)
cell_bg_2:setCascadeOpacityEnabled(true)
cell_bg_2:setVisible(false)
cell_bg_2:setAnchorPoint(0.0000, 0.5000)
cell_bg_2:setPosition(0.0000, 12.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(cell_bg_2)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentY(0.5000)
layout:setPercentWidthEnabled(true)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(1.0000)
layout:setSize({width = 200.0000, height = 24.0000})
tree_cell:addChild(cell_bg_2)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

