--------------------------------------------------------------
-- This file was automatically generated by Cocos Studio.
-- Do not make changes to this file.
-- All changes will be lost.
--------------------------------------------------------------

local luaExtend = require "LuaExtend"

-- using for layout to decrease count of local variables
local layout = nil
local localLuaFile = nil
local innerCSD = nil
local innerProject = nil
local localFrame = nil

local Result = {}
------------------------------------------------------------
-- function call description
-- create function caller should provide a function to 
-- get a callback function in creating scene process.
-- the returned callback function will be registered to 
-- the callback event of the control.
-- the function provider is as below :
-- Callback callBackProvider(luaFileName, node, callbackName)
-- parameter description:
-- luaFileName  : a string, lua file name
-- node         : a Node, event source
-- callbackName : a string, callback function name
-- the return value is a callback function
------------------------------------------------------------
function Result.create(callBackProvider)

local result={}
setmetatable(result, luaExtend)

--Create Node
local Node=cc.Node:create()
Node:setName("Node")

--Create ui_Widget
local ui_Widget = ccui.Layout:create()
ui_Widget:ignoreContentAdaptWithSize(false)
ui_Widget:setClippingEnabled(false)
ui_Widget:setBackGroundColorOpacity(102)
ui_Widget:setTouchEnabled(true);
ui_Widget:setLayoutComponentEnabled(true)
ui_Widget:setName("ui_Widget")
ui_Widget:setTag(2843)
ui_Widget:setCascadeColorEnabled(true)
ui_Widget:setCascadeOpacityEnabled(true)
ui_Widget:setAnchorPoint(0.0000, 1.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(ui_Widget)
layout:setSize({width = 300.0000, height = 28.0000})
layout:setRightMargin(-300.0000)
layout:setBottomMargin(-28.0000)
Node:addChild(ui_Widget)

--Create a1
local a1 = ccui.Layout:create()
a1:ignoreContentAdaptWithSize(false)
a1:setClippingEnabled(false)
a1:setBackGroundColorOpacity(102)
a1:setLayoutComponentEnabled(true)
a1:setName("a1")
a1:setTag(2844)
a1:setCascadeColorEnabled(true)
a1:setCascadeOpacityEnabled(true)
a1:setAnchorPoint(0.0000, 1.0000)
a1:setPosition(0.0000, 24.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(a1)
layout:setPositionPercentY(0.8571)
layout:setPercentWidth(1.0000)
layout:setPercentHeight(0.7143)
layout:setSize({width = 300.0000, height = 20.0000})
layout:setTopMargin(4.0000)
layout:setBottomMargin(4.0000)
ui_Widget:addChild(a1)

--Create Text_name
local Text_name = ccui.Text:create()
Text_name:ignoreContentAdaptWithSize(true)
Text_name:setTextAreaSize({width = 0, height = 0})
Text_name:setFontSize(12)
Text_name:setString([[挂接界面]])
Text_name:setLayoutComponentEnabled(true)
Text_name:setName("Text_name")
Text_name:setTag(2845)
Text_name:setCascadeColorEnabled(true)
Text_name:setCascadeOpacityEnabled(true)
Text_name:setAnchorPoint(1.0000, 0.5000)
Text_name:setPosition(65.0000, 10.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(Text_name)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2167)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.1600)
layout:setPercentHeight(0.6000)
layout:setSize({width = 48.0000, height = 12.0000})
layout:setLeftMargin(17.0000)
layout:setRightMargin(235.0000)
layout:setTopMargin(4.0000)
layout:setBottomMargin(4.0000)
a1:addChild(Text_name)

--Create bg1
local bg1 = ccui.Layout:create()
bg1:ignoreContentAdaptWithSize(false)
bg1:setClippingEnabled(false)
bg1:setBackGroundColorType(1)
bg1:setBackGroundColor({r = 0, g = 0, b = 0})
bg1:setTouchEnabled(true);
bg1:setLayoutComponentEnabled(true)
bg1:setName("bg1")
bg1:setTag(2846)
bg1:setCascadeColorEnabled(true)
bg1:setCascadeOpacityEnabled(true)
bg1:setAnchorPoint(0.0000, 0.5000)
bg1:setPosition(70.0000, 10.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(bg1)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2333)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.7500)
layout:setPercentHeight(1.0000)
layout:setSize({width = 225.0000, height = 20.0000})
layout:setLeftMargin(70.0000)
layout:setRightMargin(5.0000)
a1:addChild(bg1)

--Create TextField_AttachUI
local TextField_AttachUI = ccui.TextField:create()
TextField_AttachUI:ignoreContentAdaptWithSize(false)
tolua.cast(TextField_AttachUI:getVirtualRenderer(), "cc.Label"):setLineBreakWithoutSpace(true)
TextField_AttachUI:setFontName("fonts/font.ttf")
TextField_AttachUI:setFontSize(14)
TextField_AttachUI:setPlaceHolder("")
TextField_AttachUI:setString([[]])
TextField_AttachUI:setMaxLength(3)
TextField_AttachUI:setLayoutComponentEnabled(true)
TextField_AttachUI:setName("TextField_AttachUI")
TextField_AttachUI:setTag(2847)
TextField_AttachUI:setCascadeColorEnabled(true)
TextField_AttachUI:setCascadeOpacityEnabled(true)
TextField_AttachUI:setAnchorPoint(0.0000, 0.5000)
TextField_AttachUI:setPosition(71.0000, 10.0000)
layout = ccui.LayoutComponent:bindLayoutComponent(TextField_AttachUI)
layout:setPositionPercentYEnabled(true)
layout:setPositionPercentX(0.2367)
layout:setPositionPercentY(0.5000)
layout:setPercentWidth(0.7433)
layout:setPercentHeight(0.9000)
layout:setSize({width = 223.0000, height = 18.0000})
layout:setLeftMargin(71.0000)
layout:setRightMargin(6.0000)
layout:setTopMargin(1.0000)
layout:setBottomMargin(1.0000)
a1:addChild(TextField_AttachUI)

--Create Animation
result['animation'] = ccs.ActionTimeline:create()
  
result['animation']:setDuration(0)
result['animation']:setTimeSpeed(1.0000)
--Create Animation List

result['root'] = Node
return result;
end

return Result

